all Number Filter":"filtrage numéro d'appel",
    " Distinctive Ring Tones":"tonalités distinctives",
    " Do you want to reboot ?":"Do you want to reboot?",
    "(800*480)":"(800*480)",
    "10min":"10 min",
    "1min":"1 min",
    "2min":"2 min",
    "30min":"30min",
    "404 (Not found)":"404 (Not Found)",
    "480 (Temporarily not available)":"480 (Temporarily  unavailable)",
    "486 (Busy here)":"486 (Busy here)",
    "5min":"5 min",
    "603 (Decline)":"603 (Refuser)",
    "ACD Auto Available Timer(0~120s)":"Délai auto-disponibilté ACD (0~120s)",
    "ACD Auto Available":"ACD Auto disponible",
    "ACD Trace":"Trace ACD",
    "ACD":"ACD",
    "ACD:":"ACD",
    "ACD_SubscripPeriod(120~3600s)":"Période souscription ACD(120~3600s)",
    "ACS Password":"Mot de passe ACS",
    "ACS URL":"URL ACS",
    "ACS Username":"nom d'utilisateur ACS",
    "AES-32":"AES-32",
    "AES-80":"AES-80",
    "AES-80&&AES-32":"AES-80&&AES-32",
    "AUTO+SIP INFO":"AUTO or SIP INFO",
    "Account":"Compte",
    "Account1":"Compte 1",
    "Account10":"Compte 10",
    "Account11":"Compte 11",
    "Account12":"Compte 12",
    "Account13":"Compte 13",
    "Account14":"Compte 14",
    "Account15":"Compte 15",
    "Account16":"Compte 16",
    "Account2":"Compte 2",
    "Account3":"Compte 3",
    "Account4":"Compte 4",
    "Account5":"Compte 5",
    "Account6":"Compte 6",
    "Account7":"Compte 7",
    "Account8":"Compte 8",
    "Account9":"Compte 9",
    "AccountStatus":"Account Status",
    "AccountStatusId":"AccountStatusId ",
    "Action URL":"Action URL",
    "Active Backlight Level":"Intensité rétro-éclairage",
    "Active":"Actif",
    "Adaptive":"Adapté",
    "Add":"Ajouter",
    "Advanced":"Avancé",
    "After_ring_times scope2":"Après durée de sonnerie (0~120s)",
    "All Cert":"Tous certificats",
    "All Contacts":"Tous les contacts",
    "All Keys":"toutes les touches",
    "All_Configuration":"toute la configuration",
    "Allow IP Call":"Autorise l'appel IP direct",
    "Allow SIP Authentication for XSI":"Autoriser l'authentification  SIP pour XSI ",
    "Allow Trans Exist Call":"Autorise le transfert entre appels existants",
    "AllowIntercom":"Autoriser Intercom",
    "AllowMute":"Autoriser Silence",
    "AlwaysOff":"toujours Off",
    "AlwaysOn":"Always On",
    "Always_forward_to":"Renvoi inmmédiat vers",
    "And the browser must not be closed or refreshed!":"Et le navigateur ne doit pas être fermé ou rafraîchi!",
    "AnonymousCall OffCode can not contain ! and &":"Anonymous Call Off Code can not contain ! and &",
    "AnonymousCall OnCode can not contain ! and &":"Anonymous Call On Code can not contain ! and &",
    "AnonymousReject OffCode can not contain ! and &":"Anonymous Reject Off Code can not contain ! and &",
    "AnonymousReject OnCode can not contain ! and &":"Anonymous Reject On Code can not contain ! and &",
    "Anonymous_Call":"Appel anonyme",
    "Anonymous_Call_Rejection":"Rejet des appels anonymes",
    "Answer By Hand":"Répondre Manuellement",
    "Answer":"Répondre",
    "AnswerNewInCall":"Répondre nouvel appel",
    "Answer_call_only":"Answer call only",
    "Append_Delete":"Supprimer_Ajout",
    "Append_Limit_Mode":"Mode_Limite_Ajout",
    "Append_Limit_Size":"Taille_Limite_Ajout",
    "Append_Stop":"Arrêter_Ajout",
    "Apr":"Avril",
    "April":"Avril",
    "Are you sure delete user-defined factory config?":"Etes-vous sûr de supprimer la configuration définis par l'utilisateur et d'appliquer la configuration usine?",
    "Are you sure to delete the chosen photo?":"Etes-vous sûr de vouloir supprimer les photos sélectionnées?",
    "Are you sure to remove the ringtone??":"Êtes-vous sûr de vouloir supprimer la sonnerie?",
    "Are you sure to remove the wallpaper??":"Etes-vous sûr de vouloir supprimer les images de fond?",
    "Are you sure to set a blank password?":"Are you sure to set a blank password?",
    "Area Code":"Préfixe local",
    "As Bridge":"Mode pont",
    "As Router":"Mode routeur",
    "AsSend":"Touche pour numérotation",
    "Ask customers downloading status failed!!":"Echec lors de la demande de téléchargement client!",
    "Attended Tranfer":"Transfert accompagné",
    "Attended Transfer":"Attended Transfert",
    "Audio Alert for BLF Pickup":"Alerte Audio pour interception BLF",
    "Audio Alert for Parked Call":"Alerte Audio pour appel parqué",
    "Audio Settings:":"Réglages Audio",
    "Audio codecs":"Audio Codecs",
    "Audio":"acoustique",
    "Aug":"Aout",
    "August":"Ao?t",
    "Australia":"Australie",
    "Austria":"Autriche",
    "Auto Provision":"Auto Provision",
    "Auto":"Auto",
    "Auto-negotiation":"Auto-négociation",
    "AutoAnswer":"Réponse automatique",
    "AutoAnswerDelay":"Délai Auto Réponse",
    "AutoRedial":"Recomposition",
    "AutoRedialInterval (1~300s)":"Intervalle Recomposition Auto (1~300s)",
    "AutoRedialInterval should be a number !!":"Intervalle rappel automatique doit être un chiffre!",
    "AutoRedialTimes (1~300)":"Temps Recomposition Auto (1~300s)",
    "AutoRedialTimes should be a number !!":"Nombre rappel automatique doit être un chiffre!",
    "Auto_answer":"Réponse automatique",
    "Automatic":"Automatique",
    "AutopFinish":"Autop Finish",
    "Autoprovision Now":"Autoprovision Now",
    "Autoprovision":"Auto-provisioning",
    "BLA_Number":"Numéro BLA",
    "BLA_Subscription_Period":"Durée d'enregistrement BLA",
    "BLF LED Mode":"LED Mode BLF ",
    "BLF List Retrieve call parked Code":" code  Liste BLF Récupérer appel parqué",
    "BLF List":"BLF List",
    "BLF":"BLF",
    "BLFList_URL":"URI liste BLF",
    "BackLightTime":"Durée de rétro-éclairage",
    "BackLightTime(seconds)":"temps rétroéclairage (secondes)",
    "Base":"Base",
    "Basic":"de base",
    "Begin time can't be later than end time!":"L'heure de début ne peut pas être plus tard que l'heure de fin!",
    "Belgium":"Belgique",
    "Blacklist":"Liste noire",
    "BlfListBargeInCode":"Code Liste BLF",
    "BlfList_Code":"BLF List Code",
    "Blind Transfer OnHook":"Blind Transfer On Hook",
    "Blind Transfer":"Transfert aveugle",
    "Block Out":"Interdit",
    "Block XML In Calling":"Block XML In Calling",
    "BlockOut Number":"Numéros interdits",
    "Bluetooth Active":"Bluetooth actif",
    "Bluetooth Settings:":"Paramètres Bluetooth",
    "Bluetooth":"Bluetooth",
    "Brazil":"Brésil",
    "Bridge":"Pont",
    "BroadSoft Buddies":"BroadSoft Buddies",
    "Broadsoft Directory":"BroadSoft Directory",
    "Broadsoft":"Broadsoft",
    "BroadsoftActive":"Broadsoft Actif",
    "Broadsoft_SCA":"Broadsoft SCA",
    "Browser":"Navigateur",
    "Buddies":"amis",
    "Busy To Idle":"Busy To Idle",
    "Busy":"Occupé",
    "BusyToneDelay scope2":"Retard de tonalité d'occupation  (secondes)",
    "Busy_forward_to":"Renvoi sur occupation vers",
    "Button Sound":"Key Tone",
    "CA_Certificate":"CA Certificate",
    "CA_Certificates":"Certificats CA",
    "CDP":"CDP",
    "CIDSource":"En-tête Appelant",
    "CM  Key":"CM clé",
    "CNG":"CNG",
    "CONF":"CONF",
    "Call Display":"Affichage appel",
    "Call Information Display Method":" Méthode d'affichage Infos appel",
    "Call Panel":"Contrôle d'appel",
    "Call Park Code":"code parcage appel",
    "Call Park Mode":"Mode parcage appel",
    "Call Park":"Parcage d'appel",
    "Call Park:":"Call Park",
    "Call Pickup":"Interception",
    "Call Pickup:":"Interception",
    "Call Pull Feature access code":"Call pull Feature Access Code",
    "Call Return":"Rappeler",
    "Call States":"état des appels",
    "Call Waiting Tone":"Tonalité d'Appel en Attente",
    "CallCompletion":"Rappel automatique",
    "CallFailed":"appel échoué",
    "CallIn":"Appels entrants",
    "CallList_Show_Num":"Montrer numéro sur historique",
    "CallLog":"Call Log",
    "CallWaiting":"Signal d'appel",
    "CallWaitingOffCode":"Code Off attente appel",
    "CallWaitingOnCode":"Code On attente appel",
    "Call_List":"Liste d'appels",
    "Call_Waiting":"Signal d'appel",
    "Callog:":"Journal des appels",
    "Can't move to same group!":"ne peut pas être déplacé dans le même groupe",
    "Cancel":"Annuler",
    "Chile":"Chili",
    "China":"Chine",
    "Chinese_S":"简体中文(Chinese Simplified)",
    "Chinese_T":"繁体中文(Chinese Traditional)",
    "ChoiceSRTP":"ChoiceSRTP ",
    "Close Always Forward":"Désactiver renvoi immédiat ",
    "Close Busy Forward":"Désactiver renvoi occup",
    "Close DND":"Fermer ne pas déranger",
    "Close NoAnswer Forward":"Désactiver renvoi non rep",
    "Close Power Light":"fermer l'alimentation de la lumière",
    "Code":"Préfixe",
    "Codec":"Codecs",
    "Common AES Key":"Clef AES spécifique",
    "Common Power Light On":"Common Power Light On",
    "Common":"Commun",
    "Common_Name_Validation":"Validation nom commun",
    "Company":"Société",
    "Compulsory":"obligatoire",
    "Conference":"Conf",
    "Conference_Type":"Type Conférence",
    "Conference_URI":"URI Conférence",
    "Conferenced":"en conférence",
    "Configuration updating ...":"Configuration updating...",
    "Configuration updating, please wait!":"Configuration mise à jour!",
    "Configuration":"Configuration",
    "Confirm Password":"Confirmer mot de passe",
    "Confirm":"Confirmer",
    "Congestion":"Encombrement",
    "Connected":"Connecté",
    "Connecting":"en connexion",
    "ConnectionRequestPassword":"Demande connexion mot de passe",
    "ConnectionRequestUsername":"Demande connexion nom d'utilisateur",
    "Contacts":"Répertoire",
    "Content shouldn't be empty !":"Le champ Contenu doit être rempli !",
    "Contrast":"Contraste écran",
    "CosmoCom":"cosmocom",
    "Critical threshold for Delay":"seuil critique pour délai",
    "Critical threshold for Moslq":"seuil critique pour Moslq ",
    "Current Time":"Heure actuelle",
    "Custom Button":"touche personnalisée",
    "Custom Cert":"Certificats personnalisés",
    "Custom Directories:":"repertoire personnalisé",
    "Custom Option":"Option personnalisée",
    "Custom SoftKey":"touche personnalisée",
    "Custom logo":"Logo personnalisé",
    "Custom":"coutume",
    "CustomFactoryConfig":"Configuration d'usine personnalisée",
    "Czech ETSI":"ETSI tchèque",
    "Czech":"tchèque",
    "DD MMM YYYY":"JJ MMM AAAA",
    "DD-MMM-YY":"JJ-MMM-AA",
    "DD/MM/YY":"JJ / MM / AA ",
    "DD/MM/YYYY":"JJ/MM/AAAA",
    "DHCP Active":"DHCP actif",
    "DHCP Option Value":"Valeur option DHCP",
    "DHCP VLAN":"VLAN DHCP",
    "DHCP":"DHCP",
    "DHCPTime":"Heure via DHCP",
    "DHCP_Server_Status":"Etat serveur DHCP (PC)",
    "DND Status":"Etat NPD",
    "DND":"DND",
    "DND:":"DND",
    "DNDActive":"Ne pas Déranger Actif",
    "DNDEmergency":"Urgence ne pas déranger",
    "DND_Authorized_Numbers":"Numéros autorisés ne pas déranger",
    "DND_Off_Code":"Code Off Ne Pas Déranger",
    "DND_On_Code":"Code On Ne Pas Déranger",
    "DNS-NAPTR":"DNS-NAPTR",
    "DPickup":"interception dirigée",
    "DST Start Day of Week Last in Month":"Choix du jour de début",
    "DST Start Day of Week":"Jour de début",
    "DST Start Month":"Mois de début",
    "DST Stop Day of Week Last in Month":"Choix du jour de fin",
    "DST Stop Day of Week":"Jour de fin",
    "DST Stop Month":"Mois de fin",
    "DST_ByDate":"Par Date",
    "DST_ByWeek":"Par Semaine",
    "DTMF":"DTMF",
    "DTMF-Relay":"DTMF-Relay",
    "DTMFRepetition":"DTMFRepetition",
    "DTMFReplaceTran":"Déviation Via DTMF",
    "DTMF_Info_Type":"INFO DTMF",
    "DTMF_Payload seconds(96~255s)":"Type DTMF Payload (96~127)",
    "DTMF_Type":"Type DTMF",
    "Date":"Date",
    "Date_Format":"Format Date",
    "Day of week":"Jour de la semaine",
    "Day":"Jour",
    "Daylight Saving Time":"Heure d'été",
    "Dec":"décembre",
    "December":"Décembre",
    "Default Cert":"Certificats par défaut",
    "Default Gateway":"Passerelle par défaut",
    "Default":"Par défaut",
    "Del":"Del",
    "DelOldcontact":"Delete Old contact",
    "Delay must less than 300 !":"Max delay must less than 300!",
    "Delay must more than 60 !":"Min delay must more than 60!",
    "Delete All":"supprimer tout",
    "Delete Photo":"Delete Photo",
    "Delete server certs error!":"Supprimer erreur certs serveur! ",
    "Delete":" Supprimer ",
    "Denmark":"Danemark",
    "Deutsch":"Deutsch",
    "Device_Certificate":"Device Certificate",
    "Device_Certificates":"Certificats équipement",
    "Device_Type":"Connexion WAN/LAN",
    "Dia_Number":"Composez le numéro",
    "Dial Plan":"Dial Plan",
    "Dial":"Numéroter",
    "Dial-now Rule should not be empty!":"La règle de composez maintenant ne doit pas être vide!",
    "Dial-now Rule":"Règle de numérotation directe",
    "Dial-now":"Numérotation directe",
    "Dial_recall":"Rappel",
    "Dialed_List":"Appels émis",
    "Dialing":"en Numérotation",
    "DialogInfo_Call_Pickup":"Interception d'appel Dialog-Info",
    "Direct Call Pickup Code":"Code d'interception dirigée",
    "Direct Call Pickup":"Interception d'appels dirigée",
    "Direct Pickup":"interception dirigée",
    "Directories":"Annuaires",
    "Directory":"Répertoire",
    "Directotries:":"repertoire réseau",
    "Disable codecs":"Codecs disponibles",
    "Disable":"désactiver",
    "Disabled":"Désactivé",
    "Disp Code":"Code Disp",
    "Display Called Party Information":"Affichage  informations de l'appelé ",
    "Display Contact Photo":"Afficher Photo Contact",
    "Display Forward Call Popup":"Afficher Renvoi d'appel Popup ",
    "Display Method on Dialing":"Méthode d'affichage sur la numérotation ",
    "Display Missed Call Popup":"Affichage des appels manqués Popup ",
    "Display Name":"Nom",
    "Display Report options on Web":"Les options de rapport d'affichage sur le Web ",
    "Display Report options on phone":"Les options de rapport d'affichage sur le téléphone ",
    "Display Text Message Popup":"Afficher un message texte Popup",
    "Display Voice Mail Popup":"Afficher messagerie vocale Popup ",
    "Diversion/History-Info":"Diversion/Historique-Info",
    "Do not support bridge in PPPoE mode!":"Do you want to auto provision now?",
    "Do not support vlan in PPPoE mode!":"ne supporte pas le VLAN en mode PPPoE!",
    "Do you want to autoprovision now?":"Do you want to auto provision now?",
    "Do you want to delete all contacts in BlackList?":"Voulez-vous supprimer tous les contacts en liste noire?",
    "Do you want to delete all contacts in ContactList?":"Voulez-vous supprimer tous les contacts dela liste des contacts?",
    "Do you want to discard your changes??":"Voulez-vous abandonner vos modifications?",
    "Do you want to import the configuration file to All_Configuration":"Voulez-vous importer le fichier de configuration à All_Configuration ",
    "Do you want to import the configuration file to Local_Configuration":"Voulez-vous importer le fichier de configuration à Local_Configuration ",
    "Do you want to move the contacts to ":"Voulez-vous déplacer les contacts à ",
    "Do you want to reset to factory ?":"Do you want to reset to factory?",
    "Do you want to restart your machine?":"Voulez-vous redémarrer votre appareil ?",
    "Down":"vers le bas",
    "Download failed!":"Le téléchargement a échoué!",
    "Download failed, please try again":"Chargement échoué, veuillez réessayer s'il vous plaît!",
    "Downloading custom list, please try latter!!":"Chargement liste personnalisée en cours, veuillez réessayer plus tard!",
    "Dsskey":"Touche",
    "Dual Headset":"double casque",
    "E-Common":"E-commune",
    "EAP-FAST":"EAP-FAST",
    "EAP-MD5":"EAP-MD5",
    "EAP-PEAP/GTC":"EAP-PEAP/GTC",
    "EAP-PEAP/MSCHAPv2":"EAP-PEAP/MSCHAPv2",
    "EAP-TLS":"EAP-TLS",
    "EAP-TTLS/EAP-GTC":"EAP-TTLS/EAP-GTC",
    "EAP-TTLS/EAP-MSCHAPv2":"EAP-TTLS/EAP-MSCHAPv2",
    "ECHO":"ECHO",
    "Early Media":"Early Media",
    "Echo_Cancellation":"Suppression d'écho",
    "Edit":"éditer",
    "Emergency":"Urgence",
    "Empty":"vide",
    "Enable AutoFavorite":"Enable AutoFavorite",
    "Enable Custom Directories":"Activer répertoire personnel",
    "Enable DHCP Server":"activer le serveur DHCP",
    "Enable LDAP":"Activer LDAP",
    "Enable Periodic Inform":"activer information périodique",
    "Enable Semi-Attend Transfer":"Activer transfert semi-accompagné",
    "Enable Signal Encode":"Activer Codage signal",
    "Enable TR069":"activer TR069",
    "Enable codecs":"Codecs utilisables",
    "Enable":"Autoriser",
    "EnablePageTips":"Activer conseils page",
    "EnableSessionTimer":"Utiliser délai de session",
    "EnableUserEqualPhone":"Utiliser user",
    "Enable_Outbound_Proxy_Server":"Activer serveur proxy Outbound",
    "Enable_SemiAttend_Transfer":"Transfert en aveugle autorisé",
    "Enabled":"Activé",
    "End Call":"fin de l'appel",
    "End Date":"Date de fin",
    "End Hour of Day":"Heure du jour de fin",
    "End IP Address":"adresse Ip de fin",
    "EndSystemDelay":"EndSystemDelay",
    "English":"Anglais(English)",
    "Enter at least 6 characters with 1 number and 1 alphabet min":"Entrez au moins 6 caractères avec au moins 1 chiffre et un caractère alphabétique!",



    "Enterprise IP phone SIP-T23P":"Enterprise téléphone  SIP-T23P",
    "Enterprise IP phone SIP-T23G":"Enterprise téléphone SIP-T23G",

    "Enterprise IP phone SIP-T27P":"Enterprise téléphone  SIP-T27P",
    "Enterprise IP phone SIP-T27G":"Enterprise téléphone SIP-T27G",
    "Gigabit Color IP Phone SIP-T29G":"Gigabit Color IP Phone SIP-T29G",
    "Enterprise IP phone SIP-T42G":"Enterprise téléphone  SIP-T42G",	
    "Enterprise IP phone SIP-T42P":"Enterprise téléphone  SIP-T42P",
    "Enterprise IP phone SIP-T41G":"Enterprise téléphone  SIP-T41G",
    "Enterprise IP phone SIP-T41P":"Enterprise téléphone  SIP-T41P",							
    "Gigabit Color IP Phone SIP-T46G":"Téléphone IP Gigabit Couleur SIP-T46G ",
    "Enterprise IP phone SIP-T61P":"Enterprise téléphone  SIP-T61P",
    "Enterprise IP phone SIP-T61G":"Enterprise téléphone  SIP-T61G",
    "Enterprise IP phone SIP-T66G":"Enterprise téléphone  SIP-T66G",
    "Enterprise IP phone SIP-T66P":"Enterprise téléphone  SIP-T66P",
    "Enterprise:":"Entreprise",
    "EnterpriseCommon:":"Entreprise commune",
    "Error: Element's name is empty!":"Erreur: le nom de l'élément est vide! ",
    "Error: More than 50 groups.":"Erreur: plus de 50 groupes.",
    "Error: More than 50.":"Error: More than 50 groups.",
    "Error: More than five groups.":"Erreur : plus de 5 groupes",
    "Error: Record with the same Prefix already exists!":"Erreur : un item avec le même préfixe existe déjà",
    "Error: Record with the same Rule already exists!":"Erreur: objet avec les mêmes règles déjà existant!",
    "Error: Same config":"Error: Same config!",
    "Error: The max dial-now count is ":"Erreur: Le nombre maximal de numérotation directe est ",
    "Error: The maximum number of certificates is 10, please delete one before upload":"Erreur: Le nombre maximal de certificats est de 10. \nVeuillez supprimer un avant de les charger!",
    "Error: The same record already exists!":"Erreur : le même item existe déjà",
    "Error: Write dsskey config error!":"Erreur: Ecrire dsskey erreur de configuration! ",
    "Error:Black list is full!":"Erreur: liste noire complète!",
    "Error:Contact already existed!":"Erreur: Contact existait déjà! ",
    "Error:Contact is asyncing!":"Error:Contact is asyncing!",
    "Error:Contact is not black!":"Erreur: le Contact n'est pas dans la liste  noire! ",
    "Error:Contact is not local!":"Erreur: le Contact n'est pas local! ",
    "Error:Contact list is full!":"Erreur: la liste de contacts est pleine! ",
    "Error:Contact name empty!":"Erreur: Nom de contact vide! ",
    "Error:Contact not existed!":"Erreur: le Contact n'existe pas! ",
    "Error:Delete ring error!":"Erreur: erreur de suppression de sonnerie! ",
    "Error:Duplcate contact!":"Erreur: le contact est en double! ",
    "Error:Duplicate group!":"Erreur: groupe double! ",
    "Error:Export contact file error!":"Erreur:  erreur export de fichier de contact! ",
    "Error:File isn't exist!":"Erreur: le fichier n'existe pas! ",
    "Error:File upload error!":"Erreur:  erreur de téléchargement fichier! ",
    "Error:Group  list is full!":"Erreur: la  liste de groupe est pleine! ",
    "Error:Group already existed!":"Erreur: Le Groupe existait déjà! ",
    "Error:Group can not delete!":"Erreur: Le groupe ne peut pas étre supprimé! ",
    "Error:Group empty!":"Erreur: Groupe vide! ",
    "Error:Group not existed!":"Erreur:Le  Groupe n'existait pas! ",
    "Error:Import config error!":"Erreur: erreur d'importation de la config! ",
    "Error:Import contact file error!":"Erreur: Erreur d'importation du fichier de contact! ",
    "Error:Import local config error!":"Erreur: erreur d'importation de la config locale! ",
    "Error:Invalid file!":"Erreur: fichier non valide! ",
    "Error:Invalid group id!":"Erreur: identifiant de groupe invalide! ",
    "Error:Invalid path!":"Erreur: chemin invalide! ",
    "Error:Network error!":"Erreur: Erreur de réseau! ",
    "Error:No contact group!":"Erreur: Pas de groupe de contact! ",
    "Error:No default group!":"Erreur: Pas de groupe par défaut! ",
    "Error:No space left!":"Erreur: Pas d'espace à gauche! ",
    "Error:Other error!":"Erreur: Autre erreur! ",
    "Error:Photo name error!":"Erreur:  erreur du nom de la photo! ",
    "Error:The destination folder does not exist!":"Erreur: Le dossier de destination n'existe pas! ",
    "Error:The password is error!":"Erreur: Le mot de passe est erroné! ",
    "Error:Too many blacklist!":"Erreur: Trop de liste noire! ",
    "Error:Too many group!":"Erreur: Trop de groupe! ",
    "Error:Too many local contact!":"Erreur: Trop de contacts locaux!",
    "Error:Upload error!":"Erreur: Erreur de chargement! ",
    "Error:User factory config doesn't exist!":"Erreur: il n'existe pas de config utilisateur usine! ",
    "Error:Write remote_phonebook_list.xml error!":"Erreur: Erreur d'écriture remote_phonebook_list.xml! ",
    "Error:You don't have enough jurisdiction!":"Erreur: Vous n'avez pas assez de compétence!",
    "Established":"Appel établi",
    "Exist the ring!":"La sonnerie existe!",
    "Exp Switch":"Exp Switch",
    "Expansion Key":"touche d'extension",
    "Expansion":"Expansion",
    "Expiration":"Expiration",
    "Export CFG Configuration File":"Exporter le fichier de configuration CFG ",
    "Export CSV":"Export CSV",
    "Export System Log":"Exporter Log système",
    "Export XML":"Export XML",
    "Export":"exportation",
    "Export_Import_Config":"Export / Import Configuration",
    "Ext Key":"Module d'extension",
    "Ext":"Ext",
    "Extended":"prolongé",
    "Extension":"Extension",
    "FAC":"FAC",
    "FROM":"DE",
    "Fail : Too many keys !":"échoue: trop de touches",
    "Fail to upload photo ! [Can not compress the picture]":"Chargement photo échoué! [Vous ne pouvez pas compresser l'image] ",
    "Fail to upload photo ! [The Resolution of the picture is too large]":"Chargement photo échoué! [La résolution de l'image est trop grande] ",
    "Failed":"manqué",
    "Family":"Famille",
    "Favorite":"favori",
    "Favorites":"favoris",
    "Feature_Key_Synchronisation":"Synchronisation paramètres utilisateur",
    "Features":"Fonction",
    "Feb":"Fev",
    "February":"Février",
    "File Name is too long!":"Nom de fichier trop long!",
    "Finland":"Finlande",
    "Firmware Version":"firmware Version",
    "Firmware of the SIP Phone will be updated. \nIt will take 5 minutes to complete.Please don't power off!":"le Firmware du téléphone SIP va être mis à jour. Cela prendra 5 minutes . Ne pas éteindre SVP!",
    "Firmware of the SIP Phone will be updated.":"Firmware du téléphone SIP sera mis à jour. ",
    "Firmware updating ...":"Firmware mise à jour ...",
    "Firmware_Version":"Version Firmware",
    "First In Month":"Premier du mois",
    "Fixed Type":"Type choisi",
    "Fixed":"Fixe",
    "ForbinSRTP":"Forbin SRTP",
    "ForceSRTP":"Forcer SRTP",
    "Forward":"Renvoi",
    "Forward&DND":"Renvoi et NPD",
    "Forward:":"Renvoi",
    "ForwardActive":"Déviation Actif",
    "ForwardIncomingCall":"ForwardIncomingCall",
    "Forwarded_List":"Liste déviation",
    "Fourth In Month":"Quatrième du mois",
    "France":"France",
    "French":"Français(French)",
    "Fri":"Ven",
    "Friday":"Vendredi",
    "Friend":"Amis",
    "Full Contact Info":"Full Contact Infos ",
    "Funckey":"Touche de fonction",
    "Fwd International":"Déviation internationale",
    "G-Common":"G-Common",
    "G722":"G722",
    "G723_53 and G723_63  can not be applied simultaneously":"G723_53 et G723_63 ne peut être appliqué en même temps!",
    "G723_53":"G723_53",
    "G723_63":"G723_63",
    "G726-16":"G726-16",
    "G726-24":"G726-24",
    "G726-32":"G726-32",
    "G726-40":"G726-40",
    "G729":"G729",
    "GPark":"Parquage groupe",
    "GPickup":"GrpIntr",
    "GSM":"GSM",
    "Gateway IP address is invalid":"L'adresse IP de la passerelle n'est pas valide!",
    "Gateway IPv6 address is invalid":"L'adresse IPv6 de la passerelle n'est pas valide!",
    "Gateway":"Passerelle",
    "General Information":"informations générales",
    "General_Information":"General Information:",
    "German":"Allemand",
    "Germany":"Allemagne",
    "Get CSVFile data error!":"rreur de données CSVFile! ",
    "Great Britain":"grande-Bretagne",
    "Greece":"Grèce",
    "Group Call Park":"Groupe de parquage",
    "Group Call Pickup Code":"Code d'interception universelle",
    "Group Call Pickup":"Interception universelle",
    "Group Listen":"Group Listening",
    "Group Pickup":"Group Pickup",
    "Group Setting":"Réglages de groupe",
    "Group":"Groups",
    "Group:":"Groups",
    "GroupCommon:":"Groupe commun",
    "HOLD":"Attente",
    "HTTP Port (1~65535)":"HTTP Port (1~65535)",
    "HTTP":"HTTP",
    "HTTPS Port (1~65535)":"HTTPS Port (1~65535)",
    "HTTPS":"HTTPS",
    "HTTPS_Only":"HTTPS Only",
    "HTTP_HTTPS":"HTTP&HTTPS",
    "HTTP_Only":"HTTP Only",
    "Handfree Send Volume (1~53)":"Mains libres Volume (1 ~ 53)",
    "Handset Send Volume (1~53)":"Combiné Volume (1 ~ 53)",
    "Hang Up":"raccrocher",
    "Hangup":"Raccrocher",
    "Hardware Version":"Version du matériel",
    "Hardware_Version":"Version Hardware",
    "Headset Prior":"Casque avant",
    "HeadsetSendVolume (1~53)":"Casque Volume (1 ~ 53)",
    "HeadsetSendVolume(1~53)":"Casque Volume (1 ~ 53)",
    "Held":"Mise en attente",
    "Hidden":"Invisible",
    "Hide Feature Access Codes":"Codes d'accès de fonctions cachées",
    "High":"Élevé",
    "History":"Histoire",
    "Hold":"Attente",
    "Hold/Held Power Light On":"Hold/Held Power Light On",
    "Host Server":"serveur hôte",
    "HotDesking":"Hot Desking",
    "HotLine_Number":"Numéro d'appel au décroché",
    "Hoteling":"Hôtel",
    "Hotline Number should be a number or IP address!!":"Le numéro  Hotline doit être un nombre ou une adresse IP !! ",
    "Hotline_Delay(0~10)":"Délai appel au décroché(0~10s)",
    "Hour ":"Heure",
    "Hour":"Heure",
    "Hour_12":"12 Heures",
    "Hour_24":"24 Heures",
    "Http":"HTTP",
    "Https":"HTTPS",
    "Hungary":"Hongrie",
    "ICMPv6 Status":"Etat ICMPv6",
    "IME":"IME",
    "INBAND":"INBAND",
    "IP Direct Auto Answer":"Auto décroché sur IP directe",
    "IP address is invalid":"L'adresse IP est invalide!",
    "IP_Address":"Adresse IP",
    "IPv4 & IPv6":"IPv4 & IPv6",
    "IPv4 Config":"Configuration IPv4",
    "IPv4":"IPv4",
    "IPv6 Config":"Configuration IPv6",
    "IPv6 Static DNS":"IPv6 Static DNS",
    "IPv6 prefix is invalid":"LIPv6 est invalide!",
    "IPv6 prefix(0~128)":"Préfixe IPv6 (0~128)",
    "IPv6":"IPv6",
    "Identity":"Identité",
    "Idle To Busy":"Occupé pour",
    "Import CFG Configuration File":" importation  Fichier de configuration CFG",
    "Import CSV":"Importer CSV",
    "Import Local Contact File":"Importer un fichier de répertoire local",
    "Import XML":"Importer XML",
    "Import":"importation",
    "Import_Factory_Config":"Importer configuration d'usine",
    "Import_Server_Certificate":"Chargement certificat serveur",
    "Import_Trusted_Certificate":"Importer certificat de confiance (.cer)",
    "IncomingCall":"IncomingCall",
    "Index":"Index",
    "India":"Inde ",
    "Inexistence":"Absence",
    "Info":"Info",
    "Input contains invalid character like ":"Entrée contient un caractère invalide comme ",
    "Input contains invalid character like '<>'":"L’Entrée de Données contient des caractères invalides comme '<>'",
    "Input contains invalid character like <>'\"\\":"Entrée contient des caractères invalides comme <>'\"\\",
    "Install certs failed!":"Install certs échoué! ",
    "Install server certs error!":"erreur Install certs serveur! ",
    "Inter Digit Time(1~14s)":"Tempo inter chiffres (1~14s)",
    "Intercom":"interphone",
    "Intercom:":"Intercom",
    "IntercomBarge":"Acceptation Intercom",
    "IntercomMute":"Intercom silencieuse",
    "IntercomTone":"Tonalité d'intercom",
    "Internal_Ringer_File":"Fichier sonnorie interne",
    "Internal_Ringer_Text":"Texte sonnerie interne",
    "Internet Port":"Port Internet",
    "Interval_min":"Intervalle(Minutes)",
    "Invaid Emergency should only contain digital number and ','":"Invaid Emergency should only contain digital number and ','",
    "Invaid File Name!":"Nom de fichier invalide!",
    "Invaid File Type!":"Type de fichier invalide!",
    "Invail value.":"Valeur invalide!",
    "Invaild  BroadsoftXSIHostAddr":"Adresse host XSI invalide!",
    "Invaild  Primary NTP Server":"Serveur NTP principal invalide!",
    "Invaild  Secondary NTP Server":"Serveur NTP secondaire invalide!",
    "Invalid Custom Option!":"Invalid Custom Option!",
    "Invalid DHCP option!":"option DHCP invalide!",
    "Invalid DTMF payload !":"Invalid DTMF payload!",
    "Invalid Day!":"Jour invalide!",
    "Invalid Max RTP Port !":"Port Max RTP invalide!",
    "Invalid Min RTP Port !":"Port Min RTP invalide!",
    "Invalid Number":"Numéro invalide",
    "Invalid SNMP Port !":"Port SNMP invalide!",
    "Invalid SNMP Trused address !":"adresse de confiance SNMP invalide!",
    "Invalid SipQos":"QoS SIP invalide!",
    "Invalid String":"Chaine de caractères invalide!",
    "Invalid URL!":"URL invalide!",
    "Invalid VID":"VID invalide!",
    "Invalid VoiceQos":"QoS voix invalide!",
    "Invalid characters. Only digits and commas are allowed!":"Caractères non valides. \n Seuls les chiffres et les virgules sont permis!",
    "Invalid connection request username!":"Demande connexion nom d'utilisateur invalide!",
    "Invalid daylight saving end day!":"date de fin invalide!",
    "Invalid daylight saving start day!":"date de début invalide!",
    "Invalid daylight saving start/end time !":"date invalide début/fin !",
    "Invalid factory file!":"fichier de config usine invalide!",
    "Invalid file name!":"Nom de fichier invalide !",
    "Invalid group name!":"nom de groupe invalide!",
    "Invalid password!":"Mot de passe invalide!",
    "Invalid prefix String":"Chaine de préfixe invalide!",
    "Invalid request password!":"Demande mot de passe invalide!",
    "Invalid ring file!":"fichier de sonnerie invalide!",
    "Invalid ringer text string!":"caractère texte de sonnerie invalide!",
    "Invalid server URL!":"URL serveur invalide!",
    "Invalid syslog server address !":"adresse du serveur SYSLOG invalide!",
    "Invalid username!":"Nom d'utilisateur invalide!",
    "Invalid value!":"Invalid value!",
    "Ip Changed":"IP Changée",
    "IsDeal180":"IsDeal180",
    "Issued_By":"Délivré par",
    "Issued_To":"Délivré à",
    "Italian":"Italien",
    "Italy":"Italie ",
    "JITTER_BUFFER":"JITTER BUFFER",
    "Jan":"Janv",
    "January":"Janvier",
    "Japan":"Japon",
    "Jitter":"Jitter",
    "JitterBufferMax":"JitterBufferMax",
    "Jul":"Juil",
    "July":"Juillet",
    "Jun":"Juin",
    "June":"Juin",
    "Keep Alive Interval":"Intervalle keep alive (secondes)",
    "Keep Alive Type":"Type keep alive",
    "Key":"Touche",
    "Keyboard_Lock":"Verrouillage clavier",
    "Keyboard_Lock_Enable":"Activer verrouillage clavier",
    "Keypad Lock":"Clavier verrouillé",
    "LAN_IP_Address":"Adresse IP LAN",
    "LDAP":"LDAP",
    "LDAPTLSMode":"LDAP TLS Mode",
    "LDAP_Display_Name":"Nom affiché LDAP",
    "LDAP_Lookup_For_Callout":"LDAP Lookup For Callout",
    "LDAP_Lookup_For_Incoming_Call":"Recherce LDAP sur appel entrant",
    "LDAP_Name_Attributes":"Attributs Nom LDAP",
    "LDAP_Name_Filter":"Nom filtre LDAP",
    "LDAP_Number_Attributes":"Attributs Numéro LDAP",
    "LDAP_Number_Filter":"Numéro filtre LDAP",
    "LDAP_Sorting_Results":"Tri des résultats LDAP",
    "LED Off in Idle":"LED OFF au repos",
    "Label Length":"Longueur de l'étiquette",
    "Label":"étiquette",
    "Language":"WEB Langue",
    "Last In Month":"Dernier du mois",
    "Left":"gauche",
    "Line 1":"Ligne 1",
    "Line 10":"Ligne 10",
    "Line 11":"Ligne 11",
    "Line 12":"Ligne 12",
    "Line 13":"Ligne 13",
    "Line 14":"Ligne 14",
    "Line 15":"Ligne 15",
    "Line 16":"Ligne 16",
    "Line 17":"Ligne 17",
    "Line 18":"Ligne 18",
    "Line 19":"Ligne 19",
    "Line 2":"Ligne 2",
    "Line 20":"Ligne 20",
    "Line 21":"Ligne 21",
    "Line 22":"Ligne 22",
    "Line 3":"Ligne 3",
    "Line 4":"Ligne 4",
    "Line 5":"Ligne 5",
    "Line 6":"Ligne 6",
    "Line 7":"Ligne 7",
    "Line 8":"Ligne 8",
    "Line 9":"Ligne 9",
    "Line Active":"Ligne Active",
    "Line Key":"Touches de ligne",
    "Line Key1-5":"Touche ligne 1-5",
    "Line Key1-7":"Touche ligne 1-7",
    "Line Key1-9":"Touche ligne 1-9",
    "Line Key10-18":"Touche ligne 10-18",
    "Line Key11-15":"Touche ligne 11-15",
    "Line Key15-21":"Touche ligne 15-21",
    "Line Key19-27":"Touche ligne 19-27",
    "Line Key6-10":"Touche ligne 6-10",
    "Line Key8-14":"Touche ligne 8-14",
    "Line Selection":"Selection de ligne",
    "Line":"Ligne",
    "Link_Status":"Etat",
    "Listening_Address":"Adresse d'écoute",
    "Lithuania":"Lituanie ",
    "Live Dialpad":"Saisie automatique",
    "Load Fail":"Chargement échoué",
    "Load Failed":"Échec de chargement",
    "Load Ringtone":"Chargement sonneries",
    "Load_server_cer_file":"Charger fichier cer serveur",
    "Load_trusted_cer_file":"Charger fichier certificats de confiance",
    "Loading, please waiting":"Chargement en cours, veuillez patientez!",
    "Loading, please waiting...":"Chargement en cours, veuillez patientez!",
    "Local Anonymous Rejection":"rejet anonyme local",
    "Local Anonymous":"Anonyme local",
    "Local Codec":"Codec local",
    "Local Configuration":"Configuration locale",
    "Local Contacts":"Contacts Locaux",
    "Local Directory":"Repertoire local",
    "Local Group":"Groupe local",
    "Local History":"Données d'appels locales",
    "Local IP":"IP locale",
    "Local Phonebook":"Repertoire local",
    "Local Port":"Port local ",
    "Local SIP Port should be a number !!":"Port SIP local doit être un chiffre!",
    "Local User":"utilisateur local",
    "Local codec":"Codec local",
    "Local user":"utilisateur local",
    "Local":"Local",
    "Local_Conf":"Local",
    "Local_Configuration":"Local_Configuration",
    "Local_Identity":"Identité locale",
    "Local_RTP_Port":"Port RTP local",
    "Local_SIP_Port":"Port SIP local",
    "Location":"Adresse",
    "Lock":"Verrouiller",
    "LogOff":"Log Off",
    "LogOn":"Log On",
    "Log_Out":"Délogguer",
    "Login address":"Adresse d'ouverture de session",
    "Login":"Login",
    "Logon Wizard":"Assistant de connexion",
    "Low":"Faible",
    "MAC-Oriented AES Key":"Clef AES par téléphone",
    "MAC_Address":"Adresse MAC",
    "MD5_Password":"Mot de passe MD5",
    "MM/DD/YY":"MM/JJ/AA",
    "MOS-CQ":"MOS-CQ",
    "MOS-LQ":"MOS-LQ",
    "MUTE":"Coupure Micro",
    "MWI_Subscription_Period  WSP_Scope seconds":"MWI période de souscription (secondes)",
    "Manager":"Gestionnaire",
    "Manual_Time":"Mise à l'heure manuelle",
    "Mar":"Mars",
    "March":"Mars",
    "Max Delay is less than Min Delay !":"Max delay is less than Min Delay!",
    "Max Length (1-15)":"longueur Max (1-15)",
    "Max RTP Port is less than Min RTP Port !":"Max RTP Port is less than Min RTP Port!",
    "Max.Hits(1~32000)":"Entrées maximales (1~32000)",
    "MaxRtpPort (1~65535)":"Port RTP max (1~65535)",
    "Max_Delay":"Délai max",
    "May":"Mai",
    "Meet-Me Conference":"Pont de conférence",
    "Memory Key":"Touches de fonction",
    "Menu":"Menu",
    "Menukey":"Touche Menu",
    "Message":"Message",
    "Mexico":"Mexique",
    "Min Length (1-15)":"Longueur Min (1-15)",
    "MinRtpPort (1~65535)":"Port RTP min (1~65535)",
    "Min_Delay":"Délai min",
    "Minute":"Minute",
    "MissCallLog":"Liste appels non-répondus",
    "Missed Call":"Appel manqué",
    "Missed_List":"Appels non-répondus",
    "Mobile Number":"numéro de portable",
    "Mode":"Mode",
    "Mode(IPv4/IPv6)":"Mode(IPv4/IPv6)",
    "Mode_802_1_x":"Mode 802.1x",
    "Mon":"Lun",
    "Monday":"Lundi",
    "Month":"Mois",
    "Move To":"passer à",
    "Multicast Listening":"écoute multicast",
    "MulticastCodec":"Codec Multicast",
    "MulticastIP":"MulticastIP",
    "MusicServerURI":"Serveur Musique d'attente",
    "Mute Power Light On":"Mute Power Light On",
    "Mute":"Coupure Micro",
    "My Status":"ma situation",
    "N/A":"N/A",
    "NAT":"NAT",
    "NAT_Traversal":"Traversée NAT",
    "NOTE":"Remarque",
    "NTP By DHCP Priority":"NTP By DHCP Priority",
    "Name cannot be empty !":"Le nom ne peut être vide!",
    "Name":"Nom",
    "Name+Number":"Nom + Numéro",
    "Netherlands":"Néerlandais",
    "Network CallLog":"Journal des appels réseaux",
    "Network Callog":"Journal des appels réseaux",
    "Network Common":"Réseau commun",
    "Network Directories":"Répertoires réseau",
    "Network Directory":"Répertoire réseau",
    "Network Favorite":"réseau favori",
    "Network Favourite":"Network Favourite",
    "Network Group":"Groupe réseau",
    "Network":"Réseau",
    "Network:":"Réseau",
    "NetworkPacketLossRate":"NetworkPacketLossRate",
    "Network_Conf":"Serveur",
    "New Call":"Nouvel appel",
    "New Password":"Nouveau mot de passe",
    "New SMS":"nouveau SMS",
    "New Zealand":"Nouvelle-Zélande",
    "New password is similar to username, are you sure to set it?":"New password is similar to username, are you sure to set it?",
    "New password is too simple, are you sure to set it?":"New password is too simple, are you sure to set it?",
    "NewCall":"Nouvel appel",
    "Next":"prochaine",
    "No Account":"Pas de compte",
    "No data to import":"No data to import!",
    "No expansion module connected! Please connect one or more units then refresh this page.":"Aucun module d'extension connecté! Connectez un ou plusieurs module et rafraîchissez cette page.",
    "No space left!":"Pas d'espace à gauche! ",
    "No_answer_forward_to":"Renvoi sur non-réponse vers",
    "Nominal":"Nominal",
    "None":"aucun",
    "Normal Delay is beyond scope !":"Normal delay is beyond scope!",
    "Norway":"Norvège",
    "Not Found : ":"Non trouvé:",
    "Notification Popups":"Popups de notification",
    "Notify":"Avertissez",
    "Nov":"Nov",
    "November":"Novembre",
    "Number Only!!":"Nombre Seulement !!",
    "Number of line key":"Nombre de touche de ligne ",
    "Number":"Numéro",
    "Number+Name":"Nombre+Nom ",
    "OK":"D'accord",
    "Oct":"Oct",
    "October":"Octobre",
    "Off Code could not be empty when On Code is set!":"Code off ne peut pas etre vide si code on activé!",
    "Off Code":"Off Code",
    "Off hook":"Décrocher",
    "Off":"de",
    "Off_Code":"Code Off",
    "Office Num":"bureau Num",
    "Office Number":"Num. Bureau",
    "Offset(minutes)":"Offset(minutes)",
    "Old Password":"Ancien mot de passe",
    "Old group name is empty!":"Ancien nom de groupe est vide!",
    "On Code":"Le code",
    "On hook":"Raccrocher",
    "On":"sur",
    "OnTalk":"En conversation",
    "On_Code":"Code On",
    "Only_Accept_Trusted_Certificates":"Seulement certificat de confiance accepté",
    "Open Always Forward":"Activer renvoi immédiat",
    "Open Busy Forward":"Activer renvoi occup",
    "Open DND":"Ouvrir ne pas déranger",
    "Open NoAnswer Forward":"Activer renvoi non rep",
    "Operating, Please  Wait ...":"Operating, Please  Wait...",
    "Option (1-255)":"Option (128-254)",
    "Option":"Option",
    "Optional":"en option",
    "Options":"options",
    "Other Num":"autres Num",
    "Other Number":"Autre Num.",
    "Out Dialog BLF(*)":"Out Dialog BLF",
    "OutboundPort should be a number !!":"Port Outbound doit être un chiffre!",
    "Outbound_Proxy_Server":"Serveur Proxy Outbound",
    "Outgoing call":"Appel sortant",
    "Outgoing_Identity":"Identité d'appel",
    "PAI":"PAI",
    "PAI-FROM":"PAI-DE",
    "PAI-RPID-FROM":"PAI-DE-RPID",
    "PC Port Link":"Lien port PC",
    "PC Port":"Port PC",
    "PCMA":"PCMA",
    "PCMU":"PCMU",
    "PC_Port":"Port LAN",
    "PC_Port_Active":"Port PC actif",
    "PC_Port_Config":"Config port PC",
    "PC_Port_Link":"PC Port Link",
    "PEAP-MSCHAPV2":"PEAP-MSCHAPv2",
    "PNP Active":"PNP Active",
    "PPPoE":"PPPoE",
    "PSWDialLength Invalid!":"PSWDialLength invalide!",
    "PTT":"Prefix",
    "PTime(ms)":"PTime(ms)",
    "Packet_Interval (1~3600s)":"Packet Interval (1~3600s)",
    "Packets lost":"paquets perdus",
    "Page":"Page:",
    "Paging Address":"paging Adresse ",
    "Paging List":"liste Rech.Person.",
    "Paging":"pagination",
    "Paging_Barge":"Paging Barge",
    "Paging_Priority_Active":"Paging Priority Active",
    "Park Retrieve Code":"code récupération parcage",
    "Park":"Parquage",
    "Parse Fail":"Parse Fail",
    "Password is similar to username, are you sure to set it?":"Mot de passe est similaire à nom d'utilisateur, êtes vous sûr de le changer? ",
    "Password is too simple, are you sure to set it?":"Mot de passe est trop simple,  êtes vous sûr de le changer? ",
    "Password":"Mot de passe",
    "Passwords don't match!":"les mots de passe sont différents",
    "Pcap Feature":"Pcap Feature",
    "Period for Interval Report":"Period for Interval Report",
    "Periodic Inform Interval (seconds)":"Periodic Inform Interval (seconds)",
    "Permission denied!":"Permission denied!",
    "Personal:":"Personnel",
    "Phone Call Info":"Phone Call Info",
    "Phone Lock Time Out(0~3600s)":"temporisation de verrouillage du poste (0~3600s)",
    "Phone Lock":"Verrouillage téléphone:",
    "Phone":"téléphone",
    "Phone-Unlock PIN(0~15 digital)":"PIN de déverrouillage du poste(0~15 Chiffres)",
    "PhoneSetting:":"Paramètres Téléphone",
    "Photo name already existed!":"Nom de photo déjà existant!",
    "Photo":"Photo",
    "Play Local DTMF Tone":"Jouer en local les tonalités DTMF",
    "PlayHoldTone":"Tonalité Attente",
    "PlayHoldToneDelay should be a number !!":"Durée Jouer tonalité d'attente doit être un chiffre!",
    "PlayHoldToneDelay":"Délai Tonalité Attente",
    "Please choose at least one record!":"SVP choisissez au moins un article!",
    "Please choose the DisplayName":"SVP  choisissez le nom d'affichage!",
    "Please click Confirm to load custom directories.":"Cliquez sur Confirmer pour charger les répertoires personnes, s'il vous plait.",
    "Please enable a codec at least.":"SVP activez au moins un codec!",
    "Please input complete information!":"Please input complete information!",
    "Please select a .bin format file at first!":"Sélectionner un format .bin s'il vous plaît!",
    "Please select a .cfg format file at first!":"S'il vous plaît sélectionner un fichier au format .cfg d'abord! ",
    "Please select a .png or .jpg or .bmp  format file at first!":"Sélectionner un fichier .png ou .jpg ou .bmp s'il vous plaît!",
    "Please select a .wav format file at first!":"Sélectionner un fichier au format .wav, s'il vous plaît! ",
    "Please select a correct file(.bin)":"SVP  selectionnez un fichier correct(.bin)!",
    "Please select a file":"SVP  selectionnez un fichier!",
    "Please select a group!":"SVP  selectionnez un groupe!",
    "Please select one cert at least.":"S'il vous plaît sélectionner un cert au moins. ",
    "Please select one record at least.":"Please select one item at least.",
    "Please select the contacts list file":"SVP  selectionnez le fichier de la liste des contacts!",
    "Please select the record which you want to edit":"SVP selectionnez l'élément que vous voulez éditer",
    "Please specify the Target number":"SVP spécifiez le numéro de destination!",
    "Please specify the blockout number!":"SVP spécifiez le numéro de blocage!",
    "Please upload VPN config file first!":"Please upload VPN config file first!",
    "Please wait and do not power off!":"Patientez s'il vous plaît et ne débranchez pas électriquement!",
    "Polish":"Polonais",
    "Port (0~65535)":"Port (1~65535)",
    "Port":"Port",
    "Port_Link":"Port Link",
    "Portugal":"Portugal",
    "Portuguese":"Portugais",
    "Post_Append":"Ajout_Poste",
    "Post_Mode":"Mode_Poste",
    "Post_Stor":"Stor_Poste",
    "Power LED":"Power LED",
    "Power LED:":"Power LED:",
    "Power On":"Mise sous tension",
    "PreTrans":"Transférer à",
    "Preference":"Préference",
    "Prefix and Replace should not be Empty !":"Le préfixe et le remplacer ne doivent pas être vides!",
    "Prefix":"Préfixe",
    "Prev":"Précédent",
    "Prewiew":"Visualisation",
    "PriHold":"Attente",
    "Primary DNS error, please check":"Erreur de DNS primaire, SVP vérifiez!",
    "Primary DNS":"DNS principale",
    "Primary Server":"Serveur NTP principal",
    "Priority":"Priorité",
    "Private Hold":"Mise en garde Personnelle",
    "Programable Key":"Touche programmable",
    "Protocol":"Protocol",
    "Proxy_Require":"Proxy requis",
    "PswDial":"PswDial",
    "PswLength":"PswLength",
    "PswPrefix":"PswPrefix",
    "Push XML failed!!":"Push XML failed!",
    "Push XML sucessed":"Push XML sucessed!",
    "Push XML":"Poussez XML",
    "PushXML Test":"Test PushXML",
    "PushXML_ServerIP":"PushXML Server IP",
    "RC4":"RC4",
    "RFC 2543 Hold":"RFC 2543 Hold",
    "RFC2833":"RFC2833",
    "RPID-FROM":"RPID-FROM",
    "RPID-PAI-FROM":"RPID-PAI-FROM",
    "RPort":"RPort",
    "RTP Status":"état RTP",
    "ReDialTone":"Code de rappel automatique",
    "ReDialtone number should be a number !!":"Tonalité rappel doit être un chiffre!",
    "ReLogOffTime(1~1000min)":"Durée déconnexion automatique(1~1000min)",
    "Reboot In Talking":"Reboot In Talking",
    "Reboot":"Redémarrage système maintenant",
    "Rebooting , please wait ...":"Rebooting, please wait...",
    "Received_List":"Appels reçus",
    "Recent Call In Dialing":"Derniers numéros composés",
    "Record":"Enregistrement",
    "RedirectActive":"Redirect Active",
    "Refresh":"Rafraichissement",
    "Reg_Surge_Prev (0~60s)":"Enregistrement aléatoire (0~60s)",
    "Reg_Surge_Prev":"Registration Surge Prevention",
    "Register Failed":"Inscrivez Échec",
    "Register Name":"Nom d'enregistrment",
    "Register Status":"Etat d'enregistrement",
    "Register":"Inscription",
    "RegisterFailed":"Register Failed",
    "Registered":"Enregistré",
    "Registering":"En cours d'enregistrement",
    "Reject":"Rejet",
    "RejectIncomingCall":"RejectIncomingCall",
    "Remote Codec":"Codec distant",
    "Remote Control":"Télécommande",
    "Remote IP":"IP distant",
    "Remote Phone Book":"Répertoire externe",
    "Remote Phonebook":"Répertoire à distance",
    "Remote Port":"Port distant",
    "Remote User":"utilisateur distant",
    "Remote codec":"Codec distant",
    "Remote control:":"Télécommande:",
    "Remote user":"utilisateur distant",
    "RemoteURL":"URL distant",
    "Repeatly":"Régulièrement",
    "Replace All":"Remplacer tout",
    "Replace Part":"remplacement de la partie",
    "Replace Rule Type":"Type de Règle de Remplacement",
    "Replace Rule":"Règle de remplacement",
    "Replace":"Remplace",
    "Report options on phone UI":"Report options on phone UI",
    "ReportIP":"Report IP",
    "Request failed!!":"Échec de la demande !!",
    "Reserve # in User Name":"Reserve # in User Name",
    "Reserved Character in User Name":"Caractère réservé dans le champ Nom d'utilisateur ",
    "Reset Local Config":"RAZ config Locale",
    "Reset Local Configuration":"Réinitialiser la configuration locale",
    "Reset to Default":"Reset to Default",
    "Reset to Factory Setting":"Reconfigurer en mode usine",
    "Reset to default":"Retour aux réglages par défaut",
    "Reset":"Reset to Factory Setting",
    "Resetting , please wait ...":"Réinitialisation, s'il vous plaît patienter ... ",
    "Resume":"Reprendre",
    "Retrieve Park":"Récupérer parquage",
    "Retrieve":"Récupérer",
    "Return_Code_DND":"Code retour sur Ne Pas Déranger",
    "Return_Code_Refuse":"Code retour sur refus",
    "Right":"droite",
    "Ring Power Light Flash":"Ring Power Light Flash",
    "Ring Tone":"Ring Tone",
    "Ring":"Sonnerie",
    "Ring1.wav":"Ring1.wav",
    "Ring2.wav":"Ring2.wav",
    "Ring3.wav":"Ring3.wav",
    "Ring4.wav":"Ring4.wav",
    "Ring5.wav":"Ring5.wav",
    "Ring6.wav":"Ring6.wav",
    "Ring7.wav":"Ring7.wav",
    "Ring8.wav":"Ring8.wav",
    "RingBack":"Retour d'appel",
    "Ring_Type":"Type sonnerie",
    "Ring_back":"Retour d'appel",
    "Ringer_Device_for_Headset":"Sonnerie pour casque",
    "RoundTripDelay":"RoundTripDelay",
    "Router":"routeur",
    "Rule":"Règle",
    "Running":"En service",
    "Russian":"russe",
    "Russian":"Russe(Russian)",
    "SIP Config":"Config SIP",
    "SIP INFO":"SIP INFO",
    "SIP Notify":"SIP NOTIFY",
    "SIP":"SIP",
    "SIPServerType":"SIP Server Type",
    "SIP_Qos (0~63)":"SIP QoS (0~63)",
    "SIP_Qos can not be empty.":"QoS SIP ne peut être vide.",
    "SIP_Reg_Retry_Timer SIP_RegRT_Scope seconds":"SIP Registration Retry Timer(0~1800s)",
    "SIP_Reg_Retry_Timer should be a number !!":"Délai de tentative d'enregistrement SIP doit être un chiffre!",
    "SIP_Send_Line":"Ligne sur SIP",
    "SIP_Send_MAC":"MAC sur SIP",
    "SIP_Session_Timer seconds T1":"SIP Session Timer T1 (0.5~10s)",
    "SIP_Session_Timer seconds T2":"Délai session SIP T2 (2~40s)",
    "SIP_Session_Timer seconds T4":"Délai session SIP T4 (2.5~60s)",
    "SIP_Session_Timer":"Délai session SIP",
    "SMS":"SMS",
    "SMS_message":"Message",
    "SMS_target_number":"Numéro",
    "SNMP":"SNMP",
    "SRTP Auth-tag":"SRTP Auth-tag",
    "SRemoteName":"SRemoteName ",
    "SRemoteNameFlashTime(seconds)":"Sremote Name Flash Time(Seconds)",
    "STUN Port":"Port STUN",
    "STUN":"STUN",
    "STUNPort should be a number !!":"Port STUN doit être un chiffre!",
    "STUN_Server":"Serveur STUN",
    "SWAP":"SWAP",
    "Sat":"Sam",
    "Saturday":"Samedi",
    "SaveCallHistory":"SaveCallHistory",
    "Search Source List In Dialing":"Search Source List In Dialing",
    "Second In Month":"Deuxième du mois",
    "Second":"Seconde",
    "Secondary DNS error, please check":"Erreur de DNS secondaire, SVP vérifiez!",
    "Secondary DNS":"DNS alternative",
    "Secondary Server":"Serveur NTP secondaire",
    "Security":"Sécurité",
    "Select and Upgrade Firmware":"Sélectionner et lancer la mise à jour firmware",
    "Selected Softkeys (ordered by position)**":"Touches programmables sélectionnés \n (triées par position)",
    "SemiAttendTrans":"En cours de transfert",
    "SemiAttendTransBack":"Transférer retour tonalité",
    "Semi_Attend_Trans_OnHook":"Transfert sur raccroché",
    "Send Anonymous Code":"Code appel anonyme",
    "Send Anonymous Rejection Code":"Code rejet appel anonyme",
    "Send Anonymous":"Appel anonyme",
    "Send Sound":"Envoyer sonore",
    "Send":"  Envoyer ",
    "SendPoundKey":"Envoi Touche Dièse",
    "Sep":"Sept",
    "September":"Septembre",
    "Server Certs":"Certificat de serveur",
    "Server Expires":"Server Expires",
    "Server Host":"serveur hôte",
    "Server Name":"Nom du serveur",
    "Server RetryCounts":"Server Retry Counts",
    "Server URL":"URL",
    "Server":"Serveur",
    "Server_Address":"Adresse Serveur",
    "SessionExpires seconds":"Session Expires(30~7200s)",
    "SessionRefresher":"Recyclage",
    "Setting":"réglage",
    "Settings":"paramètres",
    "SetupCompleted":"Setup Completed",
    "Shared_Line":"Ligne partagée",
    "Show Title":"Afficher le titre",
    "Signal Encode Key":"Signal Encode Key",
    "Silence":"Silence",
    "Silent.wav":"Silent.wav",
    "Sip Server 1":"SIP Server 1",
    "Sip Server 2":"SIP Server 2",
    "SoftKey1":"SoftKey 1",
    "SoftKey2":"SoftKey 2",
    "SoftKey3":"SoftKey 3",
    "SoftKey4":"SoftKey 4",
    "Softkey Layout":"Softkey Layout",
    "Software_Version":"Software Version",
    "Spain":"Espagne",
    "Spanish":"Espagnol",
    "Speed Dial":"Numérotation abrégée",
    "Splash.wav":"Splash.wav",
    "Split":"Diviser",
    "Start Date":"date de début",
    "Start Hour of Day":"Start Hour of Day",
    "Start IP Address":"Adresse IP de début",
    "Start Time":"Heure de début",
    "Start":"Démarrer",
    "Static DNS":"DNS statique",
    "Static IP Address":"Adresse IP manuelle",
    "Static IP":"IP Statique",
    "Status":"Etat",
    "Stop Time":"Heure de fin",
    "Stop":"Arrêter",
    "Stopped":"arrêté",
    "Stutter":"Répétition",
    "Sub_MWI":"Souscription MWI",
    "Sub_Period seconds":"Période de souscription (secondes)",
    "Subnet mask address is invalid":"l'adresse de sous masque est invalide",
    "Subnet_Mask":"Masque sous-réseau",
    "SubscribeMWIToVM":"SubscribeMWIToVM",
    "SubscribeRegister":"Souscription d'enregistrement",
    "Subscription Period should be a number !!":"Période souscription doit être un chiffre!",
    "Success:Delete user factory config OK!":"Succès: Supprimer la config usine OK! ",
    "Success:Import your factory config OK!":"Succès: Importez votre config usine OK! ",
    "Sun":"Dim",
    "Sunday":"Dimanche",
    "Suppress DTMF Display Delay":"Délai de suppression d'affichage DTMF",
    "Suppress DTMF Display":"Supprimer l'affichage DTMF",
    "Sweden":"Suède",
    "Switch Account Down":"Switch Account Down",
    "Switch Account Up":"Switch Account UP",
    "Switch Account":"Commuter le compte",
    "Switch":"Commuter",
    "Switzerland":"Suisse",
    "SymmOneWayDelay":"SymmOneWayDelay",
    "System logo":"Logo système",
    "System ringtone can not be removed!!":"Les sonneries du système ne peuvent être supprimées!",
    "System wallpaper can not be removed!!":"Les images de fond du système ne peuvent être supprimées!",
    "SystemlogLevel":"System Log Level",
    "TCP":"TCP",
    "TLS":"TLS",
    "TLS_SIPs_Port":"TLS SIP Port",
    "TR069":"TR069",
    "TR069:":"TR069",
    "TRAN":"TRAN",
    "Talk":"Talk",
    "Talk/Dial Power Light On":"Talk/Dial Power Light On",
    "Talking, Please wait...":"Talking, Please wait...",
    "Talking, please save config later.":"Talking, please save config later!",
    "Target":"Destination",
    "Telephone-Event":"Téléphone-événement",
    "Terminated":"Appel terminé",
    "Text_Logo":"Text Logo",
    "Tftp_Server":"Ftp/Tftp Server",
    "The Block Out Number should not contain other characters except \"digital number, *, [, ']', '-', ',', '.', 'x',')','('\"":"Le numéro de blocage  ne doit pas contenir d'autres caractères sauf \"nombre numérique *, [, ']', '-'. ',', ',,' X ',') ',' ('\"",
    "The Max Length must not be less than Min Length":"The Max Length must not be less than Min Length",
    "The SMS is empty !":"Le SMS est vide!",
    "The Secondary DNS is same as Primary DNS, please enter again":"Le DNS secondaire est le même que le DNS primaire, veuillez entrer à nouveau!",
    "The TimeOffset value should be from -300 to +300!":"La valeur de décalage de temps doit être de -300 à 300!",
    "The build-in photo cannot be removed":"La photo de base ne peut être supprimée!",
    "The cert file has existed!":"Le fichier cert a existé! ",
    "The cert file has prefabricated!":"Le fichier cert a préfabriqué! ",
    "The configuration information is not complete!":"Les informations de configurationne sont pas complètes",
    "The count of DHCP Option's values can't more than 5!":"Le nombre de valeur de l'option DHCP ne peut pas plus de 5!",
    "The file already exited!!":"Le fichier existe déjà!",
    "The file already exits!":"Le fichier existe déjà !",
    "The file format must be .csv!":"Le format de fichier doit être .csv!",
    "The file format must be .dob!":"Le format de fichier doit être .dob!",
    "The file format must be .pem , .crt , .cer or .der !":"Le format de fichier doit être .pem, .crt, .cer ou .der !",
    "The file format must be .pem , .crt , .cer or .der!":"Le format du fichier doit être .pem, .crt, .cer ou .der!",
    "The file format must be .pem or .cer!":"Le format de fichier doit être .pem ou .cer!",
    "The file format must be .pem!":"Le format de fichier doit être .pem!",
    "The file format must be .rom!":"Le format de fichier doit être .rom!",
    "The file format must be .tar!":"Le format du fichier doit être .tar",
    "The file format must be .xml!":"Le format de fichier doit être .xml!",
    "The file is too large!":"Le fichier est trop gros! ",
    "The file is too large,please less than 5M!":"Le fichier est trop gros, s'il vous plaît moins de 5M! ",
    "The file name is too long!":"Le nom de fichier est trop long!",
    "The http port of webserver is invalid number!":"Le port HTTP du serveur Web est un numéro invalide!",
    "The https port of webserver is invalid number!":"Le port HTTPS du serveur Web est un numéro invalide!",
    "The maximum length of the SMS is 200 characters!":"La longueur maximale du SMS est de 200 caractères!",
    "The operation is done!":"The operation is done!",
    "The original contact will be covered, continue?":"Le contact initial sera remplacé, Continuer?",
    "The password have invalid value!":"Le mot de passe a une valeur invalide!",
    "The size is too big!":"La taille est trop grande!",
    "The username can not be empty.":"The username can not be empty.",
    "The username or password is error!":"Le nom d'utilisateur ou le mot de passe est erroné!",
    "There is no such groups":"Il n'y a pas de tels groupes!",
    "Third In Month":"Troisième du mois",
    "This firmware don't support tr069!":"This firmware don't support TR069!",
    "Thu":"Jeu",
    "ThursDay":"Jeudi",
    "Time Zone":"Fuseau horaire",
    "Time":"Heure",
    "Time&Date":"Heure et date",
    "Time&Date:":"Heure et date:",
    "Time_Format":"Format heure",
    "Time_Out_Dial_Now_Rule":"Time Out for Dial-now Rule",
    "Tones":"Tonalité",
    "Tran Send DTMF":"Tran Send DTMF",
    "Transfer on Conference Hang up":"Transfer on Conference Hang up",
    "Transfer":"transfert",
    "Transfer:":"Transfer",
    "TransferCall":"Transfer Call",
    "TransferFailed":"TransferFailed",
    "TransferFinished":"TransferFinished",
    "TransferModeViaDsskey":"mode de transfert via DssKey",
    "Transport":"Transport",
    "Trusted Certs":"Certificat de confiance",
    "Tue":"Mar",
    "Tuesday":"Mardi",
    "Turkish":"Turc",
    "TurstedAddr":"Adresse de confiance",
    "Two or more records have been chosen!":"Deux ou plusieurs éléments ont été choisis!",
    "Type can not be \"BLF List\" when autoBlflist is on!":"Type ne peut être Liste BLF quand liste BLF automatique est on!",
    "Type can not be \"UC Favourite\" when AutoFavorite is on!":"Type can not be \"UC Favourite\" when AutoFavorite is on!",
    "Type":"Type:",
    "UC Active":"UC Active",
    "UC Favourite":"UC Favourite",
    "UC Password":"UC Password",
    "UC Username":"UC Username",
    "UCAP":"UCAP",
    "UCServer":"UCServer",
    "UDP":"UDP",
    "UDP_Keep_alive_Interval should be a number !!":"Intervalle keep alive UDP doit être un chiffre!",
    "URL record":"Enregistrement URL",
    "URL":"URL",
    "USRPRIORITY":"Priorité Utilisateur",
    "Uac":"UAC",
    "Uas":"UAS",
    "UnConnected":"UnConnected",
    "UnHold":"UnHold",
    "UnMute":"UnMute",
    "United States":"États-Unis ",
    "Unknown":"inconnu",
    "UnregisterOnReboot(*)":"non enregistré au démarrage",
    "Unregistered":"non enregistré",
    "Unselected Softkeys":"touches programmables non sélectionnés",
    "UnusedBackLight":"Backlight Idle Intensity",
    "Up":"en haut",
    "Update Interval  seconds":"Synchronism (1~86400s)",
    "Upgrade":"Charger",
    "Upload Logo":"Chargement du  Logo",
    "Upload Photo":"Télécharger une photo",
    "Upload VPN Config":"Upload VPN Config",
    "Upload Wallpaper":"Charger fond d'écran",
    "Upload Wallpaper":"Charger fond d'écran(800*480)",
    "Upload cert file error!":"Erreur de chargement de fichier cert! ",
    "Upload failed!":"Chargement échoué!",
    "Upload success!":"Chargement réussi!",
    "Upload":"Télécharger",
    "Upload_Period":"Période_Téléchargement",
    "Use Logo":"Utiliser logo",
    "Use Outbound Proxy In Dialog":"Utiliser le Proxy de Sortie dans le Dialogue",
    "Use_Headset":"Utiliser Casque",
    "Use_Headset_Group":"Use Headset Group",
    "Use_Speaker":"Utiliser HP",
    "User ID":"N° utilsateur",
    "User Name":"Nom d'utilisateur",
    "User Type":"Type d'utilisateur",
    "User":"Utilisateur",
    "UserName":"Nom d'utilisateur",
    "Username":"Nom d'utilisateur",
    "VAD":"VAD",
    "VID (1-4094)":"VID (1-4094)",
    "VLAN":"VLAN",
    "VQ RTCP-XR Collector address":"VQ RTCP-XR adresse Collector ",
    "VQ RTCP-XR Collector name":"VQ RTCP-XR nom Collector ",
    "VQ RTCP-XR Collector port":"Port VQ RTCP-XR Collector ",
    "VQ RTCP-XR Interval Report":"VQ RTCP-XR rapport Intervalle ",
    "VQ RTCP-XR Session Report":"VQ RTCP-XR Rapport de la Session",
    "Value shouldn't be empty !":"La valeur ne doit pas être vide!",
    "Value":"valeur",
    "Version":"Version",
    "Version2":"Version2",
    "Version3":"Version3",
    "Visual Alert for BLF Pickup":"Alerte visuelle pour interception BLF",
    "Visual Alert for Parked Call":"Alerte visuelle pour appel parqué",
    "Voice Mail Display":" affichage Messagerie vocale",
    "Voice Mail Tone":"Tonalité de messagerie vocale",
    "Voice Mail":"Messagerie Vocale",
    "Voice Monitoring":"Voice Monitoring",
    "Voice":"Voix",
    "Voice/Text Mail Power Light Flash":"Voice/Text Mail Power Light Flash",
    "VoiceEncryptType":"Voice Encrypt Type",
    "Voice_Mail":"Messagerie",
    "Voice_QoS (0~63)":"Qos voix (0~63)",
    "Voice_QoS can not be empty.":"QoS voix ne peut être vide.",
    "Voice_QoS":"QoS Voix",
    "WAN IP address is invalid":"L'adresse IP WAN n'est pas valide!",
    "WAN IPv6 address is invalid":"L'adresse IPV6 WAN n'est pas valide!",
    "WAN Port Link":"Lien port WAN",
    "WAN_IP_Address":"Adresse IP WAN",
    "WAN_Port":"Port Internet (WAN)",
    "WAN_Port_Link":"WAN Port Link",
    "WAN_Port_Type":"Type port WAN",
    "WWW DD MMM":"Sem Jour Mois",
    "WWW MMM DD":"Sem Mois Jour",
    "WaitTime":"Wait Time(s)",
    "Wallpaper":"Fond d'écran",
    "Warming threshold for Delay":"Warming threshold for Delay",
    "Warming threshold for Moslq":"Warming threshold for Moslq",
    "Warning,AccountNATUDPUpdateTime could not be empty!":"Attention, délai mise à jour compte NAT UDP ne peut être vide!",
    "Warning,the character '&' could not be contain!":"Attention, le caractère «&» ne peut pas être inclus!",
    "Warning: Group already exist!":"Attention: Le groupe existe déjà!",
    "Warning: Some settings you changed take effect when you restart your machine! do you want to reboot now?":"Attention: Certains réglages que vous avez modifiés prennent effet lorsque vous redémarrez votre machine! \nVoulez-vous redémarrer maintenant?",
    "Warning: The Phone must be reboot to make BroadsoftActive take effect,do you want to reboot now?":"Attention: le téléphone doit redémarrer pour avoir les paramètres Broadsoft actif. Souhaitez-vous le redémarrer immédiatement?",
    "Warning: The Phone must be reboot to make UC Active take effect,do you want to reboot now?":"Attention: Le téléphone doit être  redémarré pour que l'activation de l'UC prenne effet, voulez-vous redémarrer maintenant? ",
    "Warning:Same port!":"Attention: même port!",
    "WatchDog":"Chien de garde",
    "WebServer":"Accès HTML",
    "Wed":"Mer",
    "Wednesday":"Mercredi",
    "Weekly":"Hebdomadairement",
    "XML Browser":"Navigateur XML",
    "XML Group":"Groupe XML",
    "XML Phonebook":"répertoire XML",
    "XSI Port should be between 1 and 65535!!":"XSI Port should be between 1 and 65535!",
    "XSI":"XSI",
    "XSI:":"XSI",
    "XSIServerType":"XSI Server Type",
    "YY/MM/DD":"AA / MM / JJ ",
    "YYYY-MM-DD":"AAAA-MM-JJ",
    "Year":"Année",
    "You can choose 5 customers at most!!!":"Vous pouvez chosir 5 clients maximum!",
    "You can click here to get more guides.":"You can click here to get more guides.",
    "You have changed the password!":"Vous avez changé le mot de passe! ",
    "You have changed the password":"Vous avez changé le mot de passe",
    "You should input at least one sip server address!!":"Vous devez renseigner au moins une adresse de serveur SIP!",
    "ZeroActive":"Zero Active",
    "account":"Compte",
    "account-adv-note":"<b>Advanced</b><br>Les paramètres avancés pour l'administrateur ",
    "account-basic-note":"<b>Basic</b><br>Les paramètres basiques pour l'administrateur<br><br><b>Proxy Require</b><br>Un paramètre spécial juste pour les serveurs Nortel. Si vous utiliser un serveur Nortel, la velur doit être: com.nortelnetworks.firewall<br>",
    "account-codec-note":"<b>Codecs</b><br>Choississez les codecs que vous souhaitez utilisés. ",
    "account-register-note":"<b>Display Name</b><br>SIP service subscriber's name which will be used for Caller ID display.<br><br><b>Register Name</b><br>SIP service subscriber's ID used for authentication.<br><br><b>User Name</b><br>User account, provided by VoIP service provider.<br><br><b>NAT Traversal</b><br>Defines the STUN server will be active or not.<br><br>",
    "action_URI_allow_IP":"Action URI Server IP",
    "admin":"admin",
    "auth error":"erreur auth.",
    "auto negotiate":"auto négocier",
    "auto_negotiate":"Auto Negotiate",
    "call failed":"appel échoué",
    "call success":"succès appel",
    "contacts-LDAP-note":"<b>LDAP</b><br>Les paramètres LDAP pour l'administrateur.<br>",
    "contacts-broadsoft-note":"<b>Network Directory</b><br>Les paramètres d'annuaire centralisé pour l'administrateur.<br>",
    "contacts-callinfo-note":"<b>Call Log</b><br>Les données d'appels pour l'administrateur.<br>",
    "contacts-favorite-note":"<b>Directory</b><br>Les paramètres d'annuaire pour l'administrateur.<br>",
    "contacts-multicastIP-note":"<b>Multicast IP</b><br>Les paramètres multicast pour l'administrateur.<br>",
    "contacts-preview-note":"contacts-preview-note",
    "contacts-remote-note":"<B>Remote Phone Book</b><br>Cette fonction vous permet de télécharger les contacts depuis le serveur. Renseignez l'URL du répertoire et renommer le répertoire.<br>",
    "contactsbasic-note":"<B>Ajouter contact/liste noire</B><br>Saississez les informations du contact. L'utilisateur ne peut laisser le nom du contact vide.<br><br><br><b>Effacer contact/liste noire</b><br>Sélectionner le contact que vous souhaitez supprimer dans la grille, et puis cliquer sur Supprimer pour confirmer.<br><br><br><b>Déplacer vers contact/liste noire</b><br>Sélectionner les contacts que vous souhaitez déplacer dans la grille, et cliquer sur Déplacer vers contact/liste noire pour les déplacer.<br><br><br><b>Import</b><br>Parcourir le fichier au format XML.<br><br><br><b>Export</b><br>Cliquez sur Exporter et créer un fichier avec le nom désiré pour exporter.<br>",
    "data":"Date",
    "default":"default",
    "default_photo":"Photo par défaut",
    "dhcp_hostname":"Hostname DHCP",
    "display_name":"Nom",
    "download customs, please try latter!":"Download customs, please try latter!",
    "dsskey-ext-note":"<B>Key Type</B><br/>Les types de touches de fonction disponibles Numérotation abrégé, touche évènement, intercom.<br/><br/><B>Key Event</B><br/>Les touches évènement sont des raccourcis prédéfinis pour le téléphone et des fonctions d'appel<br/><br/><B>Intercom</B><br/>Active le mode 'Intercom' qui peut ête utile dans un environnement bureautique pour joindre rapidement l'opératrice ou le secrétariat.<br/><br/>",
    "dsskey-linekey-note":"<B>Key Type</B><br/>Les types de touches de fonction disponibles Numérotation abrégé, touche évènement, intercom.<br/><br/><B>Key Event</B><br/>Les touches évènement sont des raccourcis prédéfinis pour le téléphone et des fonctions d'appel<br/><br/><B>Intercom</B><br/>Active le mode 'Intercom' qui peut ête utile dans un environnement bureautique pour joindre rapidement l'opératrice ou le secrétariat.<br/><br/>",
    "dsskey-memorykey-note":"<B>Key Type</B><br/>Les types de touches de fonction disponibles Numérotation abrégé, touche évènement, intercom.<br/><br/><B>Key Event</B><br/>Les touches évènement sont des raccourcis prédéfinis pour le téléphone et des fonctions d'appel<br/><br/><B>Intercom</B><br/>Active le mode 'Intercom' qui peut ête utile dans un environnement bureautique pour joindre rapidement l'opératrice ou le secrétariat.<br/><br/>",
    "dsskey-programkey-note":"<B>Key Type</B><br/>Les types de touches de fonction disponibles Numérotation abrégé, touche évènement, intercom.<br/><br/><B>Key Event</B><br/>Les touches évènement sont des raccourcis prédéfinis pour le téléphone et des fonctions d'appel<br/><br/><B>Intercom</B><br/>Active le mode 'Intercom' qui peut ête utile dans un environnement bureautique pour joindre rapidement l'opératrice ou le secrétariat.<br/><br/>",
    "elect_Country":"sélectionnez le pays",
    "encryption(SRTP)":"Cryptage RTP(SRTP)",
    "favorite":"Directory",
    "features-acd-note":"<b>ACD</b><br>Les paramètres ACD pour l'administrateur.<br>",
    "features-actionurl-note":"<b>Action URL</b><br>Les paramètres d'action URL pour l'administrateur.<br>",
    "features-audio-note":"<b>Audio</b><br>Les paramètres audio pour l'administrateur.<br>",
    "features-bluetooth-note":"<b> fonctions-bluetooth</b><br><br>",
    "features-callpickup-note":"<b>Call Pickup</b><br>Les paramètres d'interception d'appels pour l'administrateur.<br>",
    "features-forward-note":"<B>Forward</B><br>Cette fonction vous autorise à dévier un appel entrant vers un autre numéro de téléphone.<br><br><B>Target</B><br>Le numéro vers lequel les appels entrants vont être déviés.<br><br><b>On Code</b><br>Le code qui sera envoyé au PBX lorsqu'il sera allumé.<br><br><B>Off Code</B><br>Le code qui sera envoyé au PBX lorsqu'il sera éteint.",
    "features-general-note":"Fonctions générales",
    "features-intercom-note":"<b>Intercom</b><br>Les paramètres intercom pour l'administrateur.<br>",
    "features-notification-popups-note":"<b>Notification-Popups</b><br>The notification-popups parameters for administrator.<br>",
    "features-phonelock-note":"<b>Keyboard Lock</b><br>Les paramètres de verrouillage du clavier pour l'administrateur.<br>",
    "features-power-led-note":"<b>Power-LED</b><br>The power-led parameters for administrator.<br>",
    "features-remotecontrl-note":"<b>Remote Control</b><br>Les paramètres d'accès distant pour l'administrateur.<br>",
    "features-sms-note":"<b>SMS</b><br>Entrer le numéro de téléphone vers lequel le message sera envoyé.<br>",
    "features-transfer-note":"<b>Transfer</b><br>Les paramètres de transfert pour l'administrateur.<br>",
    "float":"Flotte",
    "forward should disable when Lock&Answer":"Le renvoi doit être désactivé en cas de poste vérouillé en auto-décroché",
    "full duplex,100Mbpss":"Full Duplex,100Mbpss",
    "full duplex,10Mbps":"Full Duplex,10Mbps",
    "full_duplex_1000Mbps":"Full duplex 1000Mbps",
    "full_duplex_100Mbps":"Full duplex,100Mbps",
    "full_duplex_10Mbps":"Full duplex,10Mbps",
    "group_id_name":"Nom groupe",
    "half duplex,100Mbps":"Half Duplex,100Mbps",
    "half duplex,10Mbps":"Half Duplex,10Mbps",
    "half_duplex_100Mbps":"Half duplex,100Mbps",
    "half_duplex_10Mbps":"Half duplex,10Mbps",
    "hang up failed":"Raccorché échoué",
    "hangup failed":"raccrochage échoué",
    "hangup success":"succès raccrochage",
    "hidden-note":"caché note",
    "iLBC":"iLBC",
    "iLBC_15_2 and iLBC_13_3  can not be applied simultaneously":"iLBC 15.2 et 13.3 iLBC ne peuvent pas être appliquées simultanément!",
    "icon_blacklist_b.png":"icon_blacklist_b.png",
    "icon_family_b.png":"icon_family_b.png",
    "icon_friend_b.png":"icon_friend_b.png",
    "ignore":"Ignore",
    "index_id":"Index",
    "info":"infos",
    "innerHtml":"InnerHtml",
    "jumpto":"Aller à",
    "ldap":"LDAP",
    "ldap+StartTLS":"LDAP TLS Start",
    "ldaps":"LDAPs",
    "line":"Ligne",
    "lock":"Verrouiller",
    "memory":"Mémoire",
    "mobile_number":"numéro_mobile",
    "network-adv-note":"<b>VLAN</b><br>Un VLAN est un réseau local logique qui se déplois sur un réseau local pour un groupe d'équipements réseau, donnant une configuration spécifique à ces équipements.<br><br><b>QoS</b><br>Quand la capacité réseau est insuffisante, QoS permet de prioriser ces équipements en configurant ce paramètre.<br><br><b>Local RTP Port </b><br>Définit le port pour la transmission de la voix.",
    "network-note":"<b>DHCP</b><br>The network configurations will be acquired from DHCP server.<br><br><b>Static IP Address</b><br>Specify the IP address, Subnet Mask, Default Gateway, Primary DNS, Secondary DNS fields manually.<br><br><b>PPPoE</b><br>Contact your ISP if it should be used.",
    "network-pcport-note":"<b>PC Port</b><br>Les paramètres port PC pour l'administrateur<br><br>",
    "num":"Nombre",
    "office_number":"Num. Bureau",
    "other_number":"Autre Num.",
    "pcport_active":"PC Port Active",
    "photo_data":"Données photo",
    "precondition":"Activer Precondition",
    "proxy require can not contain ! and &":"Proxy Require can not contain ! and &",
    "retransmition":"100 transmission fiables",
    "ring":"Sonnerie",
    "seconds":"(secondes)",
    "security-note":"<b>User Type:</b><br>Sélectionner le type de connexion. Si vous vous loguez en tant qu'utilisateur, vous ne pourrez changer que votre propre mot de passe. Si vous vous loguez en tant qu'administrateur, vous pourrez modifier les mots de passe utilisateur et administrateur.",
    "server-cert-note":"<b>Server Certificates</b><br>Liste des certificats serveur.<br>",
    "settings-autop-note":"<b>Auto Provision</b><br>Les paramètres d'autoprovisioning pour l'administrateur.<br>",
    "settings-calldisplay-note":"<b>Calldisplay</b><br>The calldisplay parameters for administrator.<br>",
    "settings-config-note":"<b>Configuration</b><br>The configuration parameters for administrator.<br>",
    "settings-datetime-note":"<b>Time Zone</b><br>Choississez le fuseau horaire où vous vous situez.<br><br><b>NTP Server</b><br>Le serveur qui sera utilisé pour synchroniser l'heure du téléphone.<br><br>",
    "settings-dialplan-note":"<b>Chiffre 0-9 *</b><br>Identifie un digit spéficique (ne pas utiliser # si défini en touche de numérotation).<br><br><b>[chiffre-chiffre]</b><br>Identifie tout chiffre composé inclus dans la plage.<br><br><b>[chiffre-chiffre,chiffre]</b><br>Spécifie des plages séparées par une virgule.<br><br><b>x</b><br>Correspond à un seul chiffre/caractère qui est composé.<br><br><b>.</b><br>Correspond à  un nombre arbitraire de chiffres.",
    "settings-preference-note":"<b>Preference Settings</b><br>Les paramètres de préférence pour l'administrateur.<br>",
    "settings-ring-note":"<b>Ring</b><br>Les paramètres sonneries pour l'administrateur.<br>",
    "settings-sip-note":"<b>SIP</b><br>The sip parameters for administrator.<br>",
    "settings-softkey-note":"<b>Softkey Layout</b><br>Les paramètres des touches programmables pour l'administrateur.<br>",
    "settings-tones-note":"<b>Tones</b><br>Les paramètres tonalité pour l'administrateur.<br>",
    "settings-tr069-note":"<b>TR069</b><br>Les paramètres TR069 pour l'administrateur.<br>",
    "settings-upgrade-note":"<b>Reset to Factory Setting</b><br>Charger tous les paramètres par défaut du téléphone. <br><br><b>Select and Upgrade Firmware</b><br>Sélectionner et charger le fichier depuis le disque local ou réseau.",
    "settings-voice-note":"<b>VAD</b><br>Détection d'activité voix.<br><br><b>CNG</b><br>Génération d'un bruit de confort.<br><br><b>JITTER BUFFER:</b><br>Il s'agit d'une zone de données où les paquets voix sont collectés, stockés et envoyés au processeur gérant la voix uniformément.<br>",
    "settings-voicemonitoring-note":"settings-voicemonitoring-note",
    "sip server port should be a number !!":"Port serveur SIP doit être un chiffre!",
    "span to pc port":"Span to PC port",
    "span to pc":"Span to PC port",
    "status-note":"<b>Version</b><br>Ceci montre la version du firmware.<br><br><b>Network</b><br>Ceci montre les informations du port WAN.<br>",
    "text":"texte",
    "title_802_1_x":"802.1x",
    "title_LLDP":"LLDP",
    "trusted-cert-note":"<b>Trusted Certificates</b><br>Liste des certificats de confiance.<br>",
    "upgrade:fail":"mise à niveau: échec ",
    "user":"Utilisateur",
    "var":"var",
    "vpn":"VPN",
    "zero sp touch":"Zero Touch",
    "Are you sure to reset the local configuration?":"Are you sure to reset the local configuration",
    "Accept SIP Trust Server Only":"Accept SIP Trust Server Only",
    "Auto Linekeys":"Auto Linekeys",
    "Warning threshold for Moslq":"Warning threshold for Moslq",
    "Warning threshold for Delay":"Warning threshold for Delay",
    "Type can not be \"Line\" when AutoLinekeys is on!":"Type can not be \"Line\" when AutoLinekeys is on!",
    "Error: The max replace rule count is ":"Error: The max replace rule count is",
    "Day":"Day",
    "Outbound Proxy1":"Outbound Proxy1",
    "Outbound Proxy2":"Outbound Proxy2",
    "Proxy Fallback Interval":"Proxy Fallback Interval",
    "Proxy Fallback Interval is invalid!":"Proxy Fallback Interval is invalid!",
    "Bridge ID":"Bridge ID",
    "Reset local configurations?":"Reset local configurations?",
    "Advice of Charge":"Advice of Charge",
    "Cancel Call Out":"Cancel Call Out",
    "Remote Busy":"Remote Busy",
    "Call Remote Canceled":"Call Remote Canceled",
    "Advice of Charge":"Advice of Charge",
    "AOC Display Time":"AOC Display Time",
    "Shared Call Appearance":"Shared Call Appearance",
    "Enable auto answer tone":"Enable auto answer tone",
    "Delay must more than 20 !":"Delay must more than 20 !",
    "Open Call Waiting":"Open Call Waiting",
    "Close Call Waiting":"Close Call Waiting",
