" Call Number Filter":"呼叫号码过滤",
	" Distinctive Ring Tones":"区别振铃",
	" Do you want to reboot ?":"是否重启话机？",
	"(800*480)":"(800*480)",
	"10min":"10分钟",
	"1min":"1分钟",
	"2min":"2分钟",
	"30min":"30分钟",
	"404 (Not found)":"404 (未找到)",
	"480 (Temporarily not available)":"480 (暂时不可用)",
	"486 (Busy here)":"486 (正在忙)",
	"5min":"5分钟",
	"603 (Decline)":"603 (拒接)",
	"ACD Auto Available Timer(0~120s)":"ACD自动激活定时器（0~120s）",
	"ACD Auto Available":"ACD自动激活",
	"ACD Trace":"ACD追踪",
	"ACD":"ACD",
	"ACD:":"ACD",
	"ACD_SubscripPeriod(120~3600s)":"ACD订阅周期（120~3600秒）",
	"ACS Password":"ACS密码",
	"ACS URL":"ACS服务器地址",
	"ACS Username":"ACS用户名",
	"AES-32":"AES-32",
	"AES-80":"AES-80",
	"AES-80&&AES-32":"AES-80&&AES-32",
	"AUTO+SIP INFO":"AUTO or SIP INFO",
	"Account":"账号",
	"Account1":"账号 1",
	"Account10":"账号 10",
	"Account11":"账号 11",
	"Account12":"账号 12",
	"Account13":"账号 13",
	"Account14":"账号 14",
	"Account15":"账号 15",
	"Account16":"账号 16",
	"Account2":"账号 2",
	"Account3":"账号 3",
	"Account4":"账号 4",
	"Account5":"账号 5",
	"Account6":"账号 6",
	"Account7":"账号 7",
	"Account8":"账号 8",
	"Account9":"账号 9",
	"AccountStatus":"账号状态",
	"AccountStatusId":"账号状态",
	"Action URL":"Action URL",
	"Active Backlight Level":"背光灯激活时亮度",
	"Active":"激活",
	"Adaptive":"自适应",
	"Add":"添加",
	"Advanced":"高级",
	"After_ring_times scope2":"响铃时间（秒）",
	"All Cert":"全部证书",
	"All Contacts":"本地联系人",
	"All Keys":"所有键",
	"All_Configuration":"所有配置",
	"Allow IP Call":"允许IP呼叫",
	"Allow SIP Authentication for XSI":"允许SIP XSI认证",
	"Allow Trans Exist Call":"允许转移已有呼叫",
	"AllowIntercom":"启用对讲机",
	"AllowMute":"允许静音",
	"AlwaysOff":"常灭",
	"AlwaysOn":"常亮",
	"Always_forward_to":"无条件转移",
	"And the browser must not be closed or refreshed!":"并且浏览器不可关闭或刷新页面！",
	"AnonymousCall OffCode can not contain ! and &":"! 和 & 为非法字符！",
	"AnonymousCall OnCode can not contain ! and &":"! 和 & 为非法字符！",
	"AnonymousReject OffCode can not contain ! and &":"! 和 & 为非法字符！",
	"AnonymousReject OnCode can not contain ! and &":"! 和 & 为非法字符！",
	"Anonymous_Call":"匿名特征码",
	"Anonymous_Call_Rejection":"匿名呼叫拒绝",
	"Answer By Hand":"摘手柄应答",
	"Answer":"应答",
	"AnswerNewInCall":"接听新来电",
	"Answer_call_only":"仅接听",
	"Append_Delete":"Append Delete",
	"Append_Limit_Mode":"Append Limit Mode",
	"Append_Limit_Size":"Append Limit Size",
	"Append_Stop":"Append Stop",
	"Apr":"四月",
	"April":"四月",
	"Are you sure delete user-defined factory config?":"是否删除自定义出厂配置？",
	"Are you sure to delete the chosen photo?":"确定删除选中的相片？",
	"Are you sure to remove the ringtone??":"确定要删除铃声？",
	"Are you sure to remove the wallpaper??":"确定要删除壁纸？",
	"Are you sure to set a blank password?":"确定设置一个空白的密码吗?",
	"Area Code":"区域代码",
	"As Bridge":"桥接模式",
	"As Router":"路由模式",
	"AsSend":"送号键",
	"Ask customers downloading status failed!!":"查询客户下载状态失败！",
	"Attended Tranfer":"咨询转",
	"Attended Transfer":"咨询转",
	"Audio Alert for BLF Pickup":"截答提示音",
	"Audio Alert for Parked Call":"驻留提示音",
	"Audio Settings:":"声音配置",
	"Audio codecs":"语音编解码",
	"Audio":"声音",
	"Aug":"八月",
	"August":"八月",
	"Australia":"澳大利亚",
	"Austria":"奥地利",
	"Auto Provision":"自动更新",
	"Auto":"自动",
	"Auto-negotiation":"自适应速率",
	"AutoAnswer":"自动应答",
	"AutoAnswerDelay":"自动接听延迟",
	"AutoRedial":"自动重拨",
	"AutoRedialInterval (1~300s)":"自动重拨间隔（1~300秒）",
	"AutoRedialInterval should be a number !!":"自动重拨间隔须为数字！",
	"AutoRedialTimes (1~300)":"自动重拨次数（1~300）",
	"AutoRedialTimes should be a number !!":"自动重拨次数须为数字！",
	"Auto_answer":"自动应答提示音",
	"Automatic":"自动",
	"AutopFinish":"自动完成更新",
	"Autoprovision Now":"立即更新",
	"Autoprovision":"自动更新",
	"BLA_Number":"共享线路号码",
	"BLA_Subscription_Period":"共享线路订阅周期",
	"BLF LED Mode":"BLF指示灯模式",
	"BLF List Retrieve call parked Code":"BLF List 取回截答码",
	"BLF List":"BLF List",
	"BLF":"BLF",
	"BLFList_URL":"BLF List URI",
	"BackLightTime":"背光灯时间",
	"BackLightTime(seconds)":"背光灯激活时间（秒）",
	"Base":"基础",
	"Basic":"基础",
	"Begin time can't be later than end time!":"开始时间须早于结束时间！",
	"Belgium":"比利时",
	"Blacklist":"黑名单",
	"BlfListBargeInCode":"BLF List 插入会话特征码",
	"BlfList_Code":"BLF List截答特征码",
	"Blind Transfer OnHook":"挂机盲转",
	"Blind Transfer":"盲转",
	"Block Out":"限制呼出",
	"Block XML In Calling":"通话中阻止XML推送",
	"BlockOut Number":"阻止号码",
	"Bluetooth Active":"蓝牙激活",
	"Bluetooth Settings:":"蓝牙设置",
	"Bluetooth":"蓝牙",
	"Brazil":"巴西",
	"Bridge":"桥接模式",
	"BroadSoft Buddies":"网络好友",
	"Broadsoft Directory":"网络联系人",
	"Broadsoft":"网络",
	"BroadsoftActive":"Broadsoft功能激活",
	"Broadsoft_SCA":"网络线路共享",
	"Browser":"浏览",
	"Buddies":"好友",
	"Busy To Idle":"通话进入闲置",
	"Busy":"忙音",
	"BusyToneDelay scope2":"忙音时长（秒）",
	"Busy_forward_to":"遇忙转移",
	"Button Sound":"按键音",
	"CA_Certificate":"CA证书",
	"CA_Certificates":"CA证书",
	"CDP":"CDP",
	"CIDSource":"来电显示域",
	"CM  Key":"CM键",
	"CNG":"舒适噪音",
	"CONF":"会议",
	"Call Display":"来电显示",
	"Call Information Display Method":"呼叫显示方式",
	"Call Panel":"呼叫面板",
	"Call Park Code":"驻留特征码",
	"Call Park Mode":"驻留方式",
	"Call Park":"通话驻留",
	"Call Park:":"通话驻留",
	"Call Pickup":"呼叫截答",
	"Call Pickup:":"呼叫截答",
	"Call Pull Feature access code":"拉回通话特征码",
	"Call Return":"回拨",
	"Call States":"呼叫状态",
	"Call Waiting Tone":"呼叫等待音",
	"CallCompletion":"呼叫完成",
	"CallFailed":"呼叫失败界面",
	"CallIn":"来电界面",
	"CallList_Show_Num":"呼叫列表显示号码",
	"CallLog":"呼叫记录",
	"CallWaiting":"呼叫等待",
	"CallWaitingOffCode":"呼叫等待禁用特征码",
	"CallWaitingOnCode":"呼叫等待启用特征码",
	"Call_List":"呼叫列表",
	"Call_Waiting":"呼叫等待提示音",
	"Callog:":"呼叫记录",
	"Can't move to same group!":"不能移动到相同组！",
	"Cancel":"取消",
	"Chile":"智利",
	"China":"中国",
	"Chinese_S":"简体中文(Chinese Simplified)",
	"Chinese_T":"繁体中文(Chinese Traditional)",
	"ChoiceSRTP":"选择SRTP",
	"Close Always Forward":"关闭无条件前转",
	"Close Busy Forward":"关闭遇忙前转",
	"Close DND":"关闭免打扰",
	"Close NoAnswer Forward":"关闭无应答前转",
	"Close Power Light":"关闭电源指示灯",
	"Code":"区号",
	"Codec":"编解码",
	"Common AES Key":"AES密钥",
	"Common Power Light On":"默认电源指示灯",
	"Common":"自动",
	"Common_Name_Validation":"用户名确认",
	"Company":"公司",
	"Compulsory":"强制加密",
	"Conference":"会议",
	"Conference_Type":"会议类型",
	"Conference_URI":"会议 URI",
	"Conferenced":"会议界面",
	"Configuration updating ...":"配置更新中...",
	"Configuration updating, please wait!":"配置更新中，请稍等！",  
	"Configuration":"配置管理",
	"Confirm Password":"确认密码",
	"Confirm":"提交",
	"Congestion":"网络拥塞提示音",
	"Connected":"已连接",
	"Connecting":"连接界面",
	"ConnectionRequestPassword":"请求连接密码",
	"ConnectionRequestUsername":"请求连接用户名",
	"Contacts":"联系人",
	"Content shouldn't be empty !":"内容不能为空！",
	"Contrast":"对比度",
	"CosmoCom":"CosmoCom",
	"Critical threshold for Delay":"延迟临界阈值",
	"Critical threshold for Moslq":"MOS-LQ临界阈值",
	"Current Time":"当前时间",
	"Custom Button":"自定义按键",
	"Custom Cert":"自定义证书",
	"Custom Directories:":"定制通讯录：",
	"Custom Option":"自定义选项",
	"Custom SoftKey":"自定义软键",
	"Custom logo":"自定义徽标",
	"Custom":"自定义",
	"CustomFactoryConfig":"自定义出厂配置",
	"Czech ETSI":"捷克ETSI",
	"Czech":"捷克",
	"DD MMM YYYY":"DD MMM YYYY",
	"DD-MMM-YY":"DD-MMM-YY",
	"DD/MM/YY":"DD/MM/YY",
	"DD/MM/YYYY":"DD/MM/YYYY",
	"DHCP Active":"DHCP激活",
	"DHCP Option Value":"DHCP选项值",
	"DHCP VLAN":"DHCP VLAN",
	"DHCP":"DHCP",
	"DHCPTime":"DHCP时间",
	"DHCP_Server_Status":"DHCP服务器状态",
	"DND Status":"免打扰状态",
	"DND":"免打扰",
	"DND:":"免打扰",
	"DNDActive":"免打扰功能激活",
	"DNDEmergency":"紧急号码",
	"DND_Authorized_Numbers":"免打扰鉴权号码",
	"DND_Off_Code":"免打扰关闭特征码",
	"DND_On_Code":"免打扰开启特征码",
	"DNS-NAPTR":"DNS-NAPTR",
	"DPickup":"指定截答",
	"DST Start Day of Week Last in Month":"月起始星期",
	"DST Start Day of Week":"星期几开始",
	"DST Start Month":"开始月份",
	"DST Stop Day of Week Last in Month":"月结束星期",
	"DST Stop Day of Week":"结束星期",
	"DST Stop Month":"结果月份",
	"DST_ByDate":"日期方式",
	"DST_ByWeek":"周方式",
	"DTMF":"DTMF",
	"DTMF-Relay":"DTMF延迟",
	"DTMFRepetition":"DTMF重发",
	"DTMFReplaceTran":"DTMF透明替代",
	"DTMF_Info_Type":"DTMF内容类型",
	"DTMF_Payload seconds(96~255s)":"DTMF负载（96~127）",
	"DTMF_Type":"DTMF类型",
	"Date":"日期",
	"Date_Format":"日期格式",
	"Day of week":"周几",
	"Day":"日",
	"Daylight Saving Time":"夏令时",
	"Dec":"十二月",
	"December":"十二月",
	"Default Cert":"默认证书",
	"Default Gateway":"网关地址",
	"Default":"默认",
	"Del":"删除",
	"DelOldcontact":"删除原有联系人",
	"Delay must less than 300 !":"最大延迟须小于300！",
	"Delay must more than 60 !":"最小延迟须大于60！",
	"Delete All":"全部删除",
	"Delete Photo":"删除相片",
	"Delete server certs error!":"删除服务器证书错误！",
	"Delete":"删除",
	"Denmark":"丹麦",
	"Deutsch":"德语",
	"Device_Certificate":"设备证书",
	"Device_Certificates":"设备证书",
	"Device_Type":"连接类型",
	"Dia_Number":"呼叫号码",
	"Dial Plan":"拨号规则",
	"Dial":"拨号",
	"Dial-now Rule should not be empty!":"即时呼出规则不可为空！",
	"Dial-now Rule":"即时拨号规则",
	"Dial-now":"立即呼出",
	"Dial_recall":"回拨提示音",
	"Dialed_List":"拨号列表",
	"Dialing":"拨号界面",
	"DialogInfo_Call_Pickup":"Dialog-Info截答方式",
	"Direct Call Pickup Code":"指定截答特征码",
	"Direct Call Pickup":"指定截答",
	"Direct Pickup":"指定截答",
	"Directories":"联系人",
	"Directory":"联系人",
	"Directotries:":"通讯录",
	"Disable codecs":"禁用编解码",
	"Disable":"禁用",
	"Disabled":"禁用",
	"Disp Code":"处置码",
	"Display Called Party Information":"显示被叫方信息",
	"Display Contact Photo":"显示联系人头像",
	"Display Forward Call Popup":"显示转移来电弹窗",
	"Display Method on Dialing":"拨号界面标题栏取值",
	"Display Missed Call Popup":"显示未接来电弹窗",
	"Display Name":"显示名称",
	"Display Report options on Web":"在网页显示报告选项",
	"Display Report options on phone":"在话机显示报告选项",
	"Display Text Message Popup":"显示文本信息弹窗",
	"Display Voice Mail Popup":"显示语言留言弹窗",
	"Diversion/History-Info":"转移/历史信息",
	"Do not support bridge in PPPoE mode!":"PPPoE模式不支持桥接模式！",
	"Do not support vlan in PPPoE mode!":"PPPoE模式下不支持VLAN！",
	"Do you want to autoprovision now?":"是否立即执行自动更新？",
	"Do you want to delete all contacts in BlackList?":"确定要清空黑名单？",
	"Do you want to delete all contacts in ContactList?":"确定要清空联系人？",
	"Do you want to discard your changes??":"是否放弃修改？",
	"Do you want to discard your changes??":"是否放弃变更？",
	"Do you want to import the configuration file to All_Configuration":"导入所有配置文件?",
	"Do you want to import the configuration file to Local_Configuration":"导入本地配置文件?",
	"Do you want to move the contacts to ":"是否移动联系人到",
	"Do you want to reset to factory ?":"是否恢复为出厂配置？",
	"Do you want to restart your machine?":"是否重启话机？",
	"Down":"向下",
	"Download failed!":"下载失败!",
	"Download failed, please try again":"下载失败，请重试！",
	"Downloading custom list, please try latter!!":"正在下载定制列表，请稍候再试！",
	"Dsskey":"可编程按键",
	"Dual Headset":"双耳机功能",
	"E-Common":"E-Common",
	"EAP-FAST":"EAP-FAST",
	"EAP-MD5":"EAP-MD5",
	"EAP-PEAP/GTC":"EAP-PEAP/GTC",
	"EAP-PEAP/MSCHAPv2":"EAP-PEAP/MSCHAPv2",
	"EAP-TLS":"EAP-TLS",
	"EAP-TTLS/EAP-GTC":"EAP-TTLS/EAP-GTC",
	"EAP-TTLS/EAP-MSCHAPv2":"EAP-TTLS/EAP-MSCHAPv2",
	"ECHO":"回声消除",
	"EXP Switch":"切换扩展台",
	"Early Media":"早期媒体",
	"Echo_Cancellation":"回声消除",
	"Edit":"编辑",
	"Emergency":"紧急呼叫",
	"Empty":"空",
	"Enable AutoFavorite":"自动收藏状态",
	"Enable Custom Directories":"启用定制通讯录",
	"Enable DHCP Server":"启用DHCP服务器",
	"Enable LDAP":"启用LDAP",
	"Enable Periodic Inform":"启用周期性通知",
	"Enable Semi-Attend Transfer":"启用半咨询转",
	"Enable Signal Encode":"启用信号编码",
	"Enable TR069":"启用TR069",
	"Enable codecs":"启用编解码",
	"Enable":"启用",
	"EnablePageTips":"启用提示页面",
	"EnableSessionTimer":"启用会话定时器",
	"EnableUserEqualPhone":"发送 user=phone",
	"Enable_Outbound_Proxy_Server":"启用Outbound代理",
	"Enable_SemiAttend_Transfer":"启用半咨询转",
	"Enabled":"启用",
	"End Call":"挂断通话",
	"End Date":"结束日期",
	"End Hour of Day":"日结束时间",
	"End IP Address":"结束IP地址",
	"EndSystemDelay":"结束系统延迟",
	"English":"英语(English)",
	"Enter at least 6 characters with 1 number and 1 alphabet min":"输入至少1位数字和1位字母的6位数密码！",

	"Enterprise IP phone SIP-T27G":"企业IP电话SIP-T27G",
	"Enterprise IP phone SIP-T23G":"企业IP电话SIP-T23G",
	"Enterprise IP phone SIP-T27P":"企业IP电话SIP-T27P",
	"Enterprise IP phone SIP-T23P":"企业IP电话SIP-T23P",
	"Gigabit Color IP Phone SIP-T29G":"千兆彩屏IP电话SIP-T29G",
	"Enterprise IP phone SIP-T41P":"企业IP电话SIP-T41P",
	"Enterprise IP phone SIP-T41G":"企业IP电话SIP-T41G",	
	"Enterprise IP phone SIP-T42G":"企业IP电话SIP-T42G",	
	"Enterprise IP phone SIP-T42P":"企业IP电话SIP-T42P",								
	"Gigabit Color IP Phone SIP-T46G":"千兆彩屏IP电话SIP-T46G",
	"Gigabit Color IP Phone SIP-T48G":"千兆彩屏IP电话SIP-T48G",

	"Enterprise IP phone SIP-T61P":"企业IP电话SIP-T61P",
	"Enterprise IP phone SIP-T66G":"企业IP电话SIP-T66G",

	"Enterprise:":"企业",
	"EnterpriseCommon:":"普通企业",
	"Error: Element's name is empty!":"错误:名字是空的！",
	"Error: More than 50 groups.":"错误：最多为50个群组！",
	"Error: More than 50.":"错误：最多为50个群组.",
	"Error: More than five groups.":"错误：最多为5个群组！",
	"Error: Record with the same Prefix already exists!":"错误：条目中存在相同的号首！",
	"Error: Record with the same Rule already exists!":"错误：存在重复规则！",
	"Error: Same config":"错误: 重复信息！",
	"Error: The max dial-now count is ":"错误：最大规则数是 ",
	"Error: The maximum number of certificates is 10, please delete one before upload":"错误：证书最大数量为10，请先删除后再上传！",
	"Error: The same record already exists!":"错误：存在重复条目！",
	"Error: Write dsskey config error!":"错误: dsskey配置写错!",
	"Error:Black list is full!":"错误：黑名单已满！",
	"Error:Contact already existed!":"错误：联系人已存在！",
	"Error:Contact is asyncing!":"错误：联系人异步中！",
	"Error:Contact is not black!":"错误：联系人不属于黑名单！",
	"Error:Contact is not local!":"错误：联系人不是本地的！",
	"Error:Contact list is full!":"错误：联系人列表已满！",
	"Error:Contact name empty!":"错误：联系人名字为空！",
	"Error:Contact not existed!":"错误：联系人不存在！",
	"Error:Delete ring error!":"错误：删除铃声错误！",
	"Error:Duplcate contact!":"错误：重复联系人！",
	"Error:Duplicate group!":"错误：重复群组！",
	"Error:Export contact file error!":"错误：导出联系人文件错误！",
	"Error:File isn't exist!":"错误：文件不存在！",
	"Error:File upload error!":"错误：文件上传错误！",
	"Error:Group  list is full!":"错误：群组列表已满！",
	"Error:Group already existed!":"错误：群组已存在！",
	"Error:Group can not delete!":"错误：群组不能删除",
	"Error:Group empty!":"错误：群组为空！",
	"Error:Group not existed!":"错误：群组不存在！",
	"Error:Import config error!":"错误：导入配置错误！",
	"Error:Import contact file error!":"错误：导入联系人文件错误！",
	"Error:Import local config error!":"错误：导入本地配置错误！",
	"Error:Invalid file!":"错误：无效文件！",
	"Error:Invalid group id!":"错误：无效群组ID！",
	"Error:Invalid path!":"错误：无效路径！",
	"Error:Network error!":"错误：网络错误！",
	"Error:No contact group!":"错误：无联系人群组！",
	"Error:No default group!":"错误：无默认群组！",
	"Error:No space left!":"错误：无剩余空间！",
	"Error:Other error!":"错误：其他错误！",
	"Error:Photo name error!":"错误：照片名字错误！",
	"Error:The destination folder does not exist!":"错误：目标文件夹不存在！",
	"Error:The password is error!":"错误：密码错误！",
	"Error:Too many blacklist!":"错误：太多黑名单！",
	"Error:Too many group!":"错误：太多群组！",
	"Error:Too many local contact!":"错误：太多本地联系人！",
	"Error:Upload error!":"错误：上传失败！",
	"Error:User factory config doesn't exist!":"错误：用户出厂配置不存在！",
	"Error:Write remote_phonebook_list.xml error!":"错误：写remote_phonebook_list.xml错误！",
	"Error:You don't have enough jurisdiction!":"错误：没有足够权限！",
	"Established":"建立会话",
	"Exist the ring!":"铃声已存在！",
	"Expansion Key":"扩展按键",
	"Expansion":"扩展",
	"Expiration":"有效期",
	"Export CFG Configuration File":"导出 CFG 配置文件",
	"Export CSV":"CSV格式导出",
	"Export System Log":"导出SYSLOG",
	"Export XML":"XML格式导出",
	"Export":"导出",
	"Export_Import_Config":"导入导出配置",
	"Ext Key":"扩展键",
	"Ext":"扩展设备",
	"Extended":"扩展",
	"Extension":"分机号",
	"FAC":"特征码",
	"FROM":"来自",
	"Fail : Too many keys !":"失败：设置键过多！",
	"Fail to upload photo ! [Can not compress the picture]":"上传照片失败！[不能压缩图标]",
	"Fail to upload photo ! [The Resolution of the picture is too large]":"上传照片失败！[图片分辨率太大]",
	"Failed":"失败",
	"Family":"家庭",
	"Favorite":"联系人",
	"Favorites":"联系人",
	"Feature_Key_Synchronisation":"功能同步",
	"Features":"功能",
	"Feb":"二月",
	"February":"二月",
	"File Name is too long!":"文件名过长！",
	"Finland":"芬兰",
	"Firmware Version":"固件版本",
	"Firmware of the SIP Phone will be updated. \nIt will take 5 minutes to complete.Please don't power off!":"将在5分钟后完成。\n请勿断电！",
	"Firmware of the SIP Phone will be updated.":"话机固件将升级！",
	"Firmware updating ...":"固件升级中…",
	"Firmware_Version":"固件版本",
	"First In Month":"第1周",
	"Fixed Type":"计算方式",
	"Fixed":"静态",
	"ForbinSRTP":"禁止SRTP",
	"ForceSRTP":"强制SRTP",
	"Forward":"呼叫转移",
	"Forward&DND":"呼叫转移 & 免打扰",
	"Forward:":"呼叫转移",
	"ForwardActive":"来电前转功能激活",
	"ForwardIncomingCall":"前转来电",
	"Forwarded_List":"前转来电记录",
	"Fourth In Month":"第4周",
	"France":"法国",
	"French":"法语(Français)",
	"Fri":"星期五",
	"Friday":"星期五",
	"Friend":"朋友",
	"Full Contact Info":"完整联系人信息",
	"Funckey":"功能键",
	"Fwd International":"国际前转来电",
	"G-Common":"G-Common",
	"G722":"G722",
	"G723_53 and G723_63  can not be applied simultaneously":"G723.53和G723.63不可同时使用！",
	"G723_53":"G723_53",
	"G723_63":"G723_63",
	"G726-16":"G726-16",
	"G726-24":"G726-24",
	"G726-32":"G726-32",
	"G726-40":"G726-40",
	"G729":"G729",
	"GPark":"群组截答",
	"GPickup":"群组截答",
	"GSM":"GSM",
	"Gateway IP address is invalid":"无效网关！",
	"Gateway IPv6 address is invalid":"无效IPv6网关！",
	"Gateway":"网关地址",
	"General Information":"基本信息",
	"General_Information":"基本信息",
	"German":"德语(Deutsch)",
	"Germany":"德国",
	"Get CSVFile data error!":"获取CSV文件错误！!",
	"Great Britain":"大不列颠岛",
	"Greece":"希腊",
	"Group Call Park Code":"群组解答特征码",
	"Group Call Park":"群组驻留",
	"Group Call Pickup Code":"群组截答特征码",
	"Group Call Pickup":"群组截答",
	"Group Listen":"群听",
	"Group Pickup":"群组截答",
	"Group Setting":"群组设置",
	"Group":"群组",
	"Group:":"群组",
	"GroupCommon:":"普通群组",
	"HOLD":"保持",
	"HTTP Port (1~65535)":"HTTP监听端口(1~65535)",
	"HTTP":"HTTP",
	"HTTPS Port (1~65535)":"HTTPS监听端口(1~65535)",
	"HTTPS":"HTTPS",
	"HTTPS_Only":"HTTPS Only",
	"HTTP_HTTPS":"HTTP HTTPS",
	"HTTP_Only":"HTTP Only",
	"Handfree Send Volume (1~53)":"免提发送音量",
	"Handset Send Volume (1~53)":"手柄发送音量",
	"Hang Up":"挂断",
	"Hangup":"结束通话",
	"Hardware Version":"硬件版本",
	"Hardware_Version":"硬件版本",
	"Headset Prior":"耳机优先",
	"HeadsetSendVolume (1~53)":"耳机发送音量",
	"HeadsetSendVolume(1~53)":"耳机发送音量（1~53）",
	"Held":"被保持界面",
	"Hidden":"隐藏",
	"Hide Feature Access Codes":"隐藏特征码",
	"High":"高",
	"History":"呼叫记录",
	"Hold":"保持",
	"Hold/Held Power Light On":"保持通话时电源指示灯闪烁",
	"Host Server":"服务器地址",
	"HotDesking":"移动办公",
	"HotLine_Number":"热线号码",
	"Hoteling":"移动办公",
	"Hotline Number should be a number or IP address!!":"热线号码应该是一个号码或者IP地址",
	"Hotline_Delay(0~10)":"热线延迟（0~10秒）",
	"Hour ":"时",
	"Hour":"时",
	"Hour_12":"12小时制",
	"Hour_24":"24小时制",
	"Http":"http",
	"Https":"https",
	"Hungary":"匈牙利",
	"ICMPv6 Status":"ICMPv6状态",
	"IME":"输入法",
	"INBAND":"带内",
	"IP Direct Auto Answer":"IP直拨自动应答",
	"IP address is invalid":"无效IP地址！",
	"IP_Address":" IP地址",
	"IPv4 & IPv6":"IPv4 & IPv6",
	"IPv4 Config":"IPv4配置",
	"IPv4":"IPv4",
	"IPv6 Config":"IPv6配置",
	"IPv6 Static DNS":"静态IPv6DNS",
	"IPv6 prefix is invalid":"无效IPv6地址前缀！",
	"IPv6 prefix(0~128)":"IPv6前缀(0~128)",
	"IPv6":"IPv6",
	"Identity":"账号",
	"Idle To Busy":"闲置进入通话",
	"Import CFG Configuration File":"导入CFG 配置文件",
	"Import CSV":"CSV格式导入",
	"Import Local Contact File":"导入本地联系人",
	"Import XML":"XML格式导入",
	"Import":"导入",
	"Import_Factory_Config":"导入出厂配置",
	"Import_Server_Certificate":"导入服务器证书",
	"Import_Trusted_Certificate":"导入受信证书",
	"IncomingCall":"来电",
	"Index":"索引",
	"India":"印度 ",
	"Inexistence":"不存在",
	"Info":"特殊信息",
	"Input contains invalid character like ":"输入字符包含无效字符，如",
	"Input contains invalid character like '<>'":"无效字符：'<>'",
	"Input contains invalid character like <>'\"\\":"无效字符：<>'\"\\",
	"Install certs failed!":"安装证书失败！",
	"Install server certs error!":"安装服务器证书错误！",
	"Inter Digit Time(1~14s)":"自动呼出激活时间（1~14秒）",
	"InterarrivalJitter":"间隔抖动",
	"Intercom":"对讲机",
	"Intercom:":"对讲机",
	"IntercomBarge":"对讲介入",
	"IntercomMute":"对讲机静音",
	"IntercomTone":"对讲提示音",
	"Internal_Ringer_File":"内置铃声文件",
	"Internal_Ringer_Text":"内置铃声名称",
	"Internet Port":"因特网接口",
	"Interval_min":"间隔（分钟）",
	"Invaid Emergency should only contain digital number and ','":"紧急号码有效字符为：数字和\",\"",
	"Invaid File Name!":"无效文件名！",
	"Invaid File Type!":"无效文件类型！",
	"Invail value.":"无效值！",
	"Invaild  BroadsoftXSIHostAddr":"无效XSI服务器地址！",
	"Invaild  Primary NTP Server":"无效首选NTP服务器！",
	"Invaild  Secondary NTP Server":"无效备选NTP服务器！",
	"Invalid Custom Option!":"无效自定义选项！",
	"Invalid DHCP option!":"无效DHCP选项！",
	"Invalid DTMF payload !":"无效DTMF负载！",
	"Invalid Day!":"无效日期！",
	"Invalid Max RTP Port !":"无效最大RTP端口！",
	"Invalid Min RTP Port !":"无效最小RTP端口！",
	"Invalid Number":"无效号码",
	"Invalid SNMP Port !":"无效SNMP端口！",
	"Invalid SNMP Trused address !":"无效SNMP服务器地址！",
	"Invalid SipQos":"无效SIP QoS！",
	"Invalid String":"无效字符串！",
	"Invalid URL!":"无效URL！",
	"Invalid VID":"无效VID！",
	"Invalid VoiceQos":"无效Voice QoS！",
	"Invalid characters. Only digits and commas are allowed!":"无效字符。只能输入数字和逗号！",
	"Invalid connection request username!":"无效用户名连接请求！",
	"Invalid daylight saving end day!":"无效夏令时结束时间！",
	"Invalid daylight saving start day!":"无效夏令时开始时间！",
	"Invalid daylight saving start/end time !":"无效夏令时起止时间！",
	"Invalid factory file!":"无效出厂文件！",
	"Invalid file name!":"无效文件名！",
	"Invalid group name!":"无效群组名称！",
	"Invalid password!":"无效密码！",
	"Invalid prefix String":"无效号首字符串！",
	"Invalid request password!":"无效密码请求！",
	"Invalid ring file!":"无效铃声文件！",
	"Invalid ringer text string!":"无效字符串！",
	"Invalid server URL!":"无效服务器地址",
	"Invalid syslog server address !":"无效SYSLOG服务器地址！",
	"Invalid username!":"无效用户名！",
	"Invalid value!":"无效值！",
	"Ip Changed":"IP变更",
	"IsDeal180":"180 Ring工作域",
	"Issued_By":"颁发者",
	"Issued_To":"颁发给",
	"Italian":"意大利语(Italiano)",
	"Italy":"意大利",
	"JITTER_BUFFER":"RTP抖动缓冲区",
	"Jan":"一月",
	"January":"一月",
	"Japan":"日本",
	"Jitter":"抖动",
	"JitterBufferMax":"最大抖动缓冲区",
	"Jul":"七月",
	"July":"七月",
	"Jun":"六月",
	"June":"六月",
	"Keep Alive Interval":"续活间隔",
	"Keep Alive Type":"续活方式",
	"Key":"按键",
	"Keyboard_Lock":"键盘锁类型",
	"Keyboard_Lock_Enable":"启用键盘锁",
	"Keypad Lock":"键盘锁",
	"LAN_IP_Address":"LAN地址",
	"LDAP":"LDAP",
	"LDAPTLSMode":"LDAP加密传输模式",
	"LDAP_Display_Name":"LDAP显示名称",
	"LDAP_Lookup_For_Callout":"LDAP呼出查询",
	"LDAP_Lookup_For_Incoming_Call":"LDAP匹配来电",
	"LDAP_Name_Attributes":"LDAP名称属性",
	"LDAP_Name_Filter":"LDAP名称过滤",
	"LDAP_Number_Attributes":"LDAP号码属性",
	"LDAP_Number_Filter":"LDAP号码过滤",
	"LDAP_Sorting_Results":"LDAP搜索排序",
	"LED Off in Idle":"LED闲置关闭",
	"Label Length":"标签长度",
	"Label":"标签",
	"Language":"语言",
	"Last In Month":"最后1周",
	"Left":"向左",
	"Line 1":"账号 1",
	"Line 10":"账号 10",
	"Line 11":"账号 11",
	"Line 12":"账号 12",
	"Line 13":"账号 13",
	"Line 14":"账号 14",
	"Line 15":"账号 15",
	"Line 16":"账号 16",
	"Line 17":"账号 17",
	"Line 18":"账号 18",
	"Line 19":"账号 19",
	"Line 2":"账号 2",
	"Line 20":"账号 20",
	"Line 21":"账号 21",
	"Line 22":"账号 22",
	"Line 3":"账号 3",
	"Line 4":"账号 4",
	"Line 5":"账号 5",
	"Line 6":"账号 6",
	"Line 7":"账号 7",
	"Line 8":"账号 8",
	"Line 9":"账号 9",
	"Line Active":"线路激活",
	"Line Key":"账号键",
	"Line Key1-5":"账号键 1-5",
	"Line Key1-7":"账号键 1-7",
	"Line Key1-9":"账号键 1-9",
	"Line Key10-18":"账号键 10-18",
	"Line Key11-15":"账号键 11-15",
	"Line Key15-21":"账号键 15-21",
	"Line Key19-27":"账号键 19-27",
	"Line Key6-10":"账号键 6-10",
	"Line Key8-14":"账号键 8-14",
	"Line Selection":"账号选择",
	"Line":"线路",
	"Link_Status":"连接状态",
	"Listening_Address":"监听地址",
	"Lithuania":"立陶宛",
	"Live Dialpad":"自动呼出",
	"Load Fail":"加载失败",
	"Load Failed":"加载失败",
	"Load Ringtone":"加载铃声",
	"Load_server_cer_file":"加载服务器证书文件",
	"Load_trusted_cer_file":"加载受信证书文件",
	"Loading, please waiting":"加载中，请稍候！",
	"Loading, please waiting...":"加载中，请稍候！",
	"Local Anonymous Rejection":"本地匿名拒接",
	"Local Anonymous":"本地匿名",
	"Local Codec":"本地编解码",
	"Local Configuration":"本地配置",
	"Local Contacts":"本地联系人",
	"Local Directory":"本地联系人",
	"Local Group":"本地群组",
	"Local History":"本地呼叫记录",
	"Local IP":"本地IP",
	"Local Phonebook":"本地联系人",
	"Local Port":"本机端口",
	"Local SIP Port should be a number !!":"本地SIP端口须为数字！",
	"Local User":"本地用户",
	"Local codec":"本地编解码",
	"Local user":"本地用户",
	"Local":"本地",
	"Local_Conf":"本地会议",
	"Local_Configuration":"本地配置",
	"Local_Identity":"本地账号",
	"Local_RTP_Port":"本地RTP端口",
	"Local_SIP_Port":"本地SIP端口",
	"Location":"位置",
	"Lock":"锁定",
	"LogOff":"未注册",
	"LogOn":"注册成功",
	"Log_Out":"注销",
	"Login address":"登录地址",
	"Login":"登入",
	"Logon Wizard":"注册向导",
	"Low":"低",
	"MAC-Oriented AES Key":"指定MAC的AES密钥",
	"MAC_Address":"物理地址",
	"MD5_Password":"MD5密钥",
	"MM/DD/YY":"MM/DD/YY",
	"MOS-CQ":"MOS-CQ",
	"MOS-LQ":"MOS-LQ",
	"MUTE":"静音",
	"MWI_Subscription_Period  WSP_Scope seconds":"语音订阅周期（秒）",
	"Manager":"管理",
	"Manual_Time":"手动设置时间",
	"Mar":"三月",
	"March":"三月",
	"Max Delay is less than Min Delay !":"最大延迟须大于最小延迟！",
	"Max Length (1-15)":"最大长度（1~15）",
	"Max RTP Port is less than Min RTP Port !":"最大RTP端口要大于最小RTP端口！",
	"Max.Hits(1~32000)":"Max. Hits (1~32000)",
	"MaxRtpPort (1~65535)":"最大本地RTP端口（1~65535）",
	"Max_Delay":"最大延迟",
	"May":"五月",
	"Meet-Me Conference":"Meet-Me会议",
	"Memory Key":"记忆键",
	"Menu":"菜单",
	"Menukey":"菜单键",
	"Message":"信息提示音",
	"Mexico":"墨西哥",
	"Min Length (1-15)":"最小长度（1~15）",
	"MinRtpPort (1~65535)":"最小本地RTP端口（1~65535）",
	"Min_Delay":"最小延迟",
	"Minute":"分钟",
	"MissCallLog":"未接来电记录",
	"Missed Call":"未接来电",
	"Missed_List":"未接来电记录",
	"Mobile Number":"移动电话",
	"Mode":"模式",
	"Mode(IPv4/IPv6)":"IPv4/IPv6",
	"Mode_802_1_x":"802.1x 模式",
	"Mon":"星期一",
	"Monday":"星期一",
	"Month":"月",
	"Move To":"移动到",
	"Multicast Listening":"组播监听",
	"MulticastCodec":"多播编解码",
	"MulticastIP":"组播地址",
	"MusicServerURI":"媒体服务器URI",
	"Mute Power Light On":"静音时电源指示灯闪烁",
	"Mute":"静音",
	"My Status":"我的状态",
	"N/A":"空",
	"NAT":"NAT",
	"NAT_Traversal":"NAT穿透",
	"NOTE":"说明",
	"NTP By DHCP Priority":"NTP由DHCP优先",
	"Name cannot be empty !":"姓名不能为空！",
	"Name":"姓名 ",
	"Name+Number":"名字+号码",
	"Netherlands":"荷兰",
	"Network CallLog":"网络通话记录",
	"Network Callog":"网络通话记录",
	"Network Common":"网络通用参数",
	"Network Directories":"网络联系人",
	"Network Directory":"网络联系人",
	"Network Favorite":"网络联系人",
	"Network Favourite":"网络收藏夹",
	"Network Group":"网络群组",
	"Network":"网络配置",
	"Network:":"网络配置",
	"NetworkPacketLossRate":"网络丢包率",
	"Network_Conf":"网络会议",
	"New Call":"新呼叫",
	"New Password":"新密码",
	"New SMS":"新信息",
	"New Zealand":"新西兰",
	"New password is similar to username, are you sure to set it?":"新密码跟用户名相同, 确定要设置?",
	"New password is too simple, are you sure to set it?":"密码太简单了,确定要设置 ?",
	"NewCall":"新呼叫",
	"Next":"后页",
	"No Account":"无账号",
	"No data to import":"无导入数据！",
	"No expansion module connected! Please connect one or more units then refresh this page.":"未连接扩展台。\n请先连接扩展台！",
	"No space left!":"无剩余空间！",
	"No_answer_forward_to":"无应答转移",
	"Nominal":"常态延迟",
	"None":"无",
	"Normal Delay is beyond scope !":"常态延迟应该在有效范围内！",
	"Norway":"挪威",
	"Not Found : ":"未找到：",
	"Notification Popups":"弹出通知窗口",
	"Notify":"通知",
	"Nov":"十一月",
	"November":"十一月",
	"Number Only!!":"只支持号码！",
	"Number of line key":"账号键数量",
	"Number":"号码",
	"Number+Name":"号码+名称",
	"OK":"OK",
	"Oct":"十月",
	"October":"十月",
	"Off Code could not be empty when On Code is set!":"On Code设置后，Off Code不可为空！",
	"Off Code":"关闭特征码",
	"Off hook":"放下手柄",
	"Off":"关",
	"Off_Code":"关闭特征码",
	"Office Num":"办公电话",
	"Office Number":"办公电话",
	"Offset(minutes)":"偏移（分钟）",
	"Old Password":"当前密码",
	"Old group name is empty!":"原群组名为空！",
	"On Code":"开启特征码",
	"On hook":"拿起手柄",
	"On":"开",
	"OnTalk":"通话界面",
	"On_Code":"开启特征码",
	"Only_Accept_Trusted_Certificates":"只允许受信任证书",
	"Open Always Forward":"开启无条件前转",
	"Open Busy Forward":"开启遇忙前转",
	"Open DND":"开启免打扰",
	"Open NoAnswer Forward":"开启无应答前转",
	"Operating, Please  Wait ...":"操作中，请稍候...",
	"Option (1-255)":"Option (128-254)",
	"Option":"选项",
	"Optional":"可选加密",
	"Options":"选项",
	"Other Num":"其它电话",
	"Other Number":"其它电话",
	"Out Dialog BLF(*)":"RFC3856实现BLF",
	"OutboundPort should be a number !!":"Outbound端口须为数字！",
	"Outbound_Proxy_Server":"Outbound代理服务器",
	"Outgoing call":"去电",
	"Outgoing_Identity":"呼出账号",
	"PAI":"PAI",
	"PAI-FROM":"PAI-FROM",
	"PAI-RPID-FROM":"PAI-RPID-FROM",
	"PC Port Link":"PC接口连接",
	"PC Port":"PC接口",
	"PCMA":"PCMA",
	"PCMU":"PCMU",
	"PC_Port":"PC接口",
	"PC_Port_Active":"PC接口激活",
	"PC_Port_Config":"PC接口配置",
	"PC_Port_Link":"PC端口连接",
	"PEAP-MSCHAPV2":"PEAP-MSCHAPV2",
	"PNP Active":"PNP激活",
	"PPPoE":"PPPoE",
	"PSWDialLength Invalid!":"无效密码长度！",
	"PTT":"前缀",
	"PTime(ms)":"打包时长（毫秒）",
	"Packet_Interval (1~3600s)":"发包间隔（1~3600秒）",
	"Packets lost":"丢包",
	"Page":"页",
	"Paging Address":"组播地址",
	"Paging List":"组播列表",
	"Paging":"组播",
	"Paging_Barge":"寻呼介入",
	"Paging_Priority_Active":"寻呼优先级",
	"Park Retrieve Code":"驻留取回特征码",
	"Park":"截答",
	"Parse Fail":"解析错误",
	"Password is similar to username, are you sure to set it?":"密码和用户名类似，确定设置？",
	"Password is too simple, are you sure to set it?":"密码过于简单，确定设置？",
	"Password":"密码",
	"Passwords don't match!":"密码不匹配！",
	"Pcap Feature":"抓包功能",
	"Period for Interval Report":"通知时间周期",
	"Periodic Inform Interval (seconds)":"周期性通知间隔（秒）",
	"Permission denied!":"权限不足!",
	"Personal:":"私有",
	"Phone Call Info":"呼叫历史",
	"Phone Lock Time Out(0~3600s)":"上锁延迟（0~3600秒）",
	"Phone Lock":"键盘锁",
	"Phone":"话机",
	"Phone-Unlock PIN(0~15 digital)":"解锁密码（0~15位数字）",
	"PhoneSetting:":"话机设置",
	"Photo name already existed!":"相片名称已存在！",
	"Photo":"相片",
	"Play Local DTMF Tone":"本地拨号DTMF音",
	"PlayHoldTone":"通话保持音",
	"PlayHoldToneDelay should be a number !!":"保持音播放延迟须为数字！",
	"PlayHoldToneDelay":"通话保持音延迟",
	"Please choose at least one record!":"请选择最少1个条目！",
	"Please choose the DisplayName":"请选择显示名称！",
	"Please click Confirm to load custom directories.":"请点击确认键开始加载定制通讯录！",
	"Please enable a codec at least.":"请至少配置1种编解码！",
	"Please input complete information!":"请输入完整信息！",
	"Please select a .bin format file at first!":"请先选择.bin格式的文件！",
	"Please select a .cfg format file at first!":"首先请选择.cfg格式的文件！",
	"Please select a .png or .jpg or .bmp  format file at first!":"文件格式须为：.png, .jpg, .bmp。",
	"Please select a .wav format file at first!":"请先上传.wav格式的铃声文件！",
	"Please select a correct file(.bin)":"请选择正确的.bin格式文件！",
	"Please select a file":"请选择1个文件！",
	"Please select a group!":"请选择1个群组！",
	"Please select one cert at least.":"请至少选择一个证书。",
	"Please select one record at least.":"请至少选择1项记录。",
	"Please select the contacts list file":"请选择联系人清单！",
	"Please select the record which you want to edit":"请选择要修改的条目！",
	"Please specify the Target number":"请指定接收号码！",
	"Please specify the blockout number!":"请指定限制号码！",
	"Please upload VPN config file first!":"请先上传VPN配置文件！",
	"Please wait and do not power off!":"请等待并保持电源连接！",
	"Polish":"波兰语(Polski)",
	"Port (0~65535)":"端口（1~65535）",
	"Port":"端口",
	"Port_Link":"端口连接",
	"Portugal":"葡萄牙",
	"Portuguese":"葡萄牙语(Português)",
	"Post_Append":"Post Append",
	"Post_Mode":"输出模式",
	"Post_Stor":"Post Stor",
	"Power LED":"电源灯",
	"Power LED:":"电源灯",
	"Power On":"上电启动",
	"PreTrans":"转移界面",
	"Preference":"基本设置",
	"Prefix and Replace should not be Empty !":"前缀与替换不能为空！",
	"Prefix":"前缀",
	"Prev":"前页",
	"Preview":"预览",
	"Prewiew":"预览",
	"PriHold":"私有保持",
	"Primary DNS error, please check":"首选DNS错误，请核对！",
	"Primary DNS":"首选DNS",
	"Primary Server":"首选服务器",
	"Priority":"优先级",
	"Private Hold":"私有保持",
	"Programable Key":"可编程功能键",
	"Protocol":"协议版本",
	"Proxy_Require":"代理请求",
	"PswDial":"密码呼叫",
	"PswLength":"密码长度",
	"PswPrefix":"密码呼叫前缀",
	"Push XML failed!!":"推送XML失败！",
	"Push XML sucessed":"推送XML成功！",
	"Push XML":"推送 XML",
	"PushXML Test":"推送XML测试",
	"PushXML_ServerIP":"XML推送服务器地址",
	"RC4":"RC4",
	"RFC 2543 Hold":"RFC 2543保持模式",
	"RFC2833":"RFC2833",
	"RPID-FROM":"RPID-FROM",
	"RPID-PAI-FROM":"RPID-PAI-FROM",
	"RPort":"RPort",
	"RTP Status":"RTP状态",
	"ReDialTone":"拨号音恢复",
	"ReDialtone number should be a number !!":"二次拨号音须为数字！",
	"ReLogOffTime(1~1000min)":"登入超时（1~1000分钟）",
	"Reboot In Talking":"通话中允许重启",
	"Reboot":"重启",
	"Rebooting , please wait ...":"重启中, 请稍候...",
	"Received_List":"已接来电记录",
	"Recent Call In Dialing":"去电匹配近期呼叫",
	"Record":"录音",
	"RedirectActive":"重定向功能激活",
	"Refresh":"刷新",
	"Reg_Surge_Prev (0~60s)":"随机注册（0~60秒）",
	"Reg_Surge_Prev":"随机注册",
	"Register Failed":"注册失败",
	"Register Name":"注册名称",
	"Register Status":"注册状态",
	"Register":"注册",
	"RegisterFailed":"注册失败",
	"Registered":"已注册",
	"Registering":"正在注册...",
	"Reject":"拒绝",
	"RejectIncomingCall":"拒绝来电",
	"Remote Codec":"远端编解码",
	"Remote Control":"远程控制",
	"Remote IP":"远端IP",
	"Remote Phone Book":"远程地址簿",
	"Remote Phonebook":"远程地址簿",
	"Remote Port":"远端端口",
	"Remote User":"远端用户",
	"Remote codec":"远端编解码",
	"Remote control:":"远程控制",
	"Remote user":"远端用户",
	"RemoteURL":"远程URL",
	"Repeatly":"重复周期",
	"Replace All":"全部替换",
	"Replace Part":"部分替换",
	"Replace Rule Type":"替换规则类型",
	"Replace Rule":"替换规则",
	"Replace":"替换",
	"Report options on phone UI":"话机的报告选项",
	"ReportIP":"报告IP",
	"Request failed!!":"请求失败！",
	"Reserve # in User Name":"保留#送号",
	"Reserved Character in User Name":"在用户名保留字符",
	"Reset Local Config":"重置本地配置",
	"Reset Local Configuration":"重置本地配置",
	"Reset to Default":"恢复默认值",
	"Reset to Factory Setting":"恢复出厂配置",
	"Reset to default":"恢复默认值",
	"Reset":"恢复出厂配置",
	"Resetting , please wait ...":"重置中 , 请稍候 ...",
	"Resume":"恢复",
	"Retrieve Park":"取回驻留",
	"Retrieve":"取回",
	"Return_Code_DND":"免打扰返回码",
	"Return_Code_Refuse":"拒接返回码",
	"Right":"向右",
	"Ring Power Light Flash":"响铃时电源灯闪烁",
	"Ring Tone":"响铃",
	"Ring":"响铃",
	"Ring1.wav":"Ring1.wav",
	"Ring2.wav":"Ring2.wav",
	"Ring3.wav":"Ring3.wav",
	"Ring4.wav":"Ring4.wav",
	"Ring5.wav":"Ring5.wav",
	"Ring6.wav":"Ring6.wav",
	"Ring7.wav":"Ring7.wav",
	"Ring8.wav":"Ring8.wav",
	"RingBack":"回铃界面",
	"Ring_Type":"铃声类型",
	"Ring_back":"回铃音",
	"Ringer_Device_for_Headset":"耳机振铃方式",
	"RoundTripDelay":"循环延迟",
	"Router":"路由",
	"Rule":"规则",
	"Running":"运行中",
	"Russia":"俄罗斯",
	"Russian":"俄语(Россия)",
	"SIP Config":"SIP 配置",
	"SIP INFO":"SIP INFO",
	"SIP Notify":"SIP通知",
	"SIP":"SIP",
	"SIPServerType":"SIP服务器类型",
	"SIP_Qos (0~63)":"SIP Qos（0~63）",
	"SIP_Qos can not be empty.":"SIP Qos不可为空！",
	"SIP_Reg_Retry_Timer SIP_RegRT_Scope seconds":"SIP注册重试时间（0~1800秒）",
	"SIP_Reg_Retry_Timer should be a number !!":"SIP重注册时间须为数字！",
	"SIP_Send_Line":"SIP携带账号信息",
	"SIP_Send_MAC":"SIP携带MAC信息",
	"SIP_Session_Timer seconds T1":"SIP会话定时器 T1（0.5~10秒)",
	"SIP_Session_Timer seconds T2":"SIP会话定时器 T2（2~40秒）",
	"SIP_Session_Timer seconds T4":"SIP会话定时器 T4（2.5~60秒）",
	"SIP_Session_Timer":"SIP会话定时器",
	"SMS":"短信息",
	"SMS_message":"发送内容",
	"SMS_target_number":"发送号码",
	"SNMP":"SNMP",
	"SRTP Auth-tag":"SRTP认证标签",
	"SRemoteName":"来电/去电号码匹配",
	"SRemoteNameFlashTime(seconds)":"更新时间间隔（秒）",
	"STUN Port":"STUN端口(1024~65000)",
	"STUN":"STUN",
	"STUNPort should be a number !!":"STUN端口须为数字！",
	"STUN_Server":"STUN服务器",
	"SWAP":"切换",
	"Sat":"星期六",
	"Saturday":"星期六",
	"SaveCallHistory":"保存呼叫记录",
	"Search Source List In Dialing":"去电联系人匹配列表",
	"Second In Month":"第2周",
	"Second":"秒",
	"Secondary DNS error, please check":"备选DNS错误，请核对！",
	"Secondary DNS":"备选DNS",
	"Secondary Server":"备选服务器",
	"Security":"安全",
	"Select and Upgrade Firmware":"升级固件",
	"Selected Softkeys (ordered by position)**":"已选择软键\n按位置排序",
	"SemiAttendTrans":"转接连接界面",
	"SemiAttendTransBack":"转接回铃界面",
	"Semi_Attend_Trans_OnHook":"挂机咨询转",
	"Send Anonymous Code":"发送匿名呼叫代码",
	"Send Anonymous Rejection Code":"发送匿名拒接代码",  
	"Send Anonymous":"匿名呼叫",
	"Send Sound":"发送按键音",
	"Send":"发送",
	"SendPoundKey":"发送#键",
	"Sep":"九月",
	"September":"九月",
	"Server Certs":"服务器证书",
	"Server Expires":"心跳报文",
	"Server Host":"服务器地址",
	"Server Name":"服务器地址",
	"Server RetryCounts":"重试次数",
	"Server URL":"服务器地址",
	"Server":"服务器",
	"Server_Address":"服务器地址",
	"SessionExpires seconds":"会话心跳（30~7200秒）",
	"SessionRefresher":"会话刷新者",
	"Setting":"设置",
	"Settings":"设置",
	"SetupCompleted":"启动完成",
	"Shared_Line":"线路共享",
	"Show Title":"显示标题",
	"Signal Encode Key":"信号编码密钥",
	"Silence":"静音",
	"Silent.wav":"静音.wav",
	"Sip Server 1":"SIP服务器 1",
	"Sip Server 2":"SIP服务器 2",
	"SoftKey1":"软键 1",
	"SoftKey2":"软键 2",
	"SoftKey3":"软键 3",
	"SoftKey4":"软键 4",
	"Softkey Layout":"软键设置",
	"Software_Version":"软件版本",
	"Spain":"西班牙",
	"Spanish":"西班牙语(Español)",
	"Speed Dial":"速拨",
	"Splash.wav":"Splash.wav",
	"Split":"拆分",
	"Start Date":"开始日期",
	"Start Hour of Day":"日起始时间",
	"Start IP Address":"开始IP地址",
	"Start Time":"开始时间",
	"Start":"开始",
	"Static DNS":"静态 DNS",
	"Static IP Address":"静态IP地址",
	"Static IP":"静态IP",
	"Status":"状态",
	"Stop Time":"停止时间",
	"Stop":"停止",
	"Stopped":"停止",
	"Stutter":"语音留言提示音",
	"Sub_MWI":"语音订阅",
	"Sub_Period seconds":"订阅周期",
	"Subnet mask address is invalid":"无效子网掩码！",
	"Subnet_Mask":"子网掩码",
	"SubscribeMWIToVM":"语音信息订阅",
	"SubscribeRegister":"注册订阅",
	"Subscription Period should be a number !!":"订阅周期须为数字！",
	"Success:Delete user factory config OK!":"成功：成功删除用户出厂配置！",
	"Success:Import your factory config OK!":"成功：成功导入出厂配置！",
	"Sun":"星期日",
	"Sunday":"星期日",
	"Suppress DTMF Display Delay":"抑制DTMF显示延迟",
	"Suppress DTMF Display":"抑制DTMF显示",
	"Sweden":"瑞典",
	"Switch Account Down":"向下切换账号",
	"Switch Account Up":"向上切换账号",
	"Switch Account":"切换账号",
	"Switch":"切换账号",
	"Switzerland":"瑞士",
	"SymmOneWayDelay":"对称单项延迟",
	"System logo":"系统徽标",
	"System ringtone can not be removed!!":"系统铃声不能删除！",
	"System wallpaper can not be removed!!":"系统壁纸不能删除！",
	"SystemlogLevel":"SYSLOG等级",
	"TCP":"TCP",
	"TLS":"TLS",
	"TLS_SIPs_Port":"TLS SIP 端口",
	"TR069":"TR069",
	"TR069:":"TR069",
	"TRAN":"转接",
	"Talk":"通话界面",
	"Talk/Dial Power Light On":"通话、拨号时开启电源灯",
	"Talking, Please wait...":"通话中,请稍后...",
	"Talking, please save config later.":"通话中，请稍候保存配置！",
	"Target":"目标号码",
	"Telephone-Event":"电话事件",
	"Terminated":"结束",
	"Text_Logo":"文件徽标",
	"Tftp_Server":"Tftp服务器",
	"The Block Out Number should not contain other characters except \"digital number, *, [, ']', '-', ',', '.', 'x',')','('\"":"限制号码只能输入\“数字, *, [, ']', '-', ',', '.', 'x',')','('\”",
	"The Max Length must not be less than Min Length":"最大长度须大于最小长度！",
	"The SMS is empty !":"文本信息为空！",
	"The Secondary DNS is same as Primary DNS, please enter again":"备选DNS与首选DNS重复，请重新输入！",
	"The TimeOffset value should be from -300 to +300!":"时间偏移量为：-300~+300！",
	"The build-in photo cannot be removed":"内置相片不可删除！",
	"The cert file has existed!":"证书已存在！",
	"The cert file has prefabricated!":"已预制的证书文件!",
	"The configuration information is not complete!":"配置信息不完整!",
	"The count of DHCP Option's values can't more than 5!":"DHCP Option值须小于5！",
	"The file already exited!!":"文件已存在！",
	"The file already exits!":"文件已存在！",
	"The file format must be .csv!":"文件格式须为：.csv！",
	"The file format must be .dob!":"文件格式须为：.dob！",
	"The file format must be .pem , .crt , .cer or .der !":"文件格式须为：.pem, .crt, .cer, .der！",
	"The file format must be .pem , .crt , .cer or .der!":"文件格式须为：.pem, .crt, .cer, .der！",
	"The file format must be .pem or .cer!":"文件格式须为：.pem，.cer！",
	"The file format must be .pem!":"文件格式须为：.pem！",
	"The file format must be .rom!":"文件格式须为：.rom！",
	"The file format must be .tar!":"文件格式须为：.tar！",
	"The file format must be .xml!":"文件格式须为：.xml!",
	"The file is too large!":"文件太大!",
	"The file is too large,please less than 5M!":"文件太大，需要小于5M!",
	"The file name is too long!":"文件名称太长！",
	"The file name is too long!":"文件名过长！",
	"The http port of webserver is invalid number!":"无效HTTP端口！",
	"The https port of webserver is invalid number!":"无效HTTPS端口！",
	"The maximum length of the SMS is 200 characters!":"文本信息最长200字符！",
	"The operation is done!":"操作完成！",
	"The original contact will be covered, continue?":"原有联系人将被覆盖，是否继续？",
	"The password have invalid value!":"密码含无效字符！",
	"The size is too big!":"尺寸太大！",
	"The username can not be empty.":"用户名不可为空！",
	"The username or password is error!":"用户名或密码错误！",
	"There is no such groups":"群组不存在！",
	"Third In Month":"第3周",
	"This firmware don't support tr069!":"此固件版本不支持TR069！",
	"Thu":"星期四",
	"ThursDay":"星期四",
	"Thursday":"星期四",
	"Time Zone":"时区",
	"Time":"时间",
	"Time&Date":"日期时间",
	"Time&Date:":"时间 & 日期",
	"Time_Format":"时间格式",
	"Time_Out_Dial_Now_Rule":"即时呼出延迟",
	"Tones":"信号音",
	"Tran Send DTMF":"DTMF透传",
	"Transfer on Conference Hang up":"会议挂机转接",
	"Transfer":"通话转接",
	"Transfer:":"通话转接",
	"TransferCall":"转接呼叫",
	"TransferFailed":"转接失败",
	"TransferFinished":"转接完成",
	"TransferModeViaDsskey":"可编程按键触发转接",
	"Transport":"传输方式",
	"Trusted Certs":"可信任证书",
	"Tue":"星期二",
	"Tuesday":"星期二",
	"Turkish":"土耳其语(Türkçe)",
	"TurstedAddr":"受信任IP地址",
	"Two or more records have been chosen!":"两项以上条目被选中！",
	"Type can not be \"BLF List\" when autoBlflist is on!":"自动BLF List后，不能配置为BLF List！",
	"Type can not be \"UC Favourite\" when AutoFavorite is on!":"当开启AutoFavorite时类型不能为 \"UC Favourite\" !",
	"Type":"类型",
	"UC Active":"启用UC功能",
	"UC Favourite":"UC收藏夹",
	"UC Password":"UC密码",
	"UC Username":"UC用户名",
	"UCAP":"UCAP",
	"UCServer":"UC服务器",
	"UDP":"UDP",
	"UDP_Keep_alive_Interval should be a number !!":"UDP续活间隔须为数字！",
	"URL record":"URL录音",
	"URL":"URL",
	"USRPRIORITY":"优先级",
	"Uac":"UAC",
	"Uas":"UAS",
	"UnConnected":"不连接",
	"UnHold":"取消保持",
	"UnMute":"取消静音",
	"United States":"美国",
	"Unknown":"未知",
	"UnregisterOnReboot(*)":"重启注销",
	"Unregistered":"未注册",
	"Unselected Softkeys":"未选择软键",
	"UnusedBackLight":"背光灯闲置时亮度",
	"Up":"向上",
	"Update Interval  seconds":"同步周期（15~86400秒）",
	"Upgrade":"升级",
	"Upload Logo":"导入徽标",
	"Upload Photo":"上传相片",
	"Upload VPN Config":"上传VPN配置",
	"Upload Wallpaper":"加载壁纸",
	"Upload Wallpaper(480*272)":"加载墙纸（480*272）",
	"Upload cert file error!":"上传证书文件错误！",
	"Upload failed!":"加载失败！",
	"Upload success!":"加载成功！",
	"Upload":"上传",
	"Upload_Period":"Upload Period",
	"Use Logo":"使用徽标",
	"Use Outbound Proxy In Dialog":"会话中使用Outbound代理",
	"Use_Headset":"使用耳机",
	"Use_Headset_Group":"使用耳机群组和免提",
	"Use_Speaker":"使用免提",
	"User ID":"用户名称",
	"User Name":"用户名称",
	"User Type":"用户类型",
	"User":"用户名",
	"UserName":"用户名称",
	"Username":"用户名",
	"VAD":"语音激活检测",
	"VID (1-4094)":"VID（1~4094）",
	"VLAN":"VLAN",
	"VQ RTCP-XR Collector address":"VQ RTCP-XR监控服务器地址",
	"VQ RTCP-XR Collector name":"VQ RTCP-XR监控服务器名字",
	"VQ RTCP-XR Collector port":"VQ RTCP-XR监控服务器端口",
	"VQ RTCP-XR Interval Report":"VQ RTCP-XR报告周期",
	"VQ RTCP-XR Session Report":"VQ RTCP-XR会议报告",
	"Value shouldn't be empty !":"值域不可为空！",
	"Value":"值",
	"Version":"版本",
	"Version2":"版本 2",
	"Version3":"版本 3",
	"Visual Alert for BLF Pickup":"截答提示窗口",
	"Visual Alert for Parked Call":"驻留提示窗口",
	"Voice Mail Display":"显示语音邮件",
	"Voice Mail Tone":"语音信息音",
	"Voice Mail":"语音留言",
	"Voice Monitoring":"声音监测",
	"Voice":"语音",
	"Voice/Text Mail Power Light Flash":"有语音、文本信息时电源灯闪烁",
	"VoiceEncryptType":"语音加密",
	"Voice_Mail":"语音信息",
	"Voice_QoS (0~63)":"语音QoS（0~63）",
	"Voice_QoS can not be empty.":"Voice Qos不可为空！",
	"Voice_QoS":"语音QoS",
	"WAN IP address is invalid":"无效WAN IP地址！",
	"WAN IPv6 address is invalid":"无效IPv6地址！",
	"WAN Port Link":"WAN接口连接",
	"WAN_IP_Address":"IP地址",
	"WAN_Port":"WAN接口",
	"WAN_Port_Link":"WAN端口连接",
	"WAN_Port_Type":"WAN口类型",
	"WWW DD MMM":"WWW DD MMM",
	"WWW MMM DD":"WWW MMM DD",
	"WaitTime":"等待时间(1~100秒)",
	"Wallpaper":"壁纸",
	"Warming threshold for Delay":"延迟升温阈值",
	"Warming threshold for Moslq":"MOS-LQ升温阈值",
	"Warning,AccountNATUDPUpdateTime could not be empty!":"警告：NAT继续包刷新时间不能为空！",
	"Warning,the character '&' could not be contain!":"警告：& 为非法字符！",
	"Warning: Group already exist!":"警告：群组已存在！",
	"Warning: Some settings you changed take effect when you restart your machine! do you want to reboot now?":"警告：配置已变更，需重启后才生效。\n是否立即重启？",
	"Warning: The Phone must be reboot to make BroadsoftActive take effect,do you want to reboot now?":"警告：需要重启话机以使用Broadsoft功能生效。\n是否立即重启？",
	"Warning: The Phone must be reboot to make UC Active take effect,do you want to reboot now?":"警告:需要重启话机以使用UC功能生效。\n是否立即重启？ ",
	"Warning:Same port!":"警告：端口重复！",
	"WatchDog":"看门狗",
	"WebServer":"网页访问类型",
	"Wed":"星期三",
	"Wednesday":"星期三",
	"Weekly":"逐周",
	"XML Browser":"XML浏览",
	"XML Group":"XML群组",
	"XML Phonebook":"XML联系人",
	"XSI Port should be between 1 and 65535!!":"XSI服务器端口有效范围为：1~65535!",
	"XSI":"XSI",
	"XSI:":"XSI",
	"XSIServerType":"XSI服务器类型",
	"YY/MM/DD":"YY/MM/DD",
	"YYYY-MM-DD":"YYYY-MM-DD",
	"Year":"年",
	"You can choose 5 customers at most!!!":"最多选择5个客户！",
	"You can click here to get more guides.":"您可以通过点击这里获得更多帮助!",
	"You have changed the password!":"密码已改变!",
	"You have changed the password":"密码已改变",
	"You should input at least one sip server address!!":"请至少配置1个SIP服务器！",
	"ZeroActive":"一键更新启用",
	"account":"账号",
	"Please select a correct file(.cfg)":"请选择正确的(.cfg)文件！",
	"account-adv-note":"<b>DTMF有效负荷类型:</b><br>选择DTMF传输的类型.<br><br><br><br><b>NAT穿透：</b><br>选择是否使用STUN服务器去注册.<br><br><br><b>RPort:</b><br>选择是否告诉服务器只对话机使用的地址和端口做出响应.<br><br><br><b>Expire:</b><br>用户自己定义一个向服务器注册的周期.",
	"account-basic-note":"<b>基本设置</b><br>设置账号的语音留言特征码<br>",
	"account-codec-note":"编解码优先权:</b><br>用户可自己选择使用的编解码的优先权,可供选择的编解码包括G.711ULaw,G.711ALaw,<br>G.729,G.723.用户至少要选择一种codec.<br><br>",
	"account-register-note":"<b>显示名称:</b><br>拨打电话时对方话机上显示的本地名字.<br><br><b>用户名称:</b><br>由运营商提供的用户名.<br><br><b>注册账号:</b><br>由运营商提供的注册名.<br><br><b>密码:</b><br>注册账号对应的密码.",
	"action_URI_allow_IP":"允许控制IP列表",
	"admin":"管理员",
	"auth error":"认证错误",
	"auto negotiate":"自适应速率",
	"auto_negotiate":"自适应速率",
	"call failed":"呼叫失败",
	"call success":"呼叫成功",
	"contacts-LDAP-note":"<b>LDAP</b><br>开启LDAP快速搜索联系人功能的设置<br>",
	"contacts-broadsoft-note":"<b>网络联系人</b><br>用于管理员设置网络联系人相关参数.<br>",
	"contacts-callinfo-note":"<b>历史记录</b><br>用于管理员查看历史记录.<br>",
	"contacts-favorite-note":"<b>联系人</b><br>用于管理员设置联系人相关参数.<br>",
	"contacts-multicastIP-note":"<b>组播</b><br>填写所需要接收的组播地址（格式为IP:端口），并配置相应的标签",
	"contacts-preview-note":"联系人预览",
	"contacts-remote-note":"<B>远程地址簿</b><br>该功能允许你从服务器中下载联系人信息，需要在网页中配置电话簿的地址和名字。",
	"contactsbasic-note":" <B>添加联系人</B><br>输入联系人信息，联系人名字不能为空!<br><br><br><b>删除联系人</b><br>选择方格中您要删除的联系人，点击删除按钮进行删除!<br><br><br><b>导入</b><br>以XML格式浏览文件。<br><br><br><b>导出</b><br>点击导出按钮并给导出的文件命名。",
	"data":"数据",
	"default":"默认",
	"default_contact_image.png":"默认联系人图像.png",
	"default_photo":"默认相片",
	"dhcp_hostname":"DHCP设备名称",
	"display_name":"显示名称",
	"download customs, please try latter!":"下载中请稍候重试！",
	"dsskey-ext-note":"<B>按键类型</B><br/>可编程功能键，类型可以为快速拨号，代答，保持，免打扰等。<b>按键事件</B><br/>自定义按键功能.<br/><br/><B>对讲机</B><br/>启用对讲机模式，主要用于办公室快速连接话务员或秘书。<br/><br/>",
	"dsskey-linekey-note":"<B>按键类型</B><br/>可编程功能键，类型可以为快速拨号，代答，保持，免打扰等。<b>按键事件</B><br/>自定义按键功能.<br/><br/><B>对讲机</B><br/>启用对讲机模式，主要用于办公室快速连接话务员或秘书。<br/><br/>",
	"dsskey-memorykey-note":"<B>按键类型</B><br/>可编程功能键，类型可以为快速拨号，代答，保持，免打扰等。<b>按键事件</B><br/>自定义按键功能.<br/><br/><B>对讲机</B><br/>启用对讲机模式，主要用于办公室快速连接话务员或秘书。<br/><br/>",
	"dsskey-programkey-note":"<B>按键类型</B><br/>可编程功能键，类型可以为快速拨号，代答，保持，免打扰等。<b>按键事件</B><br/>自定义按键功能.<br/><br/><B>对讲机</B><br/>启用对讲机模式，主要用于办公室快速连接话务员或秘书。<br/><br/>",
	"elect_Country":"选择国家",
	"encryption(SRTP)":"RTP加密模式",
	"favorite":"名片夾",
	"features-acd-note":"<b>呼叫中心</b><br>用于管理员设置呼叫中心相关参数.<br>",
	"features-actionurl-note":"<b>Action URL</b><br>设置ActionURL功能,开启该功能后,话机所执行动作会发送到相应的服务器端<br>",
	"features-audio-note":"<b>声音</b><br>用于管理员进行设置声音相关参数.<br>",
	"features-bluetooth-note":"<b>蓝牙</b><br><br>",
	"features-callpickup-note":"<b>截答</b><br>用于管理员设置截答相关参数.<br>",
	"features-forward-note":"<b>无条件前转:</b><br>把所有的电话都转接到设置的电话号码上.<br><br><b>无应答前转:</b><br>如果没有应答就把电话转接到设置的电话号码上.<br><br><b>遇忙前转:</b><br>如果正在通话中就把电话转接到设置的电话.",
	"features-general-note":"<B>呼叫等待</B><br>此功能允许你在通话中接收另一路新来电！<br><br><B>自动应答</B><br>自动接听来电。<br><br><B>发送键</B><br>设置*或#作为发送键。<br><br><B>热线号码</B><br>当你拿起话机手柄或免提模式下，话机将会自动呼出该号码。",
	"features-intercom-note":"<b>对讲机</b><br>用于管理员设置对讲机相关参数.<br>",
	"features-notification-popups-note":"<b>弹出通知窗口</b><br>用于管理员设置弹出通知窗口参数.<br>",
	"features-phonelock-note":"<b>键盘锁</b><br>用于管理员设置键盘锁相关参数.<br>",
	"features-power-led-note":"<b>电源灯</b><br>用于管理员设置电源灯相关参数.<br>",
	"features-remotecontrl-note":"<B>远程控制簿</b><br>用于管理员设置远程控制挂机相关参数",
	"features-sms-note":"<b>发送号码:</b><br>填写要发送短消息的目标号码.",
	"features-transfer-note":"<b>呼叫转移</b><br>用于管理员设置呼转相关参数.<br>",
	"float":"悬浮",
	"forward should disable when Lock&Answer":"键盘锁定后禁止来电前转操作！",
	"full duplex,100Mbpss":"100M全双工速率",
	"full duplex,10Mbps":"10M全双工速率",
	"full_duplex_1000Mbps":"1000M全双工速率",
	"full_duplex_100Mbps":"100M全双工速率",
	"full_duplex_10Mbps":"10M全双工速率",
	"g_arrayNoticeInfo//[2]":"g_arrayNoticeInfo",
	"group_id_name":"群组名称",
	"half duplex,100Mbps":"100M半双工速率",
	"half duplex,10Mbps":"10M半双工速率",
	"half_duplex_100Mbps":"100M半双工速率",
	"half_duplex_10Mbps":"10M半双工速率",
	"hang up failed":"挂断失败",
	"hangup failed":"结束通话失败！",
	"hangup success":"结束通话成功！",
	"hidden-note":"隐藏页面",
	"iLBC":"iLBC",
	"iLBC_15_2 and iLBC_13_3  can not be applied simultaneously":"iLBC 15.2和iLBC 13.3不可同时使用！",
	"icon_blacklist_b.png":"icon_blacklist_b.png",
	"icon_family_b.png":"icon_family_b.png",
	"icon_friend_b.png":"icon_friend_b.png",
	"ignore":"忽略",
	"index_id":"序号",
	"info":"特殊信息",
	"innerHtml":"innerHtml",
	"jumpto":"跳转到",
	"ldap":"LDAP",
	"ldap+StartTLS":"LDAP 开始加密传输",
	"ldaps":"LDAPs",
	"line":"线路",
	"lock":"锁定",
	"memory":"记忆键",
	"mobile_number":"移动电话",
	"network-adv-note":"<b>网络高级设置</b><br>用于管理员设置网络相关的高级参数",
	"network-note":"<b>自动获得IP地址:</b><br>话机自动向DHCP服务器请求获得IP地址,子网掩码,网关,DNS等.<br><br><br><b>静态IP地址:</b><br>手动配置IP地址,子网掩码,网关,DNS等.<br><br><br><b>xDSL(PPPoE):</b><br>这是DSL提供的最常用的设置,要求输入ISP提供的用户名和密码.",
	"network-pcport-note":"<b>PC口</b><br>用于管理员设置PC口相关参数.<br><br>",
	"num":"号码",
	"office_number":"办公电话",
	"other_number":"其它电话",
	"pcport_active":"PC接口激活",
	"photo_data":"版本数据",
	"precondition":"预处理",
	"proxy require can not contain ! and &":"! 和 & 为非法字符！",
	"retransmition":"临时响应的可靠传输",
	"ring":"铃声",
	"seconds":" (秒)",
	"security-note":"<b>口令类型:</b><br>用户选择登陆的权限,管理员权限可以修改用户的密码和自己的密码,但是用户权限只能修改自己的密码",
	"server-cert-note":"<b>服务证书</b><br>服务证书列表.<br>",
	"settings-autop-note":"<b>自动部署</b><br>用于管理员设置自动部署相关参数<br>",
	"settings-calldisplay-note":"<b>来电显示</b><br>用于管理员设置来电显示相关参数.<br>",
	"settings-config-note":"<b>配置</b><br>用于管理员设置话机配置相关参数.<br>",
	"settings-datetime-note":"<b>时区:</b><br>选择您所在的时区.<br><br><b>服务器:</b><br>设置获取时间的服务器.<br><br><b>更新时间间隔:</b><br>设置到服务器校对本机时间的间隔,默认值是1000秒",
	"settings-dialplan-note":"<b>替换规则:</b><br>用户可以自定义规则,使号码的字符或者字符串被替换成别的字符或字符串.比如把0替换成0086，那当用户拨0的时候实际拨出的号码是0086。<br>注意：在替换时，通过加括号将查找的内容存储起来，使用$1,$2….$9来对应获取查找的内容(括号的顺序为序号)。<br><br><b>立即拨出规则:</b><br>用户可以自定义规则,凡是满足规则的号码都将被立即拨出去,而不需要按发送键.比如设置为xxx,那按了任意三个数字都将被视为电话号码被送出.<br><br><b>最小/大长度:</b><br>本地号码最小/大长度.<br><br><b>账号:</b><br>用户可以自定义账号,凡是在该账号下添加的拨号规则,用该账号将会生效,其他账号下不生效,例如填写1,则只有账号1生效,可以填写多个账号,如1,2,3,用逗号隔开",
	"settings-preference-note":"<b>语言:</b><br>选择网页显示语言.<br><br><b>铃声:</b><br>设置话机响铃铃声.<br><br><b>自定义铃声:</b><br>上传自定义铃声，并作为响铃铃声",
	"settings-ring-note":"<b>区别振铃</b><br>用于管理员设置区别振铃相关参数.<br>",
	"settings-sip-note":"<b>SIP</b><br>用于管理员设置SIP相关参数.<br>",
	"settings-softkey-note":"<b>自定义可编程键</b><br>用于管理员设置自定义可编程按键<br>",
	"settings-tones-note":"<b>选择国家</b><br>选择您所在的国家。在自定义模式下，您可以手动配置信号音的值 ，格式为element = [!]freq[+freq2][/duration]<br><br>",
	"settings-tr069-note":"<b>TR069</b><br>用于管理员设置TR069功能相关参数.<br>",
	"settings-upgrade-note":"<b>恢复出厂设置:</b><br>这将使所有设置重置为出厂默认值,您的所有设置将被删除.<br><br><b>升级固件 </b><br>选择供应商发布的最新版本的固件升级.",
	"settings-voice-note":"<b>声音</b><br>用于管理员设置声音相关参数.<br>",
	"Please select a correct file(.cfg)":"请选择一个正确的文件(.cfg)",
	"settings-voicemonitoring-note":"语音监听",
	"sip server port should be a number !!":"SIP服务器端口须为数字！",
	"span to pc port":"透传到PC端口",
	"span to pc":"透传到PC",
	"status-note":"<b>版本号:</b><br>显示设备当前的固件版本号.<br><br><br><b>网络配置:</b><br>显示Internet口和PC口的网络情况.<br><br><br><b>账号:</b><br>显示注册的SIP账号的状态和SIP服务器.",
	"text":"文本",
	"title_802_1_x":"802.1x",
	"title_LLDP":"LLDP",
	"trusted-cert-note":"<b>受信任证书</b><br>受信任证书列表.<br>",
	"upgrade:fail":"升级：失败",
	"user":"用户名",
	"var":"var",
	"vpn":"VPN",
	"zero sp touch":"一键更新",
	"Are you sure to reset the local configuration?":"确定要重置本地配置",
	"Accept SIP Trust Server Only":"只支持SIP信任服务器",
	"Auto Linekeys":"自动配置帐号",
	"Type can not be \"Line\" when AutoLinekeys is on!":"Type can not be \"Line\" when AutoLinekeys is on!",
	"Day":"Day",
	"Error: The max replace rule count is ":"Error: The max replace rule count is",

	"Proxy Fallback Interval is invalid!":"Proxy Fallback Interval is invalid!",
	"Bridge ID":"Bridge ID",
	"Reset local configurations?":"Reset local configurations?",



	"Advice of Charge":"Advice of Charge",
	"AOC Display Time":"AOC Display Time",
	"Shared Call Appearance":"Shared Call Appearance",
	"Enable auto answer tone":"启用自动应答提示音",
	"Delay must more than 20 !":"Delay must more than 20 !",
	"Open Call Waiting":"开启呼叫等待",
	"Close Call Waiting":"关闭呼叫等待",
	"Outbound Proxy Server 1":"Outboundd代理服务器1",
	"Outbound Proxy Server 2":"Outboundd代理服务器2",
	"Forward Emergency":"呼叫转移紧急号码",
	"Forward Authorized Numbers":"呼叫转移鉴权号码",
	"Headset":"使用耳麦",
	"Handfree":"使用免提",
	"Cancel Call Out":"取消呼出",
	"Remote Busy":"Remote Busy",
	"Call Remote Canceled":"Call Remote Canceled",
	"Proxy Fallback Interval":"代理回退间隔",
	"Attempt Expired Time(s)":"获取配置文件超时时间(秒)",
	"Warning threshold for Moslq":"通话质量警戒值",
	"Warning threshold for Delay":"通话时延警戒值",
