"call Number Filter":"呼叫號碼過濾",
    " Distinctive Ring Tones":"區別振鈴",
    " Do you want to reboot ?":"是否重啟話機？",
    "10min":"10分鐘",
    "1min":"1分鐘",
    "2min":"2分鐘",
    "30min":"30分鐘",
    "404 (Not found)":"404 (未找到)",
    "480 (Temporarily not available)":"480 (臨時不可用)",
    "486 (Busy here)":"486 (正在忙)",
    "5min":"5分鐘",
    "603 (Decline)":"603 (拒接)",
    "ACD Auto Available Timer(0~120s)":"ACD自動啟動定時器（0~120s）",
    "ACD Auto Available":"ACD自動啟動",
    "ACD Trace":"ACD追踪",
    "ACD":"ACD",
    "ACD:":"ACD",
    "ACD_SubscripPeriod(120~3600s)":"ACD訂閱週期（120~3600秒）",
    "ACS Password":"ACS密碼",
    "ACS URL":"ACS服務器地址",
    "ACS Username":"ACS用戶名",
    "AES-32":"AES-32",
    "AES-80":"AES-80",
    "AES-80&&AES-32":"AES-80&&AES-32",
    "AUTO+SIP INFO":"AUTO or SIP INFO",
    "Account":"帳號",
    "Account1":"帳號 1",
    "Account10":"帳號 10",
    "Account11":"帳號 11",
    "Account12":"帳號 12",
    "Account13":"帳號 13",
    "Account14":"帳號 14",
    "Account15":"帳號 15",
    "Account16":"帳號 16",
    "Account2":"帳號 2",
    "Account3":"帳號 3",
    "Account4":"帳號 4",
    "Account5":"帳號 5",
    "Account6​​":"帳號 6",
    "Account7":"帳號 7",
    "Account8":"帳號 8",
    "Account9":"帳號 9",
    "AccountStatus":"帳號狀態",
    "AccountStatusId":"帳號狀態",
    "Action URL":"Action URL",
    "Active Backlight Level":"背光燈啟動時亮度",
    "Active":"啟動",
    "Adaptive":"自適應",
    "Add":"添加",
    "Advanced":"高級",
    "After_ring_times scope2":"響鈴時間（秒）",
    "All Cert":"全部證書",
    "All Contacts":"本機連絡人",
    "All Keys":"所有鍵",
    "All_Configuration":"所有配置",
    "Allow IP Call":"允許IP呼叫",
    "Allow SIP Authentication for XSI":"允許SIP XSI認證",
    "Allow Trans Exist Call":"允許轉移已有呼叫",
    "AllowIntercom":"啟用對講機",
    "AllowMute":"允許靜音",
    "AlwaysOff":"恒滅",
    "AlwaysOn":"恒亮",
    "Always_forward_to":"無條件轉移",
    "And the browser must not be closed or refreshed!":"並且瀏覽器不可關閉或刷新頁面！",
    "AnonymousCall OffCode can not contain ! and &":"! 和& 為非法字符！",
    "AnonymousCall OnCode can not contain ! and &":"! 和& 為非法字符！",
    "AnonymousReject OffCode can not contain ! and &":"! 和& 為非法字符！",
    "AnonymousReject OnCode can not contain ! and &":"! 和& 為非法字符！",
    "Anonymous_Call":"匿名特徵碼",
    "Anonymous_Call_Rejection":"匿名呼叫拒絕",
    "Answer By Hand":"摘手柄应答",
    "Answer":"應答",
    "AnswerNewInCall":"接聽新來電",
    "Answer_call_only":"僅接聽",
    "Append_Delete":"Append Delete",
    "Append_Limit_Mode":"Append Limit Mode",
    "Append_Limit_Size":"Append Limit Size",
    "Append_Stop":"Append Stop",
    "Apr":"四月",
    "April":"四月",
    "Are you sure delete user-defined factory config?":"是否刪除自定義出廠配置？",
    "Are you sure to delete the chosen photo?":"確定刪除選中的相片？",
    "Are you sure to remove the ringtone??":"確定要刪除鈴聲？",
    "Are you sure to remove the wallpaper??":"確定要刪除桌布？",
    "Are you sure to set a blank password?":"確定設定一個空白的密碼嗎?",
    "Area Code":"區域代碼",
    "As Bridge":"橋接模式",
    "As Router":"路由模式",
    "AsSend":"送號鍵",
    "Ask customers downloading status failed!!":"查詢客戶下載狀態失敗！",
    "Attended Tranfer":"諮詢轉",
    "Attended Transfer":"諮詢轉",
    "Audio Alert for BLF Pickup":"截答提示音",
    "Audio Alert for Parked Call":"駐留提示音",
    "Audio Settings:":"聲音配置",
    "Audio codecs":"語音編解碼",
    "Audio":"聲音",
    "Aug":"八月",
    "August":"八月",
    "Australia":"澳大利亞",
    "Austria":"奧地利",
    "Auto Provision":"自動更新",
    "Auto":"自動",
    "Auto-negotiation":"自適應速率",
    "AutoAnswer":"自動應答",
    "AutoAnswerDelay":"自動接聽延遲",
    "AutoRedial":"自動重撥",
    "AutoRedialInterval (1~300s)":"自動重撥間隔（1~300秒）",
    "AutoRedialInterval should be a number !!":"自動重撥間隔需為數字！",
    "AutoRedialTimes (1~300)":"自動重撥次數（1~300）",
    "AutoRedialTimes should be a number !!":"自動重撥次數需為數字！",
    "Auto_answer":"自動應答提示音",
    "Automatic":"自動",
    "AutopFinish":"自動更新完成！",
    "Autoprovision Now":"立即更新",
    "Autoprovision":"自動更新",
    "BLA_Number":"共享線路號碼",
    "BLA_Subscription_Period":"共享線路訂閱週期",
    "BLF LED Mode":"BLF指示燈模式",
    "BLF List Retrieve call parked Code":"BLF List 取回截答碼",
    "BLF List":"BLF List",
    "BLF":"BLF",
    "BLFList_URL":"BLF List URI",
    "BackLightTime":"背光燈時間",
    "BackLightTime(seconds)":"背光燈啟動時間（秒）",
    "Base":"基礎",
    "Basic":"基礎",
    "Begin time can't be later than end time!":"開始時間需早於結束時間！",
    "Belgium":"比利時",
    "Blacklist":"黑名單",
    "BlfListBargeInCode":"BLF List 插入會話特徵碼",
    "BlfList_Code":"BLF List截答特徵碼",
    "Blind Transfer OnHook":"挂機盲轉",
    "Blind Transfer":"盲轉",
    "Block Out":"限制呼出",
    "Block XML In Calling":"通話中阻止XML推送",
    "BlockOut Number":"阻止號碼",
    "Bluetooth Active":"藍牙啟動",
    "Bluetooth Settings:":"藍牙設定",
    "Bluetooth":"藍牙",
    "Brazil":"巴西",
    "Bridge":"橋接模式",
    "BroadSoft Buddies":"網絡好友",
    "Broadsoft Directory":"網絡連絡人",
    "Broadsoft":"網絡",
    "BroadsoftActive":"Broadsoft功能啟動",
    "Broadsoft_SCA":"網絡線路共享",
    "Browser":"瀏覽",
    "Buddies":"好友",
    "Busy To Idle":"通話進入閒置",
    "Busy":"忙音",
    "BusyToneDelay scope2":"忙音時長（秒）",
    "Busy_forward_to":"遇忙轉移",
    "Button Sound":"按鍵音",
    "CA_Certificate":"CA證書",
    "CA_Certificates":"CA證書",
    "CDP":"CDP",
    "CIDSource":"來電顯示域",
    "CM Key":"CM鍵",
    "CNG":"舒適噪音",
    "CONF":"會議",
    "Call Display":"來電顯示",
    "Call Information Display Method":"呼叫顯示方式",
    "Call Panel":"呼叫面板",
    "Call Park Code":"駐留特徵碼",
    "Call Park Mode":"駐留方​​式",
    "Call Park":"呼叫駐留",
    "Call Park:":"呼叫駐留",
    "Call Pickup":"呼叫截答",
    "Call Pickup:":"呼叫截答",
    "Call Pull Feature access code":"拉回通話特徵碼",
    "Call Return":"回撥",
    "Call States":"呼叫狀態",
    "Call Waiting Tone":"呼叫等待音",
    "CallCompletion":"呼叫完成",
    "CallFailed":"呼叫失敗界面",
    "CallIn":"來電界面",
    "CallList_Show_Num":"呼叫列表顯示號碼",
    "CallLog":"呼叫記錄",
    "CallWaiting":"呼叫等待",
    "CallWaitingOffCode":"呼叫等待禁用特徵碼",
    "CallWaitingOnCode":"呼叫等待啟用特徵碼",
    "Call_List":"呼叫列表",
    "Call_Waiting":"呼叫等待提示音",
    "Callog:":"呼叫記錄",
    "Can't move to same group!":"不能移動到相同組！",
    "Cancel":"取消",
    "Chile":"智利",
    "China":"中國",
    "Chinese_S":"簡體中文(Chinese Simplified)",
    "Chinese_T":"繁體中文(Chinese Traditional)",
    "ChoiceSRTP":"選擇SRTP",
    "Close Always Forward":"關閉無條件前轉",
    "Close Busy Forward":"關閉遇忙前轉",
    "Close DND":"關閉免打擾",
    "Close NoAnswer Forward":"關閉無應答前轉",
    "Close Power Light":"關閉電源指示燈",
    "Code":"區號",
    "Codec":"編解碼",
    "Common AES Key":"AES密鑰",
    "Common Power Light On":"預設電源指示燈",
    "Common":"自動",
    "Common_Name_Validation":"用戶名確認",
    "Company":"公司",
    "Compulsory":"強制加密",
    "Conference":"會議",
    "Conference_Type":"會議類型",
    "Conference_URI":"會議 URI",
    "Conferenced":"會議界面",
    "Configuration updating ...":"配置更新中...",
    "Configuration updating, please wait!":"配置更新中，請稍等！",
    "Configuration":"配置管理",
    "Confirm Password":"確認密碼",
    "Confirm":"提交",
    "Congestion":"網絡擁塞提示音",
    "Connected":"已連接",
    "Connecting":"連接界面",
    "ConnectionRequestPassword":"請求連接密碼",
    "ConnectionRequestUsername":"請求連接用戶名",
    "Contacts":"連絡人",
    "Content shouldn't be empty !":"內容不能為空！",
    "Contrast":"對比度",
    "CosmoCom":"CosmoCom",
    "Critical threshold for Delay":"延遲臨界閾值",
    "Critical threshold for Moslq":"MOS-LQ臨界閾值",
    "Current Time":"當前時間",
    "Custom Button":"自定義按鍵",
    "Custom Cert":"自定義證書",
    "Custom Directories:":"定制通訊錄：",
    "Custom Option":"自定義選項",
    "Custom SoftKey":"自定義軟鍵",
    "Custom logo":"自定義徽標",
    "Custom":"自定義",
    "CustomFactoryConfig":"自定義出廠配置",
    "Czech ETSI":"捷克ETSI",
    "Czech":"捷克",
    "DD MMM YYYY":"DD MMM YYYY",
    "DD-MMM-YY":"DD-MMM-YY",
    "DD/MM/YY":"DD/MM/YY",
    "DD/MM/YYYY":"DD/MM/YYYY",
    "DHCP Active":"DHCP啟動",
    "DHCP Option Value":"DHCP選項值",
    "DHCP VLAN":"DHCP VLAN",
    "DHCP":"DHCP",
    "DHCPTime":"DHCP時間",
    "DHCP_Server_Status":"DHCP服務器狀態",
    "DND St​​atus":"免打擾狀態",
    "DND":"免打擾",
    "DND:":"免打擾",
    "DNDActive":"免打擾功能啟動",
    "DNDEmergency":"緊急號碼",
    "DND_Authorized_Numbers":"免打擾鑑權號碼",
    "DND_Off_Code":"免打擾關閉特徵碼",
    "DND_On_Code":"免打擾開啟特徵碼",
    "DNS-NAPTR":"DNS-NAPTR",
    "DPickup":"指定截​​答",
    "DST Start Day of Week Last in M​​onth":"月起始星期",
    "DST Start Day of Week":"星期幾開始",
    "DST Start Month":"開始月份",
    "DST Stop Day of Week Last in M​​onth":"月結束星期",
    "DST Stop Day of Week":"結束星期",
    "DST Stop Month":"結果月份",
    "DST_ByDate":"日期方式",
    "DST_ByWeek":"周方式",
    "DTMF":"DTMF",
    "DTMF-Relay":"DTMF延遲",
    "DTMFRepetition":"DTMF重發",
    "DTMFReplaceTran":"DTMF透明替代",
    "DTMF_Info_Type":"DTMF內容類型",
    "DTMF_Payload seconds(96~255s)":"DTMF負載（96~127）",
    "DTMF_Type":"DTMF類型",
    "Date":"日期",
    "Date_Format":"日期格式",
    "Day of week":"週幾",
    "Day":"日",
    "Daylight Saving Time":"夏令時",
    "Dec":"十二月",
    "December":"十二月",
    "Default Cert":"預設證書",
    "Default Gateway":"網關地址",
    "Default":"預設",
    "Del":"刪除",
    "DelOldcontact":"刪除原有連絡人",
    "Delay must less than 300 !":"最大延遲需小於300！",
    "Delay must more than 60 !":"最小延遲需大於60！",
    "Delete All":"全部刪除",
    "Delete Photo":"刪除相片",
    "Delete server certs error!":"刪除服務器證書錯誤！",
    "Delete":"刪除",
    "Denmark":"丹麥",
    "Deutsch":"德國",
    "Device_Certificate":"設備證書",
    "Device_Certificates":"設備證書",
    "Device_Type":"連接類型",
    "Dia_Number":"呼叫號碼",
    "Dial Plan":"撥號規則",
    "Dial":"撥號音",
    "Dial-now Rule should not be empty!":"即時呼出規則不可為空！",
    "Dial-now Rule":"即時撥號規則",
    "Dial-now":"立即呼出",
    "Dial_recall":"回撥提示音",
    "Dialed_List":"撥號列表",
    "Dialing":"撥號界面",
    "DialogInfo_Call_Pickup":"Dialog-Info截答方式",
    "Direct Call Pickup Code":"指定截​​答特徵碼",
    "Direct Call Pickup":"指定截​​答",
    "Direct Pickup":"指定截​​答",
    "Directories":"連絡人",
    "Directory":"連絡人",
    "Directotries:":"通訊錄",
    "Disable codecs":"禁用編解碼",
    "Disable":"禁用",
    "Disabled":"禁用",
    "Disp Code":"處置碼",
    "Display Called Party Information":"顯示被叫方訊息",
    "Display Contact Photo":"顯示連絡人頭像",
    "Display Forward Call Popup":"顯示轉移來電彈窗",
    "Display Method on Dialing":"撥號顯示方式",
    "Display Missed Call Popup":"顯示未接來電彈窗",
    "Display Name":"顯示名稱",
    "Display Report opt​​ions on Web":"在網頁顯示報告選項",
    "Display Report opt​​ions on phone":"在話機顯示報告選項",
    "Display Text Message Popup":"顯示文本訊息彈窗",
    "Display Voice Mail Popup":"顯示語言留言彈窗",
    "Diversion/History-Info":"轉移/歷史訊息",
    "Do not support bridge in PPPoE mode!":"PPPoE模式不支持橋接模式！",
    "Do not support vlan in PPPoE mode!":"PPPoE模式下不支持VLAN！",
    "Do you want to autoprovision now?":"是否立即執行自動更新？",
    "Do you want to delete all contacts in BlackList?":"確定要清空黑名單？",
    "Do you want to delete all contacts in ContactList?":"確定要清空連絡人？",
    "Do you want to discard your changes??":"是否放棄修改？",
    "Do you want to discard your changes??":"是否放棄變更？",
    "Do you want to import the configuration file to All_Configuration":"導入所有配置文件?",
    "Do you want to import the configuration file to Local_Configuration":"導入本機配置文件?",
    "Do you want to move the contacts to ":"是否移動連絡人到",
    "Do you want to reset to factory ?":"是否恢復為出廠配置？",
    "Do you want to restart your machine?":"是否重啟話機？",
    "Down":"向下",
    "Download failed, please try again":"下載失敗，請重試！",
    "Downloading custom list, please try latter!!":"正在下載定制列表，請稍候再試！",
    "Dsskey":"可編程按鍵",
    "Dual Headset":"雙耳機功能",
    "E-Common":"E-Common",
    "EAP-FAST":"EAP-FAST",
    "EAP-MD5":"EAP-MD5",
    "EAP-PEAP/GTC":"EAP-PEAP/GTC",
    "EAP-PEAP/MSCHAPv2":"EAP-PEAP/MSCHAPv2",
    "EAP-TLS":"EAP-TLS",
    "EAP-TTLS/EAP-GTC":"EAP-TTLS/EAP-GTC",
    "EAP-TTLS/EAP-MSCHAPv2":"EAP-TTLS/EAP-MSCHAPv2",
    "ECHO":"迴聲消除",
    "EXP Switch":"切換擴展台",
    "Early Media":"早期媒體",
    "Echo_Cancellation":"迴聲消除",
    "Edit":"編輯",
    "Emergency":"緊急號碼",
    "Empty":"空",
    "Enable AutoFavorite":"自動收藏狀態​​",
    "Enable Custom Directories":"啟用定制通訊錄",
    "Enable DHCP Server":"啟用DHCP服務器",
    "Enable LDAP":"啟用LDAP",
    "Enable Periodic Inform":"啟用周期性通知",
    "Enable Semi-Attend Transfer":"啟用半諮詢轉",
    "Enable Signal Encode":"啟用信號編碼",
    "Enable TR069":"啟用TR069",
    "Enable codecs":"啟用編解碼",
    "Enable":"啟用",
    "EnablePageTips":"啟用提示頁面",
    "EnableSessionTimer":"啟用會話定時器",
    "EnableUserEqualPhone":"發送 user=phone",
    "Enable_Outbound_Proxy_Server":"啟用Outbound代理",
    "Enable_SemiAttend_Transfer":"啟用半諮詢轉",
    "Enabled":"啟用",
    "End Call":"掛斷通話",
    "End Date":"結束日期",
    "End Hour of Day":"日結束時間",
    "End IP Address":"結束IP地址",
    "EndSystemDelay":"結束系統延遲",
    "English":"English(English)",
    "Enter at least 6 characters with 1 number and 1 alphabet min":"輸入至少1位數字和1位字母的6位數密碼！",
    "Enterprise IP phone SIP-T23":"企業IP电话SIP-T23",
    "Enterprise IP phone SIP-T27":"企業IP電話SIP-T27",
    "Enterprise IP phone SIP-T23P":"企業IP电话 SIP-T23P",
    "Enterprise IP phone SIP-T23G":"企業IP电话 SIP-T23G",

    "Enterprise IP phone SIP-T27P":"企業IP电话 SIP-T27P",
    "Enterprise IP phone SIP-T27G":"企業IP电话 SIP-T27G",
    "Gigabit Color IP Phone SIP-T29G":"千兆彩屏IP电话 SIP-T29G",
    "Enterprise IP phone SIP-T42G":"企業IP电话 SIP-T42G",	
    "Enterprise IP phone SIP-T42P":"企業IP电话 SIP-T42P",
    "Enterprise IP phone SIP-T41G":"企業IP电话 SIP-T41G",
    "Enterprise IP phone SIP-T41P":"企業IP电话 SIP-T41P",							
    "Gigabit Color IP Phone SIP-T46G":"千兆彩屏IP电话 SIP-T46G",
    "Enterprise IP phone SIP-T61P":"企業IP电话 SIP-T61P",
    "Enterprise IP phone SIP-T61G":"企業IP电话 SIP-T61G",
    "Enterprise IP phone SIP-T66G":"企業IP电话 SIP-T66G",
    "Enterprise IP phone SIP-T66P":"企業IP电话 SIP-T66P",
    "Enterprise:":"企業",
    "EnterpriseCommon:":"普通企業",
    "Error: Element's name is empty!":"錯誤:名字是空的！",
    "Error: More than 50 groups.":"錯誤：最多為50個群組！",
    "Error: More than 50.":"错误：最多为50个群组.",
    "Error: More than five groups.":"錯誤：最多為5個群組！",
    "Error: Record with the same Prefix already exists!":"錯誤：條目中存在相同的號首！",
    "Error: Record with the same Rule already exists!":"錯誤：存在重複規則！",
    "Error: Same config":"錯誤: 重複訊息！",
    "Error: The max dial-now count is ":"錯誤：最大規則數是",
    "Error: The maximum number of certificates is 10, please delete one before upload":"錯誤：證書最大數量為10，請先刪除後再上傳！",
    "Error: The same record already exists!":"錯誤：存在重複條目！",
    "Error: Write dsskey config error!":"錯誤: dsskey配置寫錯!",
    "Error:Black list is full!":"錯誤：黑名單已滿！",
    "Error:Contact already existed!":"錯誤：連絡人已存在！",
    "Error:Contact is asyncing!":"錯誤：連絡人異步中！",
    "Error:Contact is not black!":"錯誤：連絡人不屬於黑名單！",
    "Error:Contact is not local!":"錯誤：連絡人不是本機的！",
    "Error:Contact list is full!":"錯誤：連絡人列表已滿！",
    "Error:Contact name empty!":"錯誤：連絡人名字為空！",
    "Error:Contact not existed!":"錯誤：連絡人不存在！",
    "Error:Delete ring error!":"錯誤：刪除鈴聲錯誤！",
    "Error:Duplcate contact!":"錯誤：重複連絡人！",
    "Error:Duplicate group!":"錯誤：重複群組！",
    "Error:Export contact file error!":"錯誤：導出連絡人文件錯誤！",
    "Error:File isn't exist!":"錯誤：文件不存在！",
    "Error:File upload error!":"錯誤：文件上傳錯誤！",
    "Error:Group list is full!":"錯誤：群組列表已滿！",
    "Error:Group already existed!":"錯誤：群組已存在！",
    "Error:Group can not delete!":"錯誤：群組不能刪除",
    "Error:Group empty!":"錯誤：群組為空！",
    "Error:Group not existed!":"錯誤：群組不存在！",
    "Error:Import config error!":"錯誤：導入配置錯誤！",
    "Error:Import contact file error!":"錯誤：導入連絡人文件錯誤！",
    "Error:Import local config error!":"錯誤：導入本機配置錯誤！",
    "Error:Invalid file!":"錯誤：無效文件！",
    "Error:Invalid group id!":"錯誤：無效群組ID！",
    "Error:Invalid path!":"錯誤：無效路徑！",
    "Error:Network error!":"錯誤：網絡錯誤！",
    "Error:No contact group!":"錯誤：無連絡人群組！",
    "Error:No default group!":"錯誤：無預設群組！",
    "Error:No space left!":"錯誤：無剩餘空間！",
    "Error:Other error!":"錯誤：其他錯誤！",
    "Error:Photo name error!":"錯誤：照片名字錯誤！",
    "Error:The destination folder does not exist!":"錯誤：目標文件夾不存在！",
    "Error:The password is error!":"錯誤：密碼錯誤！",
    "Error:Too many blacklist!":"錯誤：太多黑名單！",
    "Error:Too many group!":"錯誤：太多群組！",
    "Error:Too many local contact!":"錯誤：太多本機連絡人！",
    "Error:Upload error!":"錯誤：上傳失敗！",
    "Error:User factory config doesn't exist!":"錯誤：用戶出廠配置不存在！",
    "Error:Write remote_phonebook_list.xml error!":"錯誤：寫remote_phonebook_list.xml錯誤！",
    "Error:You don't have enough jurisdiction!":"錯誤：沒有足夠權限！",
    "Established":"建立會話",
    "Exist the ring!":"鈴聲已存在！",
    "Expansion Key":"擴展按鍵",
    "Expansion":"擴展",
    "Expiration":"有效期",
    "Export CFG Configuration File":"導出CFG 配置文件",
    "Export CSV":"CSV格式導出",
    "Export System Log":"導出SYSLOG",
    "Export XML":"XML格式導出",
    "Export":"導出",
    "Export_Import_Config":"導入導出配置",
    "Ext Key":"擴展鍵",
    "Ext":"擴展設備",
    "Extension":"擴展",
    "FAC":"特徵碼",
    "FROM":"來自",
    "Fail : Too many keys !":"失敗：設定鍵過多！",
    "Fail to upload photo ! [Can not compress the picture]":"上傳照片失敗！[不能壓縮圖標]",
    "Fail to upload photo ! [The Resolution of the picture is too large]":"上傳照片失敗！[圖片分辨率太大]",
    "Failed":"失敗",
    "Family":"家庭",
    "Favorite":"連絡人",
    "Favorites":"連絡人",
    "Feature_Key_Synchronisation":"功能同步",
    "Features":"功能",
    "Feb":"二月",
    "February":"二月",
    "File Name is too long!":"文件名過長！",
    "Finland":"芬蘭",
    "Firmware Version":"韌體版本",
    "Firmware of the SIP Phone will be updated. \nIt will take 5 minutes to complete.Please don't power off!":"將在5分鐘後完成。\n請勿斷電！",
    "Firmware of the SIP Phone will be updated.":"話機韌體將升級！",
    "Firmware updating ...":"韌體升級中…",
    "Firmware_Version":"韌體版本",
    "First In Month":"第1週",
    "Fixed Type":"計算方式",
    "Fixed":"靜態",
    "ForbinSRTP":"禁止SRTP",
    "ForceSRTP":"強制SRTP",
    "Forward":"轉移",
    "Forward&DND":"呼叫轉移 & 免打擾",
    "Forward:":"呼叫轉移",
    "ForwardActive":"來電前轉功能啟動",
    "ForwardIncomingCall":"前轉來電",
    "Forwarded_List":"前轉來電記錄",
    "Fourth In Month":"第4週",
    "France":"法國",
    "French":"法語(Français)",
    "Fri":"星期五",
    "Friday":"星期五",
    "Friend":"朋友",
    "Full Contact Info":"完整連絡人訊息",
    "Funckey":"功能鍵",
    "Fwd International":"國際前轉來電",
    "G-Common":"G-Common",
    "G722":"G722",
    "G723_53 and G723_63 can not be applied simultaneously":"G723.53和G723.63不可同時使用！",
    "G723_53":"G723_53",
    "G726-16":"G726-16",
    "G726-24":"G726-24",
    "G726-32":"G726-32",
    "G726-40":"G726-40",
    "G729":"G729",
    "GPark":"群組截答",
    "GPickup":"群組截答",
    "Gateway IP address is invalid":"無效網關！",
    "Gateway IPv6 address is invalid":"無效IPv6網關！",
    "Gateway":"網關地址",
    "General Information":"基本訊息",
    "General_Information":"基本訊息",
    "German":"德語(Deutsch)",
    "Germany":"德國",
    "Get CSVFile data error!":"獲取CSV文件錯誤！!",
    "Great Britain":"大不列顛島",
    "Greece":"希臘",
    "Group Call Park Code":"群組解答特徵碼",
    "Group Call Park":"群組駐留",
    "Group Call Pickup Code":"群組截答特徵碼",
    "Group Call Pickup":"群組截答",
    "Group Listen":"群聽",
    "Group Pickup":"群組截答",
    "Group Setting":"群組設定",
    "Group":"群組",
    "Group:":"群組",
    "GroupCommon:":"普通群組",
    "HOLD":"保持",
    "HTTP Port (1~65535)":"HTTP監聽端口(1~65535)",
    "HTTP":"HTTP",
    "HTTPS Port (1~65535)":"HTTPS監聽端口(1~65535)",
    "HTTPS":"HTTPS",
    "HTTPS_Only":"HTTPS Only",
    "HTTP_HTTPS":"HTTP HTTPS",
    "HTTP_Only":"HTTP Only",
    "Handfree Send Volume (1~53)":"免提發送音量",
    "Handset Send Volume (1~53)":"手柄發送音量",
    "Hang Up":"掛斷",
    "Hangup":"結束通話",
    "Hardware Version":"硬件版本",
    "Hardware_Version":"硬件版本",
    "Headset Prior":"耳機優先",
    "HeadsetSendVolume (1~53)":"耳機發送音量",
    "HeadsetSendVolume(1~53)":"耳機發送音量（1~53）",
    "Held":"被保持界面",
    "Hidden":"隱藏",
    "Hide Feature Access Codes":"隱藏特徵碼",
    "High":"高",
    "History":"呼叫記錄",
    "Hold":"保持",
    "Hold/Held Power Light On":"保留通話時開啟電源指示燈",
    "Host Server":"服務器地址",
    "HotDesking":"移動辦公",
    "HotLine_Number":"熱線號碼",
    "Hoteling":"移動辦公",
    "Hotline Number should be a number or IP address!!":"熱線號碼應該是一個號碼或者IP地址",
    "Hotline_Delay(0~10)":"熱線延遲（0~10秒）",
    "Hour ":"時",
    "Hour":"時",
    "Hour_12":"12小時制",
    "Hour_24":"24小時制",
    "Http":"HTTP",
    "Https":"HTTPS",
    "Hungary":"匈牙利",
    "ICMPv6 Status":"ICMPv6狀態",
    "IME":"輸入法",
    "INBAND":"帶內",
    "IP Direct Auto Answer":"IP直撥自動應答",
    "IP address is invalid":"無效IP地址！",
    "IP_Address":" IP地址",
    "IPv4 & IPv6":"IPv4 & IPv6",
    "IPv4 Config":"IPv4配置",
    "IPv4":"IPv4",
    "IPv6 Config":"IPv6配置",
    "IPv6 Static DNS":"靜態IPv6DNS",
    "IPv6 prefix is​​ invalid":"無效IPv6地址前綴！",
    "IPv6 prefix(0~128)":"IPv6前綴(0~128)",
    "IPv6":"IPv6",
    "Identity":"帳號",
    "Idle To Busy":"閒置進入通話",
    "Import CFG Configuration File":"導入CFG 配置文件",
    "Import CSV":"CSV格式導入",
    "Import Local Contact File":"導入本機連絡人",
    "Import XML":"XML格式導入",
    "Import":"導入",
    "Import_Factory_Config":"導入出廠配置",
    "Import_Server_Certificate":"導入服務器證書",
    "Import_Trusted_Certificate":"導入受信證書",
    "IncomingCall":"來電",
    "Index":"索引",
    "India":"印度 ",
    "Inexistence":"不存在",
    "Info":"特殊訊息",
    "Input contains invalid character like ":"輸入字符包含無效字符，如",
    "Input contains invalid character like '<>'":"無效字符：'<>'",
    "Input contains invalid character like <>'\"\\":"無效字符：<>'\"\\",
    "Install certs failed!":"安裝證書失敗！",
    "Install server certs error!":"安裝服務器證書錯誤！",
    "Inter Digit Time(1~14s)":"自動呼出啟動時間（1~14秒）",
    "InterarrivalJitter":"間隔抖動",
    "Intercom":"對講機",
    "Intercom:":"對講機",
    "IntercomBarge":"對講介入",
    "IntercomMute":"對講機靜音",
    "IntercomTone":"對講提示音",
    "Internal_Ringer_File":"內置鈴聲文件",
    "Internal_Ringer_Text":"內置鈴聲名稱",
    "Internet Port":"WAN接口",
    "Interval_min":"間隔（分鐘）",
    "Invaid Emergency should only contain digital number and ','":"緊急號碼有效字符為：數字和\",\"",
    "Invaid File Name!":"無效文件名！",
    "Invaid File Type!":"無效文件類型！",
    "Invail value.":"無效值！",
    "Invaild BroadsoftXSIHostAddr":"無效XSI服務器地址！",
    "Invaild Primary NTP Server":"無效首選NTP服務器！",
    "Invaild Secondary NTP Server":"無效備選NTP服務器！",
    "Invalid Custom Option!":"無效自定義選項！",
    "Invalid DHCP option!":"無效DHCP選項！",
    "Invalid DTMF payload !":"無效DTMF負載！",
    "Invalid Day!":"無效日期！",
    "Invalid Max RTP Port !":"無效最大RTP端口！",
    "Invalid Min RTP Port !":"無效最小RTP端口！",
    "Invalid Number":"無效號碼",
    "Invalid SNMP Port !":"無效SNMP端口！",
    "Invalid SNMP Trused address !":"無效SNMP服務器地址！",
    "Invalid SipQos":"無效SIP QoS！",
    "Invalid String":"無效字符串！",
    "Invalid URL!":"無效URL！",
    "Invalid VID":"無效VID！",
    "Invalid VoiceQos":"無效Voice QoS！",
    "Invalid characters. Only digits and commas are allowed!":"無效字符。只能輸入數字和逗號！",
    "Invalid connection request username!":"無效用戶名連接請求！",
    "Invalid daylight saving end day!":"無效夏令時結束時間！",
    "Invalid daylight saving start day!":"無效夏令時開始時間！",
    "Invalid daylight saving start/end time !":"無效夏令時起止時間！",
    "Invalid factory file!":"無效出廠文件！",
    "Invalid file name!":"無效文件名！",
    "Invalid group name!":"無效群組名稱！",
    "Invalid password!":"無效密碼！",
    "Invalid prefix String":"無效號首字符串！",
    "Invalid request password!":"無效密碼請求！",
    "Invalid ring file!":"無效鈴聲文件！",
    "Invalid ringer text string!":"無效字符串！",
    "Invalid server URL!":"無效服務器地址",
    "Invalid syslog server address !":"無效SYSLOG服務器地址！",
    "Invalid username!":"無效用戶名！",
    "Invalid value!":"無效值！",
    "Ip Changed":"IP變更",
    "IsDeal180":"180 Ring工作域",
    "Issued_By":"頒發者",
    "Issued_To":"頒發給",
    "Italian":"意大利語(Italiano)",
    "Italy":"意大利",
    "JITTER_BUFFER":"RTP抖動緩衝區",
    "Jan":"一月",
    "January":"一月",
    "Japan":"日本",
    "Jitter":"抖動",
    "JitterBufferMax":"最大抖動緩衝區",
    "Jul":"七月",
    "July":"七月",
    "Jun":"六月",
    "June":"六月",
    "Keep Alive Interval":"續活間隔",
    "Keep Alive Type":"續活方式",
    "Key":"按鍵",
    "Keyboard_Lock":"鍵盤鎖類型",
    "Keyboard_Lock_Enable":"啟用鍵盤鎖",
    "Keypad Lock":"鍵盤鎖",
    "LAN_IP_Address":"LAN地址",
    "LDAP":"LDAP",
    "LDAPTLSMode":"LDAP加密傳輸模式",
    "LDAP_Display_Name":"LDAP顯示名稱",
    "LDAP_Lookup_For_Callout":"LDAP呼出查詢",
    "LDAP_Lookup_For_Incoming_Call":"LDAP匹配來電",
    "LDAP_Name_Attributes":"LDAP名稱屬性",
    "LDAP_Name_Filter":"LDAP名稱過濾",
    "LDAP_Number_Attributes":"LDAP號碼屬性",
    "LDAP_Number_Filter":"LDAP號碼過濾",
    "LDAP_Sorting_Results":"LDAP搜索排序",
    "LED Off in Idle":"LED閒置關閉",
    "Label Length":"标签长度",
    "Label":"標籤",
    "Language":"語言",
    "Last In Month":"最後1週",
    "Left":"向左",
    "Line 1":"帳號 1",
    "Line 10":"帳號 10",
    "Line 11":"帳號 11",
    "Line 12":"帳號 12",
    "Line 13":"帳號 13",
    "Line 14":"帳號 14",
    "Line 15":"帳號 15",
    "Line 16":"帳號 16",
    "Line 17":"帳號 17",
    "Line 18":"帳號 18",
    "Line 19":"帳號 19",
    "Line 2":"帳號 2",
    "Line 20":"帳號 20",
    "Line 21":"帳號 21",
    "Line 22":"帳號 22",
    "Line 3":"帳號 3",
    "Line 4":"帳號 4",
    "Line 5":"帳號 5",
    "Line 6":"帳號 6",
    "Line 7":"帳號 7",
    "Line 8":"帳號 8",
    "Line 9":"帳號 9",
    "Line Active":"线路啟動",
    "Line Key":"帳號键",
    "Line Key1-5":"帳號键 1-5",
    "Line Key1-7":"帳號键 1-7",
    "Line Key1-9":"帳號键 1-9",
    "Line Key10-18":"帳號键 10-18",
    "Line Key11-15":"帳號键 11-15",
    "Line Key15-21":"帳號键 15-21",
    "Line Key19-27":"帳號键 19-27",
    "Line Key6-10":"帳號键 6-10",
    "Line Key8-14":"帳號鍵 8-14",
    "Line Selection":"帳號選擇",
    "Line":"線路",
    "Link_Status":"連接狀態",
    "Listening_Address":"監聽地址",
    "Lithuania":"立陶宛",
    "Live Dialpad":"自動呼出",
    "Load Fail":"加載失敗",
    "Load Failed":"加載失敗",
    "Load Ringtone":"加載鈴聲",
    "Load_server_cer_file":"加載服務器證書文件",
    "Load_trusted_cer_file":"加載受信證書文件",
    "Loading, please waiting":"加載中，請稍候！",
    "Loading, please waiting...":"加載中，請稍候！",
    "Local Anonymous Rejection":"本機匿名拒接",
    "Local Anonymous":"本機匿名",
    "Local Codec":"本機編解碼",
    "Local Contacts":"本機連絡人",
    "Local Directory":"本機連絡人",
    "Local Group":"本機群組",
    "Local History":"本機呼叫記錄",
    "Local IP":"本機IP",
    "Local Phonebook":"本機連絡人",
    "Local Port":"本機端口",
    "Local SIP Port should be a number !!":"本機SIP端口需為數字！",
    "Local User":"本機用戶",
    "Local codec":"本機編解碼",
    "Local user":"本機用戶",
    "Local":"本機",
    "Local_Conf":"本機會議",
    "Local_Configuration":"本機配置",
    "Local_Identity":"本機帳號",
    "Local_RTP_Port":"本機RTP端口",
    "Local_SIP_Port":"本機SIP端口",
    "Location":"Location",
    "Lock":"鎖定",
    "LogOff":"未註冊",
    "LogOn":"註冊成功",
    "Log_Out":"註銷",
    "Login address":"登錄地址",
    "Login":"登入",
    "Logon Wizard":"註冊嚮導",
    "Low":"低",
    "MAC-Oriented AES Key":"指定MAC的AES密鑰",
    "MAC_Address":"物理地址",
    "MD5_Password":"MD5密鑰",
    "MM/DD/YY":"MM/DD/YY",
    "MOS-CQ":"MOS-CQ",
    "MOS-LQ":"MOS-LQ",
    "MUTE":"靜音",
    "MWI_Subscription_Period WSP_Scope seconds":"語音訂閱週期（秒）",
    "Manager":"管理",
    "Manual_Time":"手動設定時間",
    "Mar":"三月",
    "March":"三月",
    "Max Delay is less than Min Delay !":"最大延遲需大於最小延遲！",
    "Max Length (1-15)":"最大長度（1~15）",
    "Max RTP Port is less than Min RTP Port !":"最大RTP端口要大於最小RTP端口！",
    "Max.Hits(1~32000)":"Max. Hits (1~32000)",
    "MaxRtpPort (1~65535)":"最大本機RTP端口（1~65535）",
    "Max_Delay":"最大延遲",
    "May":"五月",
    "Meet-Me Conference":"Meet-Me會議",
    "Memory Key":"記憶鍵",
    "Menu":"菜單",
    "Menukey":"菜單鍵",
    "Message":"訊息提示音",
    "Mexico":"墨西哥",
    "Min Length (1-15)":"最小長度（1~15）",
    "MinRtpPort (1~65535)":"最小本機RTP端口（1~65535）",
    "Min_Delay":"最小延遲",
    "Minute":"分鐘",
    "MissCallLog":"未接來電記錄",
    "Missed Call":"未接來電",
    "Missed_List":"未接來電記錄",
    "Mobile Number":"移動電話",
    "Mode":"模式",
    "Mode(IPv4/IPv6)":"IPv4/IPv6",
    "Mode_802_1_x":"802.1x 模式",
    "Mon":"星期一",
    "Monday":"星期一",
    "Month":"月",
    "Move To":"移動到",
    "Multicast Listening":"組播監聽",
    "MulticastCodec":"多播編解碼",
    "MulticastIP":"多播地址",
    "MusicServerURI":"媒體服務器URI",
    "Mute Power Light On":"靜音時開啟電源指示燈",
    "Mute":"靜音",
    "My Status":"我的狀態",
    "N/A":"空",
    "NAT":"NAT",
    "NAT_Traversal":"NAT穿透",
    "NOTE":"說明",
    "NTP By DHCP Priority":"NTP由DHCP優先",
    "Name cannot be empty !":"姓名不能為空！",
    "Name":"姓名 ",
    "Name+Number":"名字+號碼",
    "Netherlands":"荷蘭",
    "Network CallLog":"網絡呼叫記錄",
    "Network Callog":"網絡呼叫記錄",
    "Network Common":"網絡通用參數",
    "Network Directories":"網絡連絡人",
    "Network Directory":"網絡連絡人",
    "Network Favorite":"网络联系人",
    "Network Favourite":"網絡收藏夾",
    "Network Group":"網絡群組",
    "Network":"網絡配置",
    "Network:":"網絡配置",
    "NetworkPacketLossRate":"網絡丟包率",
    "Network_Conf":"網絡會議",
    "New Call":"新呼叫",
    "New Password":"新密碼",
    "New SMS":"新訊息",
    "New Zealand":"新西蘭",
    "New password is similar to username, are you sure to set it?":"新密碼跟用戶名相同, 確定要設定?",
    "New password is too simple, are you sure to set it?":"密碼太簡單了,確定要設定?",
    "NewCall":"新呼叫",
    "Next":"後頁",
    "No Account":"無帳號",
    "No data to import":"無導入數據！",
    "No expansion module connected! Please connect one or more units then refresh this page.":"未連接擴展台。\n請先連接擴展台！",
    "No space left!":"No space left!",
    "No_answer_forward_to":"無應答轉移",
    "Nominal":"常態延遲",
    "None":"無",
    "Normal Delay is beyond scope !":"常態延遲應該在有效範圍內！",
    "Norway":"挪威",
    "Not Found : ":"未找到：",
    "Notification Popups":"彈出通知窗口",
    "Notify":"通知",
    "Nov":"十一月",
    "November":"十一月",
    "Number Only!!":"只支持號碼！",
    "Number of line key":"帳號鍵數量",
    "Number":"電話號碼",
    "Number+Name":"號碼+名稱",
    "OK":"OK",
    "Oct":"十月",
    "October":"十月",
    "Off Code could not be empty when On Code is set!":"On Code設定後，Off Code不可為空！",
    "Off Code":"關閉特徵碼",
    "Off hook":"放下手柄",
    "Off":"關",
    "Off_Code":"關閉特徵碼",
    "Office Num":"辦公電話",
    "Office Number":"辦公電話",
    "Offset(minutes)":"偏移（分鐘）",
    "Old Password":"當前密碼",
    "Old group name is empty!":"原群組名為空！",
    "On Code":"開啟特徵碼",
    "On hook":"拿起手柄",
    "On":"開",
    "OnTalk":"通話界面",
    "On_Code":"開啟特徵碼",
    "Only_Accept_Trusted_Certificates":"只允許受信任證書",
    "Open Always Forward":"開啟無條件前轉",
    "Open Busy Forward":"開啟遇忙前轉",
    "Open DND":"開啟免打擾",
    "Open NoAnswer Forward":"開啟無應答前轉",
    "Operating, Please Wait ...":"操作中，請稍候...",
    "Option":"選項",
    "Optional":"可選加密",
    "Options":"選項",
    "Other Num":"其它電話",
    "Other Number":"其它電話",
    "Out Dialog BLF(*)":"RFC3856實現BLF",
    "OutboundPort should be a number !!":"Outbound端口需為數字！",
    "Outbound_Proxy_Server":"Outbound代理服務器",
    "Outgoing call":"去電",
    "Outgoing_Identity":"呼出帳號",
    "PAI":"PAI",
    "PAI-FROM":"PAI-FROM",
    "PAI-RPID-FROM":"PAI-RPID-FROM",
    "PC Port Link":"PC接口連接",
    "PC Port":"PC接口",
    "PCMA":"PCMA",
    "PCMU":"PCMU",
    "PC_Port":"PC接口",
    "PC_Port_Active":"PC接口啟動",
    "PC_Port_Config":"PC接口配置",
    "PC_Port_Link":"PC端口連接",
    "PEAP-MSCHAPV2":"PEAP-MSCHAPV2",
    "PNP Active":"PNP啟動",
    "PPPoE":"PPPoE",
    "PSWDialLength Invalid!":"無效密碼長度！",
    "PTT":"前綴",
    "PTime(ms)":"打包時長（毫秒）",
    "Packet_Interval (1~3600s)":"發包間隔（1~3600秒）",
    "Packets lost":"丟包",
    "Page":"頁",
    "Paging Address":"組播地址",
    "Paging List":"組播列表",
    "Paging":"廣播",
    "Paging_Barge":"尋呼介入",
    "Paging_Priority_Active":"尋呼優先級",
    "Park Retrieve Code":"駐留取回特徵碼",
    "Park":"截答",
    "Parse Fail":"解析錯誤",
    "Password is similar to username, are you sure to set it?":"密碼和用戶名類似，確定設定？",
    "Password is too simple, are you sure to set it?":"密碼過於簡單，確定設定？",
    "Password":"密碼",
    "Passwords don't match!":"密碼不匹配！",
    "Pcap Feature":"抓包功能",
    "Period for Interval Report":"通知時間週期",
    "Periodic Inform Interval (seconds)":"週期性通知間隔（秒）",
    "Permission denied!":"權限不足!",
    "Personal:":"私有",
    "Phone Call Info":"呼叫歷史",
    "Phone Lock Time Out(0~3600s)":"上鎖延遲（0~3600秒）",
    "Phone Lock":"鍵盤鎖",
    "Phone":"話機",
    "Phone-Unlock PIN(0~15 digital)":"解鎖密碼（0~15位數字）",
    "PhoneSetting:":"話機設定",
    "Photo name already existed!":"相片名稱已存在！",
    "Photo":"相片",
    "Play Local DTMF Tone":"本機撥號DTMF音",
    "PlayHoldTone":"通話保持音",
    "PlayHoldToneDelay should be a number !!":"保持音播放延遲需為數字！",
    "PlayHoldToneDelay":"通話保持音延遲",
    "Please choose at least one record!":"請選擇最少1個條目！",
    "Please choose the DisplayName":"請選擇顯示名稱！",
    "Please click Confirm to load custom directories.":"請點擊確認鍵開始加載定制通訊錄！",
    "Please enable a codec at least.":"請至少配置1種編解碼！",
    "Please input complete information!":"請輸入完整訊息！",
    "Please select a .bin format file at first!":"請先選擇.bin格式的文件！",
    "Please select a .cfg format file at first!":"首先請選擇.cfg格式的文件！",
    "Please select a .png or .jpg or .bmp format file at first!":"文件格式需為：.png, .jpg, .bmp。",
    "Please select a .wav format file at first!":"請先上傳.wav格式的鈴聲文件！",
    "Please select a correct file(.bin)":"請選擇正確的.bin格式文件！",
    "Please select a file":"請選擇1個文件！",
    "Please select a group!":"請選擇1個群組！",
    "Please select one cert at least.":"請至少選擇一個證書。",
    "Please select one record at least.":"請至少選擇1項記錄。",
    "Please select the contacts list file":"請選擇連絡人清單！",
    "Please select the record which you want to edit":"請選擇要修改的條目！",
    "Please specify the Target number":"請指定接收號碼！",
    "Please specify the blockout number!":"請指定限制號碼！",
    "Please upload VPN config file first!":"請先上傳VPN配置文件！",
    "Please wait and do not power off!":"請等待並保持電源連接！",
    "Polish":"波蘭語(Polski)",
    "Port (0~65535)":"端口（1~65535）",
    "Port":"端口",
    "Port_Link":"端口連接",
    "Portugal":"葡萄牙",
    "Portuguese":"葡萄牙語(Português)",
    "Post_Append":"Post Append",
    "Post_Mode":"输出模式",
    "Post_Stor":"Post Stor",
    "Power LED":"電源燈",
    "Power LED:":"電源燈",
    "Power On":"上電啟動",
    "PreTrans":"轉移界面",
    "Preference":"基本設定",
    "Prefix and Replace should not be Empty !":"號首與替換不可為空！",
    "Prefix":"前綴",
    "Prev":"前頁",
    "Preview":"預覽",
    "Prewiew":"預覽",
    "PriHold":"私有保持",
    "Primary DNS error, please check":"首選DNS錯誤，請核對！",
    "Primary DNS":"首選DNS",
    "Primary Server":"首選服務器",
    "Priority":"優先級",
    "Private Hold":"私有保持",
    "Programable Key":"可編程功能鍵",
    "Protocol":"協議版本",
    "Proxy_Require":"代理請求",
    "PswDial":"密碼呼叫",
    "PswLength":"密碼長度",
    "PswPrefix":"密碼呼叫前綴",
    "Push XML failed!!":"推送XML失敗！",
    "Push XML sucessed":"推送XML成功！",
    "Push XML":"推送 XML",
    "PushXML Test":"推送XML測試",
    "PushXML_ServerIP":"XML推送服務器地址",
    "RC4":"RC4",
    "RFC 2543 Hold":"RFC 2543保持模式",
    "RFC2833":"RFC2833",
    "RPID-FROM":"RPID-FROM",
    "RPID-PAI-FROM":"RPID-PAI-FROM",
    "RPort":"RPort",
    "RTP Status":"RTP狀態",
    "ReDialTone":"撥號音恢復",
    "ReDialtone number should be a number !!":"二次撥號音需為數字！",
    "ReLogOffTime(1~1000min)":"登入超時（1~1000分鐘）",
    "Reboot In Talking":"通話中允許重啟",
    "Reboot":"重啟",
    "Rebooting , please wait ...":"重啟中, 請稍候...",
    "Received_List":"已接來電記錄",
    "Recent Call In Dialing":"去電匹配近期呼叫",
    "Record":"錄音提示音",
    "RedirectActive":"重定向功能啟動",
    "Refresh":"刷新",
    "Reg_Surge_Prev (0~60s)":"隨機註冊（0~60秒）",
    "Reg_Surge_Prev":"隨機註冊",
    "Register Failed":"註冊失敗",
    "Register Name":"註冊名稱",
    "Register Status":"註冊狀態",
    "Register":"註冊",
    "RegisterFailed":"註冊失敗",
    "Registered":"已註冊",
    "Registering":"正在註冊...",
    "Reject":"拒絕",
    "RejectIncomingCall":"拒絕來電",
    "Remote Codec":"遠端編解碼",
    "Remote Control":"遠程控制",
    "Remote IP":"遠端IP",
    "Remote Phone Book":"遠程地址簿",
    "Remote Phonebook":"遠程地址簿",
    "Remote Port":"遠端端口",
    "Remote User":"遠端用戶",
    "Remote codec":"遠端編解碼",
    "Remote control:":"遠程控制",
    "Remote user":"遠端用戶",
    "RemoteURL":"遠程URL",
    "Repeatly":"重複週期",
    "Replace All":"全部替換",
    "Replace Part":"部分替換",
    "Replace Rule Type":"替換規則類型",
    "Replace Rule":"替換規則",
    "Replace":"替換",
    "Report opt​​ions on phone UI":"話機的報告選項",
    "ReportIP":"報告IP",
    "Request failed!!":"請求失敗！",
    "Reserve # in User Name":"保留#送號",
    "Reserved Character in User Name":"在用戶名保留字符",
    "Reset Local Config":"重置本機配置",
    "Reset Local Config":"重置本機配置",
    "Reset Local Configuration":"重置本機配置",
    "Reset to Default":"恢復預設值",
    "Reset to Factory Setting":"恢復出廠配置",
    "Reset to default":"恢復預設值",
    "Reset":"恢復出廠配置",
    "Resetting , please wait ...":"重置中, 請稍候...",
    "Resume":"恢復",
    "Retrieve Park":"取回駐留",
    "Retrieve":"取回",
    "Return_Code_DND":"免打擾返回碼",
    "Return_Code_Refuse":"拒接返回碼",
    "Right":"向右",
    "Ring Power Light Flash":"響鈴時電源燈閃爍",
    "Ring Tone":"鈴聲",
    "Ring":"鈴聲",
    "Ring1.wav":"Ring1.wav",
    "Ring2.wav":"Ring2.wav",
    "Ring3.wav":"Ring3.wav",
    "Ring4.wav":"Ring4.wav",
    "Ring5.wav":"Ring5.wav",
    "Ring6.wav":"Ring6.wav",
    "Ring7.wav":"Ring7.wav",
    "Ring8.wav":"Ring8.wav",
    "RingBack":"回鈴界面",
    "Ring_Type":"鈴聲類型",
    "Ring_back":"回鈴音",
    "Ringer_Device_for_Headset":"耳機振鈴方式",
    "RoundTripDelay":"循環延遲",
    "Router":"路由",
    "Rule":"規則",
    "Running":"運行中",
    "Russia":"俄羅斯",
    "Russian":"俄語(Россия)",
    "SIP Config":"SIP 配置",
    "SIP INFO":"SIP INFO",
    "SIP Notify":"SIP通知",
    "SIP":"SIP",
    "SIPServerType":"SIP服務器類型",
    "SIP_Qos (0~63)":"SIP Qos（0~63）",
    "SIP_Qos can not be empty.":"SIP Qos不可為空！",
    "SIP_Reg_Retry_Timer SIP_RegRT_Scope seconds":"SIP註冊重試時間（0~1800秒）",
    "SIP_Reg_Retry_Timer should be a number !!":"SIP重註冊時間需為數字！",
    "SIP_Send_Line":"SIP攜帶帳號訊息",
    "SIP_Send_MAC":"SIP攜帶MAC訊息",
    "SIP_Session_Timer seconds T1":"SIP會話定時器T1（0.5~10秒)",
    "SIP_Session_Timer seconds T2":"SIP會話定時器T2（2~40秒）",
    "SIP_Session_Timer seconds T4":"SIP會話定時器T4（2.5~60秒）",
    "SIP_Session_Timer":"SIP會話定時器",
    "SMS":"文本訊息",
    "SMS_message":"發送內容",
    "SMS_target_number":"發送號碼",
    "SNMP":"SNMP",
    "SRTP Auth-tag":"SRTP認證標籤",
    "SRemoteName":"來電號碼匹配",
    "SRemoteNameFlashTime(seconds)":"更新時間間隔（秒）",
    "STUN Port":"STUN端口(1024~65000)",
    "STUN":"STUN",
    "STUNPort should be a number !!":"STUN端口需為數字！",
    "STUN_Server":"STUN服務器",
    "SWAP":"切換",
    "Sat":"星期六",
    "Saturday":"星期六",
    "SaveCallHistory":"保存呼叫記錄",
    "Search Source List In Dialing":"去電連絡人匹配列表",
    "Second In Month":"第2週",
    "Second":"秒",
    "Secondary DNS error, please check":"備選DNS錯誤，請核對！",
    "Secondary DNS":"備選DNS",
    "Secondary Server":"備選服務器",
    "Security":"安全",
    "Select and Upgrade Firmware":"升級韌體",
    "Selected Softkeys (ordered by position)**":"已選擇軟鍵\n按位置排序",
    "SemiAttendTrans":"轉接連接界面",
    "SemiAttendTransBack":"轉接回鈴界面",
    "Semi_Attend_Trans_OnHook":"挂機諮詢轉",
    "Send Anonymous Code":"發送匿名呼叫代碼",
    "Send Anonymous Rejection Code":"發送匿名拒接代碼",
    "Send Anonymous":"匿名呼叫",
    "Send Sound":"發送按鍵音",
    "Send":"發送",
    "SendPoundKey":"發送#鍵",
    "Sep":"九月",
    "September":"九月",
    "Server Certs":"服務器證書",
    "Server Expires":"心跳報文​​",
    "Server Host":"服務器地址",
    "Server Name":"服務器地址",
    "Server RetryCounts":"重試次數",
    "Server URL":"服務器地址",
    "Server":"服務器",
    "Server_Address":"服務器地址",
    "SessionExpires seconds":"會話心跳（30~7200秒）",
    "SessionRefresher":"會話刷新者",
    "Setting":"設定",
    "Settings":"設定",
    "SetupCompleted":"啟動完成",
    "Shared_Line":"線路共享",
    "Show Title":"顯示標題",
    "Signal Encode Key":"信號編碼密鑰",
    "Silence":"靜音",
    "Silent.wav":"靜音.wav",
    "Sip Server 1":"SIP服務器 1",
    "Sip Server 2":"SIP服務器 2",
    "SoftKey1":"軟鍵 1",
    "SoftKey2":"軟鍵 2",
    "SoftKey3":"軟鍵 3",
    "SoftKey4":"軟鍵 4",
    "Softkey Layout":"軟鍵設定",
    "Software_Version":"軟件版本",
    "Spain":"西班牙",
    "Spanish":"西班牙語(Español)",
    "Speed​​ Dial":"速撥",
    "Split":"拆分",
    "Start Date":"開始日期",
    "Start Hour of Day":"日起始時間",
    "Start IP Address":"開始IP地址",
    "Start Time":"開始時間",
    "Start":"開始",
    "Static DNS":"靜態 DNS",
    "Static IP Address":"靜態IP地址",
    "Static IP":"靜態IP",
    "Status":"狀態",
    "Stop Time":"停止時間",
    "Stop":"停止",
    "Stopped":"停止",
    "Stutter":"語音留言提示音",
    "Sub_MWI":"語音訂閱",
    "Sub_Period seconds":"訂閱週期",
    "Subnet mask address is invalid":"無效子網掩碼！",
    "Subnet_Mask":"子網掩碼",
    "SubscribeMWIToVM":"語音訊息訂閱",
    "SubscribeRegister":"註冊訂閱",
    "Subscription Period should be a number !!":"訂閱週期需為數字！",
    "Success:Delete user factory config OK!":"成功：成功刪除用戶出廠配置！",
    "Success:Import your factory config OK!":"成功：成功導入出廠配置！",
    "Sun":"星期日",
    "Sunday":"星期日",
    "Suppress DTMF Display Delay":"抑制DTMF顯示延遲",
    "Suppress DTMF Display":"抑制DTMF顯示",
    "Sweden":"瑞典",
    "Switch Account Down":"向下切換帳號",
    "Switch Account Up":"向上切換帳號",
    "Switch Account":"切換帳號",
    "Switch":"切換帳號",
    "Switzerland":"瑞士",
    "SymmOneWayDelay":"對稱單項延遲",
    "System logo":"系統徽標",
    "System ringtone can not be removed!!":"系統鈴聲不能刪除！",
    "System wallpaper can not be removed!!":"系統桌布不能刪除！",
    "SystemlogLevel":"SYSLOG等級",
    "TCP":"TCP",
    "TLS":"TLS",
    "TLS_SIPs_Port":"TLS SIP 端口",
    "TR069":"TR069",
    "TR069:":"語音留言",
    "TRAN":"轉接",
    "Talk":"通話界面",
    "Talk/Dial Power Light On":"通話、撥號時開啟電源燈",
    "Talking, Please wait...":"通話中,請稍後...",
    "Talking, please save config later.":"通話中，請稍候保存配置！",
    "Target":"目標號碼",
    "Telephone-Event":"電話事件",
    "Terminated":"結束",
    "Text_Logo":"文件徽標",
    "Tftp_Server":"Tftp服务器",
    "The Block Out Number should not contain other characters except \"digital number, *, [, ']', '-', ',', '.', 'x',')','('\"" :"限制號碼只能輸入\“數字, *, [, ']', '-', ',', '.', 'x',')','('\”",
    "The Max Length must not be less than Min Length":"最大長度需大於最小長度！",
    "The SMS is empty !":"文本訊息為空！",
    "The Secondary DNS is same as Primary DNS, please enter again":"備選DNS與首選DNS重複，請重新輸入！",
    "The TimeOffset value should be from -300 to +300!":"時間偏移量為：-300~+300！",
    "The build-in photo cannot be removed":"內置相片不可刪除！",
    "The cert file has existed!":"證書已存在！",
    "The cert file has prefabricated!":"已预制的证书文件!",
    "The configuration information is not complete!":"配置訊息不完整!",
    "The count of DHCP Option's values​​ can't more than 5!":"DHCP Option值需小於5！",
    "The file already exited!!":"文件已存在！",
    "The file already exits!":"文件已存在！",
    "The file format must be .csv!":"文件格式需為：.csv！",
    "The file format must be .dob!":"文件格式需為：.dob！",
    "The file format must be .pem , .crt , .cer or .der !":"文件格式需為：.pem, .crt, .cer, .der！",
    "The file format must be .pem , .crt , .cer or .der!":"文件格式需為：.pem, .crt, .cer, .der！",
    "The file format must be .pem or .cer!":"文件格式需為：.pem，.cer！",
    "The file format must be .pem!":"文件格式需為：.pem！",
    "The file format must be .rom!":"文件格式需為：.rom！",
    "The file format must be .tar!":"文件格式需為：.tar！",
    "The file format must be .xml!":"文件格式需為：.xml!",
    "The file is too large,please less than 5M!":"文件太大，需要小於5M!",
    "The file name is too long!":"文件名稱太長！",
    "The file name is too long!":"文件名過長！",
    "The http port of webserver is invalid number!":"無效HTTP端口！",
    "The https port of webserver is invalid number!":"無效HTTPS端口！",
    "The maximum length of the SMS is 200 characters!":"文本訊息最長200字符！",
    "The operation is done!":"操作完成！",
    "The original contact will be covered, continue?":"原有連絡人將被覆蓋，是否繼續？",
    "The password have invalid value!":"密碼含無效字符！",
    "The size is too big!":"尺寸太大！",
    "The username can not be empty.":"用戶名不可為空！",
    "The username or password is error!":"用戶名或密碼錯誤！",
    "There is no such groups":"群組不存在！",
    "There is no such groups":"群組不存在！",
    "Third In Month":"第3週",
    "This firmware don't support tr069!":"此韌體版本不支持TR069！",
    "Thu":"星期四",
    "ThursDay":"星期四",
    "Thursday":"星期四",
    "Time Zone":"時區",
    "Time":"時間",
    "Time&Date":"日期時間",
    "Time&Date:":"時間 & 日期",
    "Time_Format":"時間格式",
    "Time_Out_Dial_Now_Rule":"即時呼出延遲",
    "Tones":"信號音",
    "Tran Send DTMF":"DTMF透傳",
    "Transfer on Conference Hang up":"會議挂機轉接",
    "Transfer":"通話轉接",
    "Transfer:":"通話轉接",
    "TransferCall":"轉接呼叫",
    "TransferFailed":"轉接失敗",
    "TransferFinished":"轉接完成",
    "TransferModeViaDsskey":"可編程按鍵觸發轉接",
    "Transport":"傳輸方式",
    "Trusted Certs":"可信任證書",
    "Tue":"星期二",
    "Tuesday":"星期二",
    "Turkish":"土耳其語(Turkish)",
    "TurstedAddr":"受信任IP地址",
    "Two or more records have been chosen!":"兩項以上條目被選中！",
    "Type can not be \"BLF List\" when autoBlflist is on!":"自動BLF List後，不能配置為BLF List！",
    "Type can not be \"UC Favourite\" when AutoFavorite is on!":"当开启AutoFavorite时类型不能为 \"UC Favourite\" !",
    "Type":"類型",
    "UC Active":"啟用UC功能",
    "UC Favourite":"UC收藏夾",
    "UC Password":"UC密碼",
    "UC Username":"UC用戶名",
    "UCAP":"UCAP",
    "UCServer":"UC服務器",
    "UDP":"UDP",
    "UDP_Keep_alive_Interval should be a number !!":"UDP續活間隔需為數字！",
    "URL record":"URL錄音",
    "URL":"服務器地址",
    "USRPRIORITY":"優先級",
    "Uac":"UAC",
    "Uas":"UAS",
    "UnConnected":"不連接",
    "UnHold":"取消保持",
    "UnMute":"取消靜音",
    "United States":"美國",
    "Unknown":"未知",
    "UnregisterOnReboot(*)":"重啟註銷",
    "Unregistered":"未註冊",
    "Unselected Softkeys":"未選擇軟鍵",
    "UnusedBackLight":"背光燈閒置時亮度",
    "Up":"向上",
    "Update Interval seconds":"同步週期（15~86400秒）",
    "Upgrade":"升級",
    "Upload Logo":"導入徽標",
    "Upload Photo":"上傳相片",
    "Upload VPN Config":"上傳VPN配置",
    "Upload Wallpaper":"加載桌布(800*480)",
    "Upload Wallpaper(480*272)":"加载墙纸（480*272）",
    "Upload cert file error!":"上傳證書文件錯誤！",
    "Upload failed!":"加載失敗！",
    "Upload success!":"加載成功！",
    "Upload":"上傳",
    "Upload_Period":"Upload Period",
    "Use Logo":"使用徽標",
    "Use Outbound Proxy In Dialog":"會話中使用Outbound代理",
    "Use_Headset":"使用耳機",
    "Use_Headset_Group":"使用耳機群組和免提",
    "Use_Speaker":"使用免提",
    "User ID":"用戶名稱",
    "User Name":"用戶名稱",
    "User Type":"用戶類型",
    "User":"用戶名",
    "UserName":"用戶名稱",
    "Username":"用戶名",
    "VAD":"語音啟動檢測",
    "VID (1-4094)":"VID（1~4094）",
    "VLAN":"VLAN",
    "VQ RTCP-XR Collector address":"VQ RTCP-XR監控服務器地址",
    "VQ RTCP-XR Collector name":"VQ RTCP-XR監控服務器名字",
    "VQ RTCP-XR Collector port":"VQ RTCP-XR監控服務器端口",
    "VQ RTCP-XR Interval Report":"VQ RTCP-XR報告週期",
    "VQ RTCP-XR Session Report":"VQ RTCP-XR會議報告",
    "Value shouldn't be empty !":"值域不可為空！",
    "Value":"值",
    "Version":"版本",
    "Version2":"版本 2",
    "Version3":"版本 3",
    "Visual Alert for BLF Pickup":"截答提示窗口",
    "Visual Alert for Parked Call":"駐留提示窗口",
    "Voice Mail Display":"顯示語音郵件",
    "Voice Mail Tone":"語音訊息音",
    "Voice Mail":"語音留言",
    "Voice Monitoring":"聲音監測",
    "Voice":"語音",
    "Voice/Text Mail Power Light Flash":"有語言、文本訊息時電源燈閃爍",
    "VoiceEncryptType":"語音加密",
    "Voice_Mail":"語音訊息",
    "Voice_QoS (0~63)":"語音QoS（0~63）",
    "Voice_QoS can not be empty.":"Voice Qos不可為空！",
    "Voice_QoS":"語音QoS",
    "WAN IP address is invalid":"無效WAN IP地址！",
    "WAN IPv6 address is invalid":"無效IPv6地址！",
    "WAN Port Link":"WAN接口連接",
    "WAN_IP_Address":"IP地址",
    "WAN_Port":"WAN接口",
    "WAN_Port_Link":"WAN端口連接",
    "WAN_Port_Type":"WAN口類型",
    "WWW DD MMM":"WWW DD MMM",
    "WWW MMM DD":"WWW MMM DD",
    "WaitTime":"等待時間(1~100秒)",
    "Wallpaper":"桌布",
    "Warming threshold for Delay":"延遲升溫閾值",
    "Warming threshold for Moslq":"MOS-LQ升溫閾值",
    "Warning,AccountNATUDPUpdateTime could not be empty!":"警告：NAT繼續包刷新時間不能為空！",
    "Warning,the character '&' could not be contain!":"警告：& 為非法字符！",
    "Warning: Group already exist!":"警告：群組已存在！",
    "Warning: Some settings you changed take effect when you restart your machine! do you want to reboot now?":"警告：配置已變更，需重啟後才生效。\n是否立即重啟？",
    "Warning: The Phone must be reboot to make BroadsoftActive take effect,do you want to reboot now?":"警告：需要重啟話機以使用Broadsoft功能生效。\n是否立即重啟？",
    "Warning: The Phone must be reboot to make UC Active take effect,do you want to reboot now?":"警告:需要重启话机以使用UC功能生效。\n是否立即重启？ ",
    "Warning:Same port!":"警告：端口重複！",
    "WatchDog":"看門狗",
    "WebServer":"網頁訪問類型",
    "Wed":"星期三",
    "Wednesday":"星期三",
    "Weekly":"逐週",
    "XML Browser":"XML瀏覽",
    "XML Group":"XML群組",
    "XML Phonebook":"XML連絡人",
    "XSI Port should be between 1 and 65535!!":"XSI服務器端口有效範圍為：1~65535!",
    "XSI":"XSI",
    "XSI:":"XSI",
    "XSIServerType":"XSI服務器類型",
    "YY/MM/DD":"YY/MM/DD",
    "YYYY-MM-DD":"YYYY-MM-DD",
    "Year":"年",
    "You can choose 5 customers at most!!!":"最多選擇5個客戶！",
    "You can click here to get more guides.":"您可以通過點擊這裡獲得更多幫助!",
    "You have changed the password!":"密碼已改變!",
    "You have changed the password":"密码已改变",
    "You should input at least one sip server address!!":"請至少配置1個SIP服務器！",
    "ZeroActive":"一鍵更新啟用",
    "account":"帳號",
    "Please select a correct file(.cfg)":"请选择正确的(.cfg)文件！",
    "account-adv-note":"<b>DTMF有效負荷類型:</b><br>選擇DTMF傳輸的類型.<br><br><br><br><b>NAT穿透：< /b><br>選擇是否使用STUN服務器去註冊.<br><br><br><b>RPort:</b><br>選擇是否告訴服務器只對話機使用的地址和端口做出響應.<br><br><br><b>Expire:</b><br>用戶自己定義一個向服務器註冊的周期.",
    "account-basic-note":"<b>基本設定</b><br>設定帳號的語音留言特徵碼<br>",
    "account-codec-note":"編解碼優先權:</b><br>用戶可自己選擇使用的編解碼的優先權,可供選擇的編解碼包括G.711ULaw,G.711ALaw,<br >G.729,G.723.用戶至少要選擇一種codec.<br><br>",
    "account-register-note":"<b>顯示名稱:</b><br>撥打電話時對方話機上顯示的本機名字.<br><br><b>用戶名稱:</b>< br>由運營商提供的用戶名.<br><br><b>註冊帳號:</b><br>由運營商提供的註冊名.<br><br><b>密碼:</ b><br>註冊帳號對應的密碼.",
    "action_URI_allow_IP":"允許控制IP列表",
    "admin":"管理員",
    "auth error":"認證錯誤",
    "auto negotiate":"自適應速率",
    "auto_negotiate":"自適應速率",
    "call failed":"呼叫失敗",
    "call success":"呼叫成功",
    "contacts-LDAP-note":"<b>LDAP</b><br>開啟LDAP快速搜索連絡人功能的設定<br>",
    "contacts-broadsoft-note":"<b>網絡連絡人</b><br>用於管理員設定網絡連絡人相關參數.<br>",
    "contacts-callinfo-note":"<b>歷史記錄</b><br>用於管理員查看歷史記錄.<br>",
    "contacts-favorite-note":"<b>連絡人</b><br>用於管理員設定連絡人相關參數.<br>",
    "contacts-multicastIP-note":"<b>組播</b><br>填寫所需要接收的組播地址（格式為IP:端口），並配置相應的標籤",
    "contacts-preview-note":"联系人预览",
    "contacts-remote-note":"<B>遠程電話簿</b><br>該功能允許你從服務器中下載​​連絡人訊息，需要在網頁中配置電話簿的地址和名字。",
    "contactsbasic-note":" <B>添加連絡人</B><br>輸入連絡人訊息，連絡人名字不能為空!<br><br><br><b>刪除連絡人</b ><br>選擇方格中您要刪除的連絡人，點擊刪除按鈕進行刪除!<br><br><br><b>導入</b><br>以XML格式瀏覽文件。<br> <br><br><b>導出</b><br>點擊導出按鈕並給導出的文件命名。",
    "data":"數據",
    "default":"預設",
    "default_contact_image.png":"預設連絡人圖像.png",
    "default_photo":"預設相片",
    "dhcp_hostname":"DHCP設備名稱",
    "display_name":"顯示名稱",
    "download customs, please try latter!":"下載中請稍候重試！",
    "dsskey-ext-note":"<B>按鍵類型</B><br/>可編程功能鍵，類型可以為快速撥號，代答，保持，免打擾等。<b>按键事件</B><br/>自定义按键功能<br/><br/> <B>對講機</B><br/>啟用對講機模式，主要用於辦公室快速連接話務員或秘書。<br/><br/>",
    "dsskey-linekey-note":"<B>按鍵類型</B><br/>可編程功能鍵，類型可以為快速撥號，代答，保持，免打擾等。<b>按键事件</B><br/>自定义按键功能<br/><br/> <B>對講機</B><br/>啟用對講機模式，主要用於辦公室快速連接話務員或秘書。<br/><br/>",
    "dsskey-memoryke​​y-note":"<B>按鍵類型</B><br/>可編程功能鍵，類型可以為快速撥號，代答，保持，免打擾等。<b>按键事件</B><br/>自定义按键功能<br/><br/> <B>對講機</B><br/>啟用對講機模式，主要用於辦公室快速連接話務員或秘書。<br/><br/>",
    "dsskey-programkey-note":"<B>按鍵類型</B><br/>可編程功能鍵，類型可以為快速撥號，代答，保持，免打擾等。<b>按键事件</B><br/>自定义按键功能<br/><br/> <B>對講機</B><br/>啟用對講機模式，主要用於辦公室快速連接話務員或秘書。<br/><br/>",
    "elect_Country":"選擇國家",
    "encryption(SRTP)":"RTP加密模式",
    "favorite":"名片夾",
    "features-acd-note":"<b>呼叫中心</b><br>用於管理員設定呼叫中心相關參數.<br>",
    "features-actionurl-note":"<b>Action URL</b><br>設定ActionURL功能,開啟該功能後,話機所執行動作會發送到相應的服務器端<br>",
    "features-audio-note":"<b>聲音</b><br>用於管理員進行設定聲音相關參數.<br>",
    "features-bluetooth-note":"<b>蓝牙</b><br><br>",
    "features-callpickup-note":"<b>截答</b><br>用於管理員設定截答相關參數.<br>",
    "features-forward-note":"<b>無條件前轉:</b><br>把所有的電話都轉接到設定的電話號碼上.<br><br><b>無應答前轉:</b><br>如果沒有應答就把電話轉接到設定的電話號碼上.<br><br><b>遇忙前轉:</b><br>如果正在通話中就把電話轉接到設定的電話.",
    "features-general-note":"<B>呼叫等待</B><br>此功能允許你在通話中接收另一路新來電！<br><br><B>自動應答</B>< br>自動接聽來電。<br><br><B>發送鍵</B><br>設定*或#作為發送鍵。<br><br><B>熱線號碼</B><br>當你拿起話機手柄或免提模式下，話機將會自動呼出該號碼。",
    "features-intercom-note":"<b>對講機</b><br>用於管理員設定對講機相關參數.<br>",
    "features-notification-popups-note":"<b>彈出通知窗口</b><br>用於管理員設定彈出通知窗口參數.<br>",
    "features-phonelock-note":"<b>鍵盤鎖</b><br>用於管理員設定鍵盤鎖相關參數.<br>",
    "features-power-led-note":"<b>電源燈</b><br>用於管理員設定電源燈相關參數.<br>",
    "features-remotecontrl-note":"<B>遠程控制簿</b><br>用於管理員設定遠程控制挂機相關參數",
    "features-sms-note":"<b>發送號碼:</b><br>填寫要發送短消息的目標號碼.",
    "features-transfer-note":"<b>呼叫轉移</b><br>用於管理員設定呼轉相關參數.<br>",
    "float":"懸浮",
    "forward should disable when Lock&Answer":"鍵盤鎖定後禁止來電前轉操作！",
    "full duplex,100Mbpss":"100M全雙工速率",
    "full duplex,10Mbps":"10M全雙工速率",
    "full_duplex_1000Mbps":"1000M全雙工速率",
    "full_duplex_100Mbps":"100M全雙工速率",
    "full_duplex_10Mbps":"10M全雙工速率",
    "g_arrayNoticeInfo//[2]":"g_arrayNoticeInfo",
    "group_id_name":"群組名稱",
    "half duplex,100Mbps":"100M半雙工速率",
    "half duplex,10Mbps":"10M半雙工速率",
    "half_duplex_100Mbps":"100M半雙工速率",
    "half_duplex_10Mbps":"10M半雙工速率",
    "hang up failed":"掛斷失敗",
    "hangup failed":"結束通話失敗！",
    "hangup success":"結束通話成功！",
    "hidden-note":"隱藏頁面",
    "iLBC":"iLBC",
    "iLBC_15_2 and iLBC_13_3 can not be applied simultaneously":"iLBC 15.2和iLBC 13.3不可同時使用！",
    "icon_blacklist_b.png":"icon_blacklist_b.png",
    "icon_family_b.png":"icon_family_b.png",
    "icon_friend_b.png":"icon_friend_b.png",
    "ignore":"忽略",
    "index_id":"序號",
    "info":"特殊訊息",
    "innerHtml":"innerHtml",
    "jumpto":"跳轉到",
    "ldap":"LDAP",
    "ldap+StartTLS":"LDAP 開始加密傳輸",
    "ldaps":"LDAPs",
    "line":"線路",
    "lock":"鎖定",
    "memory":"記憶鍵",
    "mobile_number":"移動電話",
    "network-adv-note":"<b>網絡高級設定</b><br>用於管理員設定網絡相關的高級參數",
    "network-note":"<b>自動獲得IP地址:</b><br>話機自動向DHCP服務器請求獲得IP地址,子網掩碼,網關,DNS等.<br><br><br ><b>靜態IP地址:</b><br>手動配置IP地址,子網掩碼,網關,DNS等.<br><br><br><b>xDSL(PPPoE):</b ><br>這是DSL提供的最常用的設定,要求輸入ISP提供的用戶名和密碼.",
    "network-pcport-note":"<b>PC口</b><br>用於管理員設定PC口相關參數.<br><br>",
    "num":"號碼",
    "office_number":"辦公電話",
    "other_number":"其它電話",
    "pcport_active":"PC接口啟動",
    "photo_data":"版本數據",
    "precondition":"預處理",
    "proxy require can not contain ! and &":"! 和& 為非法字符！",
    "retransmition":"臨時響應的可靠傳輸",
    "ring":"鈴聲",
    "seconds":" (秒)",
    "security-note":"<b>口令類型:</b><br>用戶選擇登陸的權限,管理員權限可以修改用戶的密碼和自己的密碼,但是用戶權限只能修改自己的密碼",
    "server-cert-note":"<b>服務證書</b><br>服務證書列表.<br>",
    "settings-autop-note":"<b>自動部署</b><br>用於管理員設定自動部署相關參數<br>",
    "settings-calldisplay-note":"<b>來電顯示</b><br>用於管理員設定來電顯示相關參數.<br>",
    "settings-config-note":"<b>配置</b><br>用於管理員設定話機配置相關參數.<br>",
    "settings-datetime-note":"<b>時區:</b><br>選擇您所在的時區.<br><br><b>服務器:</b><br>設定獲取時間的服務器.<br><br><b>更新時間間隔:</b><br>設定到服務器校對本機時間的間隔,預設值是1000秒",
    "settings-dialplan-note":"<b>替換規則:</b><br>用戶可以自定義規則,使號碼的字符或者字符串被替換成別的字符或字符串.比如把0替換成0086，那當用戶撥0的時候實際撥出的號碼是0086。<br>注意：在替換時，通過加括號將查找的內容存儲起來，使用$1,$2….$9來對應獲取查找的內容(括號的順序為序號)。<br><br><b>立即撥出規則:</b><br>用戶可以自定義規則,凡是滿足規則的號碼都將被立即撥出去,而不需要按發送鍵.比如設定為xxx,那按了任意三個數字都將被視為電話號碼被送出.<br><br><b>最小/大長度:</b><br>本機號碼最小/大長度.<br><br><b>帳號:</b><br>用戶可以自定義帳號,凡是在該帳號下添加的撥號規則,用該帳號將會生效,其他帳號下不生效,例如填寫1,則只有帳號1生效,可以填寫多個帳號,如1,2,3,用逗號隔開",
    "settings-preference-note":"<b>語言:</b><br>選擇網頁顯示語言.<br><br><b>鈴聲:</b><br>設定話機響鈴鈴聲. <br><br><b>自定義鈴聲:</b><br>上傳自定義鈴聲，並作為響鈴鈴聲",
    "settings-ring-note":"<b>區別振鈴</b><br>用於管理員設定區別振鈴相關參數.<br>",
    "settings-sip-note":"<b>SIP</b><br>用於管理員設定SIP相關參數.<br>",
    "settings-softkey-note":"<b>自定義可編程鍵</b><br>用於管理員設定自定義可編程按鍵<br>",
    "settings-tones-note":"<b>選擇國家</b><br>選擇您所在的國家。在自定義模式下，您可以手動配置信號音的值，格式為element = [!]freq [+freq2][/duration]<br><br>",
    "settings-tr069-note":"<b>TR069</b><br>用於管理員設定TR069功能相關參數.<br>",
    "settings-upgrade-note":"<b>恢復出廠設定:</b><br>這將使所有設定重置為出廠預設值,您的所有設定將被刪除.<br><br>< b>從本機硬盤更新:</b><br>從本機硬盤選擇您要更新的文件.",
    "settings-voice-note":"<b>聲音</b><br>用於管理員設定聲音相關參數.<br>",
    "Please select a correct file(.cfg)":"請選擇一個正確的(.cfg)文件",
    "settings-voicemonitoring-note":"语音监听",
    "sip server port should be a number !!":"SIP服務器端口需為數字！",
    "span to pc port":"透傳到PC端口",
    "span to pc":"透傳到PC",
    "status-note":"<b>版本號:</b><br>顯示設備當前的韌體版本號.<br><br><br><b>網絡配置:</b><br>顯示Internet口和PC口的網絡情況.<br><br><br><b>帳號:</b><br>顯示註冊的SIP帳號的狀態和SIP服務器.",
    "text":"文本",
    "title_802_1_x":"802.1x",
    "title_LLDP":"LLDP",
    "trusted-cert-note":"<b>受信任證書</b><br>受信任證書列表.<br>",
    "upgrade:fail":"升級：失敗",
    "user":"用戶名",
    "var":"var",
    "vpn":"VPN",
    "zero sp touch":"一鍵更新",
    "Are you sure to reset the local configuration?":"Are you sure to reset the local configuration",
    "Accept SIP Trust Server Only":"Accept SIP Trust Server Only",
    "Auto Linekeys":"Auto Linekeys",

    "Type can not be \"Line\" when AutoLinekeys is on!":"Type can not be \"Line\" when AutoLinekeys is on!",
    "Error: The max replace rule count is ":"Error: The max replace rule count is",
    "Day":"Day",
    "Outbound Proxy1":"Outbound Proxy1",
    "Outbound Proxy2":"Outbound Proxy2",

    "Proxy Fallback Interval is invalid!":"Proxy Fallback Interval is invalid!",
    "Bridge ID":"Bridge ID",
    "Reset local configurations?":"Reset local configurations?",
    "Advice of Charge":"Advice of Charge",
    "AOC Display Time":"AOC Display Time",
    "Shared Call Appearance":"Shared Call Appearance",
    "Enable auto answer tone":"啟用自动应答提示音",
    "Delay must more than 20 !":"Delay must more than 20 !",
    "Open Call Waiting":"啟用呼叫等待",
    "Close Call Waiting":"啟用呼叫等待",
    "Outbound Proxy Server 1":"Outboundd代理服務器1",
    "Outbound Proxy Server 2":"Outboundd代理服務器2",
    "Forward Emergency":"呼叫轉移緊急號碼",
    "Forward Authorized Numbers":"呼叫轉移鑑權號碼",
    "Headset":"使用耳麥",
    "Handfree":"使用免提",
    "Cancel Call Out":"取消呼出",
    "Remote Busy":"Remote Busy",
    "Call Remote Canceled":"Call Remote Canceled",
    "Proxy Fallback Interval":"代理回退間隔",
    "Attempt Expired Time(s)":"獲取配置文件超時時間(秒)",
    "Warning threshold for Moslq":"通話質量警戒值",
    "Warning threshold for Delay":"通話時延警戒值",
